"""Type stubs for the :mod:`pdfspine` package."""

from . import _core as _core
from . import constants as constants
from ._core import (
    PdfDecodeError as PdfDecodeError,
    PdfError as PdfError,
    PdfLimitError as PdfLimitError,
    PdfPasswordError as PdfPasswordError,
    PdfRedactionError as PdfRedactionError,
    PdfSyntaxError as PdfSyntaxError,
    PdfUnsupportedError as PdfUnsupportedError,
    identity_matrix as identity_matrix,
)
from .constants import *  # noqa: F403
from .document import (
    Annot as Annot,
    Colorspace as Colorspace,
    DisplayList as DisplayList,
    Document as Document,
    Link as Link,
    Outline as Outline,
    Page as Page,
    Pixmap as Pixmap,
    Shape as Shape,
    Table as Table,
    TableFinder as TableFinder,
    TextPage as TextPage,
    TextWriter as TextWriter,
    Widget as Widget,
    csCMYK as csCMYK,
    csGRAY as csGRAY,
    csRGB as csRGB,
    linkDest as linkDest,
    open as open,
)
from .geometry import (
    IRect as IRect,
    Matrix as Matrix,
    Point as Point,
    Quad as Quad,
    Rect as Rect,
)
from .helpers import (
    Base14_fontdict as Base14_fontdict,
    ConversionHeader as ConversionHeader,
    ConversionTrailer as ConversionTrailer,
    get_pdf_now as get_pdf_now,
    get_pdf_str as get_pdf_str,
    get_text_length as get_text_length,
    glyph_name_to_unicode as glyph_name_to_unicode,
    image_profile as image_profile,
    log as log,
    message as message,
    planish_line as planish_line,
    recover_bbox_quad as recover_bbox_quad,
    recover_char_quad as recover_char_quad,
    recover_line_quad as recover_line_quad,
    recover_quad as recover_quad,
    recover_span_quad as recover_span_quad,
    sRGB_to_pdf as sRGB_to_pdf,
    sRGB_to_rgb as sRGB_to_rgb,
    set_log as set_log,
    set_messages as set_messages,
    unicode_to_glyph_name as unicode_to_glyph_name,
)

__version__: str

def install_fitz_shim() -> None: ...

__all__ = [
    "__version__",
    "identity_matrix",
    "install_fitz_shim",
    "open",
    "Document",
    "Page",
    "Pixmap",
    "DisplayList",
    "TextPage",
    "Annot",
    "Widget",
    "Shape",
    "Table",
    "TableFinder",
    "Link",
    "linkDest",
    "Outline",
    "Colorspace",
    "TextWriter",
    "csGRAY",
    "csRGB",
    "csCMYK",
    "Rect",
    "IRect",
    "Point",
    "Matrix",
    "Quad",
    "PdfError",
    "PdfSyntaxError",
    "PdfPasswordError",
    "PdfUnsupportedError",
    "PdfDecodeError",
    "PdfLimitError",
    "PdfRedactionError",
    "constants",
    "Base14_fontdict",
    "ConversionHeader",
    "ConversionTrailer",
    "get_pdf_now",
    "get_pdf_str",
    "get_text_length",
    "glyph_name_to_unicode",
    "image_profile",
    "log",
    "message",
    "planish_line",
    "recover_bbox_quad",
    "recover_char_quad",
    "recover_line_quad",
    "recover_quad",
    "recover_span_quad",
    "sRGB_to_pdf",
    "sRGB_to_rgb",
    "set_log",
    "set_messages",
    "unicode_to_glyph_name",
]
