"""Optional Microsoft Table Transformer (TATR) table backend.

The two neural networks only predict table regions and structure.  Cell text is
always filled from pdfspine's native word coordinates (or its built-in OCR when
the page has no text layer), so numeric strings are not regenerated by a model.

Torch, Transformers and Pillow are imported lazily.  Importing :mod:`pdfspine`
therefore has no ML dependency and never loads or downloads a checkpoint.
"""

from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass, field, fields
from html import escape
import math
import os
import platform
from pathlib import Path
import sys
import threading
from typing import Any, Mapping

from . import _tatr_postprocess as _postprocess
from ._core import PdfUnsupportedError


DETECTION_MODEL = "microsoft/table-transformer-detection"
DETECTION_REVISION = "34669b5e93083671f6ccd7aca07d615a79772286"
STRUCTURE_MODEL = "microsoft/table-transformer-structure-recognition-v1.1-all"
STRUCTURE_REVISION = "7587a7ef111d9dcbf8ac695f1376ab7014340a0c"

_DETECTION_LABELS = {
    0: "table",
    1: "table rotated",
    2: "no object",
}
_STRUCTURE_LABELS = {
    0: "table",
    1: "table column",
    2: "table row",
    3: "table column header",
    4: "table projected row header",
    5: "table spanning cell",
    6: "no object",
}
_STRUCTURE_LABEL_IDS = {name: label for label, name in _STRUCTURE_LABELS.items()}


@dataclass(frozen=True)
class TatrOptions:
    """Validated options for the opt-in TATR backend."""

    dpi: int = 144
    device: str = "auto"
    detection_model: str = DETECTION_MODEL
    detection_revision: str | None = DETECTION_REVISION
    structure_model: str = STRUCTURE_MODEL
    structure_revision: str | None = STRUCTURE_REVISION
    detection_threshold: float = 0.5
    structure_threshold: float = 0.5
    crop_padding: int = 10
    local_files_only: bool = True
    ocr_if_no_text: bool = True
    native_line_guidance: bool = True
    adaptive_crop: bool = True
    ocr_engine: str = "paddle"
    ocr_language: str = "eng"

    def __post_init__(self) -> None:
        if type(self.dpi) is not int:
            raise TypeError("TATR dpi must be an int")
        if type(self.crop_padding) is not int:
            raise TypeError("TATR crop_padding must be an int")
        for name in ("detection_threshold", "structure_threshold"):
            value = getattr(self, name)
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                raise TypeError(f"TATR {name} must be a real number")
            object.__setattr__(self, name, float(value))
        for name in (
            "device",
            "detection_model",
            "structure_model",
            "ocr_engine",
            "ocr_language",
        ):
            if not isinstance(getattr(self, name), str):
                raise TypeError(f"TATR {name} must be a string")
        object.__setattr__(self, "device", self.device.casefold().strip())
        for name in ("detection_revision", "structure_revision"):
            value = getattr(self, name)
            if value is not None and not isinstance(value, str):
                raise TypeError(f"TATR {name} must be a string or None")
        for name in (
            "local_files_only",
            "ocr_if_no_text",
            "native_line_guidance",
            "adaptive_crop",
        ):
            if type(getattr(self, name)) is not bool:
                raise TypeError(f"TATR {name} must be a bool")
        self._validate()

    @classmethod
    def from_mapping(cls, value: Mapping[str, object] | None) -> "TatrOptions":
        if value is None:
            result = cls()
        elif not isinstance(value, Mapping):
            raise TypeError("vision_options must be a mapping or None")
        else:
            known = {field.name for field in fields(cls)}
            unknown = sorted((key for key in value if key not in known), key=str)
            if unknown:
                raise TypeError(
                    "unknown TATR option(s): " + ", ".join(str(k) for k in unknown)
                )
            result = cls(**dict(value))  # type: ignore[arg-type]
        return result

    def _validate(self) -> None:
        if not 36 <= self.dpi <= 600:
            raise ValueError("TATR dpi must be between 36 and 600")
        if not math.isfinite(self.detection_threshold):
            raise ValueError("TATR detection_threshold must be finite")
        if not 0.0 <= self.detection_threshold <= 1.0:
            raise ValueError("TATR detection_threshold must be in [0, 1]")
        if not math.isfinite(self.structure_threshold):
            raise ValueError("TATR structure_threshold must be finite")
        if not 0.0 <= self.structure_threshold <= 1.0:
            raise ValueError("TATR structure_threshold must be in [0, 1]")
        if not 0 <= self.crop_padding <= 20:
            raise ValueError("TATR crop_padding must be between 0 and 20 pixels")
        if self.device not in {"auto", "cpu", "cuda", "mps"}:
            cuda_prefix, separator, cuda_index = self.device.partition(":")
            if cuda_prefix != "cuda" or separator != ":" or not cuda_index.isdecimal():
                raise ValueError(
                    "TATR device must be 'auto', 'cpu', 'cuda', 'cuda:N', or 'mps'"
                )
        if not self.detection_model.strip() or not self.structure_model.strip():
            raise ValueError("TATR model identifiers must not be empty")
        if not self.ocr_engine.strip() or not self.ocr_language.strip():
            raise ValueError("TATR OCR engine and language must not be empty")


@dataclass
class _RenderedPage:
    image: Any
    tokens: list[dict[str, Any]]
    page_bbox: tuple[float, float, float, float]
    scale_x: float
    scale_y: float
    text_source: str
    rotation: int = 0
    unrotated_size: tuple[float, float] | None = None


@dataclass
class _TableCrop:
    image: Any
    tokens: list[dict[str, Any]]
    bbox: tuple[float, float, float, float]
    rotated: bool
    unrotated_size: tuple[int, int]


def _model_sources(options: TatrOptions) -> tuple[str, str]:
    """Resolve explicit model refs, optionally from ``PDFSPINE_TATR_MODELS``."""

    detection = os.environ.get("PDFSPINE_TATR_DETECTION_MODEL", options.detection_model)
    structure = os.environ.get("PDFSPINE_TATR_STRUCTURE_MODEL", options.structure_model)
    root = os.environ.get("PDFSPINE_TATR_MODELS")
    if root:
        base = Path(root).expanduser()
        det_dir = base / "detection"
        struct_dir = base / "structure-recognition-v1.1-all"
        if detection == DETECTION_MODEL and det_dir.is_dir():
            detection = os.fspath(det_dir)
        if structure == STRUCTURE_MODEL and struct_dir.is_dir():
            structure = os.fspath(struct_dir)
    return detection, structure


def _model_kwargs(source: str, revision: str | None, local_only: bool) -> dict[str, Any]:
    kwargs: dict[str, Any] = {
        "local_files_only": local_only,
        "trust_remote_code": False,
    }
    if revision and not Path(source).expanduser().exists():
        kwargs["revision"] = revision
    return kwargs


def _runtime_platform_error(
    *,
    python_version: tuple[int, int] | None = None,
    platform_name: str | None = None,
    machine: str | None = None,
    libc_name: str | None = None,
) -> str | None:
    """Explain platforms without a compatible prebuilt TATR/PyTorch stack."""

    version = python_version or (sys.version_info.major, sys.version_info.minor)
    os_name = platform_name or sys.platform
    arch = (machine or platform.machine()).casefold()
    if version >= (3, 15):
        return "the prebuilt TATR runtime currently supports Python 3.12-3.14"
    if os_name not in {"darwin", "win32"} and not os_name.startswith("linux"):
        return f"prebuilt PyTorch wheels are not supported on platform {os_name!r}"
    if os_name == "darwin" and arch in {"x86_64", "amd64"}:
        return "current PyTorch wheels no longer support Intel macOS"
    if os_name == "darwin" and arch not in {"arm64", "aarch64"}:
        return "prebuilt PyTorch wheels on macOS require Apple Silicon"
    if os_name == "win32" and arch not in {"x86_64", "amd64"}:
        return "prebuilt PyTorch wheels on Windows require x86-64"
    if os_name.startswith("linux"):
        if arch not in {"x86_64", "amd64", "arm64", "aarch64"}:
            return "prebuilt PyTorch wheels on Linux require x86-64 or ARM64"
        libc = (libc_name if libc_name is not None else platform.libc_ver()[0]).casefold()
        if libc and libc != "glibc":
            return "prebuilt PyTorch wheels require a glibc-based Linux distribution"
    return None


def _missing_runtime(exc: BaseException) -> PdfUnsupportedError:
    unsupported = _runtime_platform_error()
    if unsupported:
        return PdfUnsupportedError(
            f"The optional TATR backend is unavailable on this platform: {unsupported}. "
            "Use Apple Silicon macOS, glibc Linux, or Windows with Python 3.12-3.14, "
            "or provide a separately validated source-built Torch runtime."
        )
    return PdfUnsupportedError(
        "TATR table extraction needs the optional ML runtime. Install it with "
        "`pip install 'pdfspine[tatr]'`. The base pdfspine wheel intentionally "
        f"does not include Torch/Transformers ({type(exc).__name__}: {exc})."
    )


class _TransformersRuntime:
    """Pinned TATR detector + structure recognizer, loaded once per process."""

    def __init__(
        self,
        options: TatrOptions,
        detection_source: str,
        structure_source: str,
    ) -> None:
        try:
            import torch
            from transformers import (
                AutoModelForObjectDetection,
                TableTransformerConfig,
            )
        except (ImportError, ModuleNotFoundError, OSError) as exc:
            raise _missing_runtime(exc) from exc

        self._torch = torch
        self.device = self._resolve_device(options.device)
        try:
            self.detector = self._load_model(
                AutoModelForObjectDetection,
                TableTransformerConfig,
                detection_source,
                options.detection_revision,
                options.local_files_only,
            )
            self.structure_model = self._load_model(
                AutoModelForObjectDetection,
                TableTransformerConfig,
                structure_source,
                options.structure_revision,
                options.local_files_only,
            )
        except Exception as exc:  # Transformers uses OSError for cache misses.
            mode = "local cache only" if options.local_files_only else "download allowed"
            raise PdfUnsupportedError(
                "Could not load the pinned TATR checkpoints "
                f"({mode}; {type(exc).__name__}: {exc}). Pre-fetch the two models "
                "into the Hugging Face cache, set PDFSPINE_TATR_MODELS to a model "
                "directory, or explicitly pass "
                "vision_options={'local_files_only': False} once to download them."
            ) from exc
        self.detector.eval()
        self.structure_model.eval()
        self._mean = torch.tensor(
            [0.485, 0.456, 0.406], dtype=torch.float32, device=self.device
        ).view(1, 3, 1, 1)
        self._std = torch.tensor(
            [0.229, 0.224, 0.225], dtype=torch.float32, device=self.device
        ).view(1, 3, 1, 1)
        self.metadata = {
            "backend": "tatr",
            "detection_model": detection_source,
            "detection_revision": (
                None
                if Path(detection_source).expanduser().exists()
                else options.detection_revision
            ),
            "structure_model": structure_source,
            "structure_revision": (
                None
                if Path(structure_source).expanduser().exists()
                else options.structure_revision
            ),
            "device": self.device,
            "preprocessing": "microsoft-maxresize-800/1000-imagenet",
        }

    def _load_model(
        self,
        auto_model: Any,
        config_class: Any,
        source: str,
        revision: str | None,
        local_files_only: bool,
    ) -> Any:
        """Load an old TATR config under Transformers' current strict schema.

        The pinned Microsoft checkpoints serialize the optional top-level
        ``dilation`` field as JSON null. Transformers 5.14 made that field a
        strict bool, so normalize exactly that legacy representation to the
        historical default (False) before constructing the config.
        """
        kwargs = _model_kwargs(source, revision, local_files_only)
        config_dict, _ = config_class.get_config_dict(source, **kwargs)
        if config_dict.get("dilation") is None:
            config_dict["dilation"] = False
        config = config_class.from_dict(config_dict)
        return auto_model.from_pretrained(source, config=config, **kwargs).to(self.device)

    def _resolve_device(self, requested: str) -> str:
        torch = self._torch
        device = requested.casefold().strip()
        if device == "auto":
            return "cuda" if torch.cuda.is_available() else "cpu"
        if device.startswith("cuda") and not torch.cuda.is_available():
            raise PdfUnsupportedError("TATR device='cuda' was requested but CUDA is unavailable")
        if (
            device.startswith("cuda:")
            and int(device.partition(":")[2]) >= torch.cuda.device_count()
        ):
            raise PdfUnsupportedError(
                f"TATR device={device!r} was requested but only "
                f"{torch.cuda.device_count()} CUDA device(s) are available"
            )
        if device == "mps":
            available = bool(
                getattr(getattr(torch, "backends", None), "mps", None)
                and torch.backends.mps.is_available()
            )
            if not available:
                raise PdfUnsupportedError("TATR device='mps' was requested but MPS is unavailable")
        return device

    def _tensor(self, image: Any, max_size: int) -> Any:
        torch = self._torch
        width, height = image.size
        scale = max_size / max(width, height)
        target = (max(1, round(width * scale)), max(1, round(height * scale)))
        resized = image.resize(target)
        raw = bytearray(resized.tobytes())
        tensor = torch.frombuffer(raw, dtype=torch.uint8)
        tensor = tensor.reshape(target[1], target[0], 3).permute(2, 0, 1)
        tensor = tensor.unsqueeze(0).to(device=self.device, dtype=torch.float32) / 255.0
        return (tensor - self._mean) / self._std

    def _predict(
        self,
        image: Any,
        model: Any,
        labels: Mapping[int, str],
        threshold: float,
        max_size: int,
    ) -> list[dict[str, Any]]:
        torch = self._torch
        pixel_values = self._tensor(image, max_size)
        with torch.inference_mode():
            outputs = model(pixel_values=pixel_values)
        probabilities = outputs.logits.softmax(-1)[0]
        scores, label_ids = probabilities.max(-1)
        boxes = outputs.pred_boxes[0]
        width, height = image.size
        results: list[dict[str, Any]] = []
        for score_t, label_t, box_t in zip(scores, label_ids, boxes):
            label_id = int(label_t.detach().cpu().item())
            name = labels.get(label_id, "no object")
            score = float(score_t.detach().cpu().item())
            if name == "no object" or score < threshold:
                continue
            cx, cy, bw, bh = (float(v) for v in box_t.detach().cpu().tolist())
            bbox = [
                (cx - bw / 2.0) * width,
                (cy - bh / 2.0) * height,
                (cx + bw / 2.0) * width,
                (cy + bh / 2.0) * height,
            ]
            results.append({"label": name, "score": score, "bbox": bbox})
        return results

    def detect(self, image: Any, threshold: float) -> list[dict[str, Any]]:
        return self._predict(
            image, self.detector, _DETECTION_LABELS, threshold, max_size=800
        )

    def recognize(self, image: Any, threshold: float) -> list[dict[str, Any]]:
        return self._predict(
            image,
            self.structure_model,
            _STRUCTURE_LABELS,
            threshold,
            max_size=1000,
        )


@dataclass(frozen=True)
class _RuntimeSpec:
    detection_source: str
    detection_revision: str | None
    structure_source: str
    structure_revision: str | None
    device: str
    # Loading policy is not model identity. If a caller explicitly downloads
    # once, a later offline/default call must reuse that exact in-memory model.
    local_files_only: bool = field(compare=False, hash=False)


_MODEL_CACHE: dict[_RuntimeSpec, _TransformersRuntime] = {}
_MODEL_CACHE_LOCK = threading.Lock()


def _cached_runtime(spec: _RuntimeSpec) -> _TransformersRuntime:
    # Keep construction inside the lock: functools.lru_cache may invoke the
    # wrapped function twice on concurrent first calls, which would briefly load
    # ~230 MB of weights twice (or exhaust GPU memory).
    with _MODEL_CACHE_LOCK:
        cached = _MODEL_CACHE.get(spec)
        if cached is not None:
            return cached
        options = TatrOptions(
            device=spec.device,
            detection_model=spec.detection_source,
            detection_revision=spec.detection_revision,
            structure_model=spec.structure_source,
            structure_revision=spec.structure_revision,
            local_files_only=spec.local_files_only,
        )
        runtime = _TransformersRuntime(
            options, spec.detection_source, spec.structure_source
        )
        if len(_MODEL_CACHE) >= 4:
            _MODEL_CACHE.pop(next(iter(_MODEL_CACHE)))
        _MODEL_CACHE[spec] = runtime
        return runtime


def clear_model_cache() -> None:
    """Drop Python references to cached TATR runtimes (mainly useful in tests)."""

    with _MODEL_CACHE_LOCK:
        _MODEL_CACHE.clear()


def _get_runtime(options: TatrOptions) -> _TransformersRuntime:
    detection_source, structure_source = _model_sources(options)
    return _cached_runtime(
        _RuntimeSpec(
            detection_source=detection_source,
            detection_revision=(
                None
                if Path(detection_source).expanduser().exists()
                else options.detection_revision
            ),
            structure_source=structure_source,
            structure_revision=(
                None
                if Path(structure_source).expanduser().exists()
                else options.structure_revision
            ),
            device=options.device,
            local_files_only=options.local_files_only,
        )
    )


def _native_words(
    page: Any, options: TatrOptions
) -> tuple[list[tuple[Any, ...]], str]:
    words = list(page.get_text("words", sort=True))
    if words or not options.ocr_if_no_text:
        return words, "pdfspine-native"
    try:
        textpage = page.get_textpage_ocr(
            dpi=options.dpi,
            language=options.ocr_language,
            engine=options.ocr_engine,
        )
        words = list(page.get_text("words", textpage=textpage, sort=True))
    except Exception:  # Structure extraction remains useful even without OCR.
        words = []
    return words, "pdfspine-ocr" if words else "none"


def _rotate_box_ccw(
    box: list[float] | tuple[float, ...],
    width: float,
    height: float,
    degrees: int,
) -> list[float]:
    """Rotate a continuous, half-open image box counter-clockwise."""

    x0, y0, x1, y1 = (float(value) for value in box)
    rotation = degrees % 360
    if rotation == 90:
        return [y0, width - x1, y1, width - x0]
    if rotation == 180:
        return [width - x1, height - y1, width - x0, height - y0]
    if rotation == 270:
        return [height - y1, x0, height - y0, x1]
    return [x0, y0, x1, y1]


def _normalized_box_to_display(
    box: tuple[float, float, float, float],
    width: float,
    height: float,
    rotation: int,
) -> tuple[float, float, float, float]:
    """Apply the PDF page rotation to a zero-based unrotated point box."""

    x0, y0, x1, y1 = box
    normalized = rotation % 360
    if normalized == 90:
        return height - y1, x0, height - y0, x1
    if normalized == 180:
        return width - x1, height - y1, width - x0, height - y0
    if normalized == 270:
        return y0, width - x1, y1, width - x0
    return box


def _display_box_to_normalized(
    box: tuple[float, float, float, float],
    width: float,
    height: float,
    rotation: int,
) -> tuple[float, float, float, float]:
    """Invert the PDF page rotation for a zero-based display-space box."""

    x0, y0, x1, y1 = box
    normalized = rotation % 360
    if normalized == 90:
        return y0, height - x1, y1, height - x0
    if normalized == 180:
        return width - x1, height - y1, width - x0, height - y0
    if normalized == 270:
        return width - y1, x0, width - y0, x1
    return box


def _render_page(page: Any, options: TatrOptions) -> _RenderedPage:
    try:
        from PIL import Image
    except (ImportError, ModuleNotFoundError) as exc:
        raise _missing_runtime(exc) from exc

    # Always replay the complete display list. ``Page.get_pixmap`` deliberately
    # has an image-only fast path that returns the source raster dimensions;
    # that is useful for extraction, but its pixels no longer share the page's
    # device coordinate system when an image is scaled or translated.
    pixmap = page.get_displaylist().get_pixmap(
        dpi=options.dpi, colorspace=3, alpha=False
    )
    if pixmap.n != 3:
        raise PdfUnsupportedError(
            f"TATR needs an RGB page render; pdfspine returned {pixmap.n} channels"
        )
    image = Image.frombytes("RGB", (pixmap.width, pixmap.height), bytes(pixmap.samples))
    cropbox = getattr(page, "cropbox", page.rect)
    if callable(cropbox):
        cropbox = cropbox()
    crop_rect = _box4(cropbox)
    unrotated_width = abs(crop_rect[2] - crop_rect[0])
    unrotated_height = abs(crop_rect[3] - crop_rect[1])
    rotation = getattr(page, "rotation", 0)
    if callable(rotation):
        rotation = rotation()
    rotation = int(rotation) % 360
    if rotation % 180:
        display_width, display_height = unrotated_height, unrotated_width
    else:
        display_width, display_height = unrotated_width, unrotated_height
    page_rect = (0.0, 0.0, display_width, display_height)
    if unrotated_width <= 0 or unrotated_height <= 0:
        return _RenderedPage(
            image,
            [],
            page_rect,
            1.0,
            1.0,
            "none",
            rotation,
            (unrotated_width, unrotated_height),
        )
    visible_scale_x = pixmap.width / display_width
    visible_scale_y = pixmap.height / display_height
    words, text_source = _native_words(page, options)
    tokens: list[dict[str, Any]] = []
    for index, word in enumerate(words):
        if len(word) < 5 or not str(word[4]):
            continue
        block = int(word[5]) if len(word) > 5 else 0
        line = int(word[6]) if len(word) > 6 else 0
        word_num = int(word[7]) if len(word) > 7 else index
        bbox = [
            float(word[0]) * visible_scale_x,
            float(word[1]) * visible_scale_y,
            float(word[2]) * visible_scale_x,
            float(word[3]) * visible_scale_y,
        ]
        if rotation:
            bbox = _rotate_box_ccw(
                bbox, float(pixmap.width), float(pixmap.height), rotation
            )
        tokens.append(
            {
                "bbox": bbox,
                "text": str(word[4]),
                "block_num": block,
                "line_num": line,
                "span_num": word_num,
            }
        )
    if rotation:
        image = image.rotate(rotation, expand=True)
    scale_x = image.size[0] / unrotated_width
    scale_y = image.size[1] / unrotated_height
    return _RenderedPage(
        image,
        tokens,
        page_rect,
        scale_x,
        scale_y,
        text_source,
        rotation,
        (unrotated_width, unrotated_height),
    )


def _area(box: list[float] | tuple[float, ...]) -> float:
    return max(0.0, box[2] - box[0]) * max(0.0, box[3] - box[1])


def _box4(values: Any) -> tuple[float, float, float, float]:
    x0, y0, x1, y1 = values
    return float(x0), float(y0), float(x1), float(y1)


def _intersection_area(a: Any, b: Any) -> float:
    return float(
        max(0.0, min(a[2], b[2]) - max(a[0], b[0]))
        * max(0.0, min(a[3], b[3]) - max(a[1], b[1]))
    )


def _iob(a: Any, b: Any) -> float:
    area = _area(a)
    return _intersection_area(a, b) / area if area > 0 else 0.0


def _make_crop(
    rendered: _RenderedPage,
    detection: Mapping[str, Any],
    padding: int,
) -> _TableCrop | None:
    image_width, image_height = rendered.image.size
    raw = detection["bbox"]
    bbox = (
        max(0.0, float(raw[0]) - padding),
        max(0.0, float(raw[1]) - padding),
        min(float(image_width), float(raw[2]) + padding),
        min(float(image_height), float(raw[3]) + padding),
    )
    if _area(bbox) <= 1.0:
        return None
    image = rendered.image.crop(bbox)
    tokens: list[dict[str, Any]] = []
    for token in rendered.tokens:
        if _iob(token["bbox"], bbox) < 0.5:
            continue
        copied = dict(token)
        tb = token["bbox"]
        copied["bbox"] = [
            tb[0] - bbox[0],
            tb[1] - bbox[1],
            tb[2] - bbox[0],
            tb[3] - bbox[1],
        ]
        tokens.append(copied)
    rotated = detection.get("label") == "table rotated"
    unrotated_size = image.size
    if rotated:
        image = image.rotate(270, expand=True)
        rotated_width = image.size[0]
        for token in tokens:
            x0, y0, x1, y1 = token["bbox"]
            token["bbox"] = [
                rotated_width - y1,
                x0,
                rotated_width - y0,
                x1,
            ]
    return _TableCrop(image, tokens, bbox, rotated, unrotated_size)


def _crop_box_to_page(
    box: Any,
    crop: _TableCrop,
    rendered: _RenderedPage,
) -> tuple[float, float, float, float]:
    x0, y0, x1, y1 = (float(v) for v in box)
    if crop.rotated:
        original_height = crop.unrotated_size[1]
        x0, y0, x1, y1 = (
            y0,
            original_height - x1,
            y1,
            original_height - x0,
        )
    px0, py0 = crop.bbox[0] + x0, crop.bbox[1] + y0
    px1, py1 = crop.bbox[0] + x1, crop.bbox[1] + y1
    return _image_box_to_page((px0, py0, px1, py1), rendered)


def _image_box_to_page(
    box: tuple[float, float, float, float] | list[float],
    rendered: _RenderedPage,
) -> tuple[float, float, float, float]:
    normalized_box = (
        float(box[0]) / rendered.scale_x,
        float(box[1]) / rendered.scale_y,
        float(box[2]) / rendered.scale_x,
        float(box[3]) / rendered.scale_y,
    )
    unrotated_size = rendered.unrotated_size
    if unrotated_size is None:
        if rendered.rotation % 180:
            unrotated_size = (rendered.page_bbox[3], rendered.page_bbox[2])
        else:
            unrotated_size = (rendered.page_bbox[2], rendered.page_bbox[3])
    display_box = _normalized_box_to_display(
        normalized_box,
        unrotated_size[0],
        unrotated_size[1],
        rendered.rotation,
    )
    page = rendered.page_bbox
    return tuple(
        max(page[index % 2], min(page[index % 2 + 2], value))
        for index, value in enumerate(display_box)
    )  # type: ignore[return-value]


def _page_box_to_image(
    box: tuple[float, float, float, float],
    rendered: _RenderedPage,
) -> tuple[float, float, float, float]:
    unrotated_size = rendered.unrotated_size
    if unrotated_size is None:
        if rendered.rotation % 180:
            unrotated_size = (rendered.page_bbox[3], rendered.page_bbox[2])
        else:
            unrotated_size = (rendered.page_bbox[2], rendered.page_bbox[3])
    normalized = _display_box_to_normalized(
        box,
        unrotated_size[0],
        unrotated_size[1],
        rendered.rotation,
    )
    return (
        normalized[0] * rendered.scale_x,
        normalized[1] * rendered.scale_y,
        normalized[2] * rendered.scale_x,
        normalized[3] * rendered.scale_y,
    )


def _native_line_anchors(page: Any, clip: Any) -> list[tuple[float, float, float, float]]:
    if page is None or not hasattr(page, "find_tables"):
        return []
    try:
        finder = page.find_tables(strategy="lines", clip=clip)
        tables = list(getattr(finder, "tables", finder))
        return [
            bbox
            for table in tables
            if _area(bbox := _box4(table.bbox)) > 1.0
        ]
    except Exception:
        # Vector guidance is optional; TATR remains usable on scans and on PDFs
        # whose drawing operators the native line detector cannot interpret.
        return []


def _guided_detection(
    detection: Mapping[str, Any],
    anchors: list[tuple[float, float, float, float]],
    rendered: _RenderedPage,
    used_anchors: set[int],
) -> tuple[dict[str, Any], tuple[float, float, float, float], bool]:
    result = dict(detection)
    detection_page_bbox = _image_box_to_page(_box4(detection["bbox"]), rendered)
    best: tuple[float, int] | None = None
    detection_area = _area(detection_page_bbox)
    for index, anchor in enumerate(anchors):
        if index in used_anchors:
            continue
        anchor_area = _area(anchor)
        if detection_area <= 0 or anchor_area <= 0:
            continue
        area_ratio = anchor_area / detection_area
        if not 0.25 <= area_ratio <= 6.0:
            continue
        containment = _iob(detection_page_bbox, anchor)
        if containment < 0.75:
            continue
        score = containment + _intersection_area(detection_page_bbox, anchor) / anchor_area
        if best is None or score > best[0]:
            best = (score, index)
    if best is None:
        return result, detection_page_bbox, False
    anchor_index = best[1]
    used_anchors.add(anchor_index)
    result["bbox"] = _page_box_to_image(anchors[anchor_index], rendered)
    return result, detection_page_bbox, True


def _structure_crop_edges(
    objects: list[dict[str, Any]], image_size: tuple[int, int]
) -> set[str]:
    tables = [obj for obj in objects if obj.get("label") == "table"]
    if not tables:
        return {"left", "top", "right", "bottom"}
    table = max(tables, key=lambda obj: float(obj.get("score", 0.0)))
    x0, y0, x1, y1 = _box4(table["bbox"])
    width, height = image_size
    # The official crop already carries 10px context. A structure box entering
    # roughly that guard band is evidence the detector crop, rather than the
    # true table edge, may be constraining recognition.
    margin_x = max(2.0, min(12.0, width * 0.05))
    margin_y = max(2.0, min(12.0, height * 0.05))
    edges: set[str] = set()
    if x0 <= margin_x:
        edges.add("left")
    if y0 <= margin_y:
        edges.add("top")
    if x1 >= width - margin_x:
        edges.add("right")
    if y1 >= height - margin_y:
        edges.add("bottom")
    return edges


def _unrotate_crop_edges(edges: set[str], rotated: bool) -> set[str]:
    if not rotated:
        return edges
    # ``_make_crop`` rotates a detector crop 270° (clockwise) before TSR.
    mapping = {
        "left": "bottom",
        "right": "top",
        "top": "left",
        "bottom": "right",
    }
    return {mapping[edge] for edge in edges}


def _detection_expansion_limits(
    detection: Mapping[str, Any],
    detections: list[dict[str, Any]],
    image_size: tuple[int, int],
) -> tuple[float, float, float, float]:
    current = _box4(detection["bbox"])
    cx = (current[0] + current[2]) / 2.0
    cy = (current[1] + current[3]) / 2.0
    left, top, right, bottom = 0.0, 0.0, float(image_size[0]), float(image_size[1])
    for other in detections:
        if other is detection or other.get("label") not in {"table", "table rotated"}:
            continue
        box = _box4(other["bbox"])
        ocx = (box[0] + box[2]) / 2.0
        ocy = (box[1] + box[3]) / 2.0
        vertical_overlap = min(current[3], box[3]) - max(current[1], box[1])
        horizontal_overlap = min(current[2], box[2]) - max(current[0], box[0])
        if vertical_overlap > 0:
            if ocx < cx:
                left = max(left, (box[2] + current[0]) / 2.0)
            elif ocx > cx:
                right = min(right, (current[2] + box[0]) / 2.0)
        if horizontal_overlap > 0:
            if ocy < cy:
                top = max(top, (box[3] + current[1]) / 2.0)
            elif ocy > cy:
                bottom = min(bottom, (current[3] + box[1]) / 2.0)
    # Overlapping detector proposals can put a midpoint *inside* the current
    # proposal. Limits may stop an expansion, but must never turn it into a
    # contraction that discards already detected table content.
    return (
        min(left, current[0]),
        min(top, current[1]),
        max(right, current[2]),
        max(bottom, current[3]),
    )


def _expand_detection(
    detection: Mapping[str, Any],
    edges: set[str],
    limits: tuple[float, float, float, float],
    ratio: float = 0.25,
) -> dict[str, Any]:
    result = dict(detection)
    x0, y0, x1, y1 = _box4(detection["bbox"])
    grow_x = max(1.0, (x1 - x0) * ratio)
    grow_y = max(1.0, (y1 - y0) * ratio)
    if "left" in edges:
        x0 = max(limits[0], x0 - grow_x)
    if "top" in edges:
        y0 = max(limits[1], y0 - grow_y)
    if "right" in edges:
        x1 = min(limits[2], x1 + grow_x)
    if "bottom" in edges:
        y1 = min(limits[3], y1 + grow_y)
    result["bbox"] = (x0, y0, x1, y1)
    return result


def _grid_boundaries(boxes: list[tuple[float, float, float, float]], axis: int) -> list[float]:
    if not boxes:
        return []
    boxes = sorted(boxes, key=lambda box: box[axis])
    end_axis = axis + 2
    boundaries = [boxes[0][axis]]
    for previous, current in zip(boxes, boxes[1:]):
        boundaries.append((previous[end_axis] + current[axis]) / 2.0)
    boundaries.append(boxes[-1][end_axis])
    return boundaries


class _TatrTableRecord:
    """Duck-typed core table consumed by the public :class:`Table` wrapper."""

    def __init__(
        self,
        cells: list[dict[str, Any]],
        row_boxes: list[tuple[float, float, float, float]],
        column_boxes: list[tuple[float, float, float, float]],
        confidence: float,
        text_source: str,
        metadata: Mapping[str, Any],
        rotated: bool = False,
    ) -> None:
        self.row_count = max(
            len(row_boxes),
            max((max(c["row_nums"]) for c in cells), default=-1) + 1,
        )
        self.col_count = max(
            len(column_boxes),
            max((max(c["column_nums"]) for c in cells), default=-1) + 1,
        )
        self.rows = _grid_boundaries(row_boxes, 0 if rotated else 1)
        self.cols = _grid_boundaries(column_boxes, 1 if rotated else 0)
        self.confidence = float(confidence)
        self.source = "tatr"
        self.text_source = text_source
        self.metadata = dict(metadata)
        candidates = sorted(
            cells, key=lambda c: (min(c["row_nums"]), min(c["column_nums"]))
        )
        self.cells: list[list[tuple[float, float, float, float] | None]] = [
            [None for _ in range(self.col_count)] for _ in range(self.row_count)
        ]
        self._text: list[list[str | None]] = [
            [None for _ in range(self.col_count)] for _ in range(self.row_count)
        ]
        self._covered: set[tuple[int, int]] = set()
        self._by_origin: dict[tuple[int, int], dict[str, Any]] = {}
        self.spans: list[tuple[int, int, int, int, tuple[float, float, float, float]]] = []
        accepted: list[dict[str, Any]] = []
        for cell in candidates:
            rows = sorted(set(int(v) for v in cell["row_nums"]))
            columns = sorted(set(int(v) for v in cell["column_nums"]))
            if not rows or not columns:
                continue
            if rows != list(range(rows[0], rows[-1] + 1)):
                continue
            if columns != list(range(columns[0], columns[-1] + 1)):
                continue
            origin = (rows[0], columns[0])
            slots = {(row, column) for row in rows for column in columns}
            if slots & self._covered:
                continue
            rect = _box4(cell["bbox"])
            if _area(rect) <= 0 or not all(math.isfinite(v) for v in rect):
                continue
            self._covered.update(slots)
            accepted.append(cell)
            self._by_origin[origin] = cell
            self.cells[origin[0]][origin[1]] = rect
            text = str(cell.get("cell_text") or "")
            self._text[origin[0]][origin[1]] = text or None
            self.spans.append(
                (origin[0], origin[1], len(rows), len(columns), rect)
            )
        self._records = accepted
        if row_boxes and column_boxes:
            self.bbox = (
                min(column[0] for column in column_boxes),
                min(row[1] for row in row_boxes),
                max(column[2] for column in column_boxes),
                max(row[3] for row in row_boxes),
            )
        else:
            valid_rects = [span[4] for span in self.spans]
            self.bbox = (
                (
                    min(r[0] for r in valid_rects),
                    min(r[1] for r in valid_rects),
                    max(r[2] for r in valid_rects),
                    max(r[3] for r in valid_rects),
                )
                if valid_rects
                else (0.0, 0.0, 0.0, 0.0)
            )
        first_row_header = any(
            min(cell["row_nums"]) == 0
            and bool(cell.get("header") or cell.get("subheader"))
            for cell in self._records
        )
        self.header = list(self._text[0]) if self.row_count and first_row_header else []

    @property
    def grits_cells(self) -> list[dict[str, Any]]:
        return [
            {
                "row_nums": list(cell["row_nums"]),
                "column_nums": list(cell["column_nums"]),
                "bbox": list(cell["bbox"]),
                "cell_text": str(cell.get("cell_text") or ""),
                "header": bool(cell.get("header")),
                "projected_row_header": bool(cell.get("subheader")),
                "text_source": self.text_source,
            }
            for cell in self._records
        ]

    def extract(self) -> list[list[str | None]]:
        return [list(row) for row in self._text]

    def to_markdown(self) -> str:
        if not self.row_count or not self.col_count:
            return ""

        def value(row: int, column: int) -> str:
            text = self._text[row][column] or ""
            return text.replace("\n", " ").replace("|", r"\|").strip()

        lines = [
            "| " + " | ".join(value(0, column) for column in range(self.col_count)) + " |",
            "| " + " | ".join("---" for _ in range(self.col_count)) + " |",
        ]
        lines.extend(
            "| " + " | ".join(value(row, column) for column in range(self.col_count)) + " |"
            for row in range(1, self.row_count)
        )
        return "\n".join(lines) + "\n"

    def to_html(self) -> str:
        out = ["<table>"]
        for row in range(self.row_count):
            out.append("<tr>")
            for column in range(self.col_count):
                record = self._by_origin.get((row, column))
                if record is None:
                    if (row, column) not in self._covered:
                        out.append("<td></td>")
                    continue
                rows = record["row_nums"]
                columns = record["column_nums"]
                tag = "th" if record.get("header") or record.get("subheader") else "td"
                attrs = ""
                if len(columns) > 1:
                    attrs += f' colspan="{len(columns)}"'
                if len(rows) > 1:
                    attrs += f' rowspan="{len(rows)}"'
                text = escape(str(record.get("cell_text") or "")).replace("\n", "<br>")
                out.append(f"<{tag}{attrs}>{text}</{tag}>")
            out.append("</tr>")
        out.append("</table>")
        return "".join(out)


class _TatrTableFinderRecord:
    def __init__(self, tables: list[_TatrTableRecord]) -> None:
        self.tables = tables

    def __len__(self) -> int:
        return len(self.tables)

    def __getitem__(self, index: int) -> _TatrTableRecord:
        return self.tables[index]


def _grid_cell_bbox(
    cell: Mapping[str, Any],
    rows: list[dict[str, Any]],
    columns: list[dict[str, Any]],
) -> tuple[float, float, float, float]:
    """Rebuild a cell from the refined grid, before text-tight adjustment."""

    row_nums = [int(value) for value in cell["row_nums"]]
    column_nums = [int(value) for value in cell["column_nums"]]
    selected_rows = [_box4(rows[index]["bbox"]) for index in row_nums]
    selected_columns = [_box4(columns[index]["bbox"]) for index in column_nums]
    return (
        min(box[0] for box in selected_columns),
        min(box[1] for box in selected_rows),
        max(box[2] for box in selected_columns),
        max(box[3] for box in selected_rows),
    )


def _table_from_structure(
    objects: list[dict[str, Any]],
    crop: _TableCrop,
    rendered: _RenderedPage,
    detection_score: float,
    runtime_metadata: Mapping[str, Any],
    structure_threshold: float = 0.5,
) -> _TatrTableRecord | None:
    table_objects = [obj for obj in objects if obj.get("label") == "table"]
    if not table_objects:
        return None
    table = max(table_objects, key=lambda obj: float(obj.get("score", 0.0)))
    table_box = table["bbox"]
    selected = [obj for obj in objects if _iob(obj["bbox"], table_box) >= 0.5]
    selected_tokens = [
        dict(token) for token in crop.tokens if _iob(token["bbox"], table_box) >= 0.5
    ]
    indexed: list[dict[str, Any]] = []
    for obj in selected:
        label = _STRUCTURE_LABEL_IDS.get(str(obj.get("label")))
        if label is None or label == _STRUCTURE_LABEL_IDS["no object"]:
            continue
        copied = dict(obj)
        copied["bbox"] = [float(v) for v in obj["bbox"]]
        copied["label"] = label
        indexed.append(copied)
    table_record = {
        "bbox": [float(v) for v in table_box],
        "score": float(table.get("score", 0.0)),
        "page_num": 0,
    }
    thresholds = {name: structure_threshold for name in _STRUCTURE_LABEL_IDS}
    try:
        structures = _postprocess.objects_to_table_structures(  # type: ignore[no-untyped-call]
            table_record,
            indexed,
            selected_tokens,
            _STRUCTURE_LABELS,
            thresholds,
        )
        # Microsoft's cell exporter intentionally tightens row/column/cell boxes
        # around assigned text near the end of post-processing. Preserve the
        # refined structural grid first: public geometry and detector matching
        # must describe the table grid, while text/span/header assignment still
        # comes from the canonical exporter below.
        grid_structures = deepcopy(structures)
        if not structures.get("rows") or not structures.get("columns"):
            return None
        cells, token_confidence = _postprocess.table_structure_to_cells(  # type: ignore[no-untyped-call]
            structures,
            selected_tokens,
            table_record["bbox"],
        )
    except (ArithmeticError, IndexError, KeyError, TypeError, ValueError):
        return None
    if not cells:
        return None
    page_cells: list[dict[str, Any]] = []
    grid_rows = list(grid_structures.get("rows", []))
    grid_columns = list(grid_structures.get("columns", []))
    for cell in cells:
        converted = dict(cell)
        converted["row_nums"] = sorted(int(v) for v in cell["row_nums"])
        converted["column_nums"] = sorted(int(v) for v in cell["column_nums"])
        grid_bbox = _grid_cell_bbox(cell, grid_rows, grid_columns)
        converted["bbox"] = _crop_box_to_page(grid_bbox, crop, rendered)
        page_cells.append(converted)
    row_boxes = [
        _crop_box_to_page(row["bbox"], crop, rendered)
        for row in grid_rows
    ]
    column_boxes = [
        _crop_box_to_page(column["bbox"], crop, rendered)
        for column in grid_columns
    ]
    model_confidence = min(
        float(detection_score), float(table.get("score", 0.0))
    )
    if selected_tokens:
        model_confidence = (model_confidence + float(token_confidence)) / 2.0
    table_metadata = dict(runtime_metadata)
    table_metadata["rotated_table"] = crop.rotated
    table_metadata["page_rotation"] = rendered.rotation
    display_axes_rotated = crop.rotated != bool(rendered.rotation % 180)
    result = _TatrTableRecord(
        page_cells,
        row_boxes,
        column_boxes,
        model_confidence,
        rendered.text_source,
        table_metadata,
        rotated=display_axes_rotated,
    )
    return result if result.spans else None


def _intersects_clip(table: _TatrTableRecord, clip: Any) -> bool:
    if clip is None:
        return True
    if len(clip) != 4:
        raise ValueError("clip must be a 4-sequence")
    return _intersection_area(table.bbox, tuple(float(v) for v in clip)) > 0.0


def find_tables(
    page: Any,
    *,
    clip: Any = None,
    options: Mapping[str, object] | None = None,
    _runtime: Any = None,
) -> _TatrTableFinderRecord:
    """Run TATR detection + structure recognition and map native words to cells."""

    config = TatrOptions.from_mapping(options)
    runtime = _runtime if _runtime is not None else _get_runtime(config)
    rendered = _render_page(page, config)
    if _area(rendered.page_bbox) <= 0:
        return _TatrTableFinderRecord([])
    detections = runtime.detect(rendered.image, config.detection_threshold)
    tables: list[_TatrTableRecord] = []
    metadata = getattr(runtime, "metadata", {"backend": "tatr"})
    anchors = (
        _native_line_anchors(page, clip) if config.native_line_guidance else []
    )
    used_anchors: set[int] = set()
    for detection in detections:
        if detection.get("label") not in {"table", "table rotated"}:
            continue
        guided_detection, detection_page_bbox, line_guided = _guided_detection(
            detection, anchors, rendered, used_anchors
        )
        recognition_detection = guided_detection
        expansions = 1 if line_guided else 0
        adaptive_expansions = 0
        limits = _detection_expansion_limits(
            detection, detections, rendered.image.size
        )
        while True:
            crop = _make_crop(
                rendered, recognition_detection, config.crop_padding
            )
            if crop is None:
                break
            objects = runtime.recognize(crop.image, config.structure_threshold)
            crop_edges = _structure_crop_edges(objects, crop.image.size)
            if (
                line_guided
                or not config.adaptive_crop
                or not crop_edges
                or adaptive_expansions >= 2
            ):
                break
            expanded = _expand_detection(
                recognition_detection,
                _unrotate_crop_edges(crop_edges, crop.rotated),
                limits,
            )
            if _box4(expanded["bbox"]) == _box4(recognition_detection["bbox"]):
                break
            recognition_detection = expanded
            adaptive_expansions += 1
            expansions += 1
        if crop is None:
            continue
        table_metadata = dict(metadata)
        crop_edges = _structure_crop_edges(objects, crop.image.size)
        if line_guided:
            geometry_source = "tatr-structure+vector-lines-guidance"
        elif adaptive_expansions:
            geometry_source = "tatr-structure+adaptive-context"
        else:
            geometry_source = "tatr-structure"
        table_metadata.update(
            {
                "detection_bbox": list(detection_page_bbox),
                "recognition_crop_bbox": list(
                    _image_box_to_page(_box4(crop.bbox), rendered)
                ),
                "geometry_source": geometry_source,
                "crop_expansions": expansions,
                "truncated": bool(crop_edges),
            }
        )
        table = _table_from_structure(
            objects,
            crop,
            rendered,
            float(detection.get("score", 0.0)),
            table_metadata,
            config.structure_threshold,
        )
        if table is not None and table.metadata.get("truncated"):
            table.confidence *= 0.8
        if table is not None and _intersects_clip(table, clip):
            tables.append(table)
    tables.sort(key=lambda table: (table.bbox[1], table.bbox[0]))
    return _TatrTableFinderRecord(tables)


__all__ = [
    "DETECTION_MODEL",
    "DETECTION_REVISION",
    "STRUCTURE_MODEL",
    "STRUCTURE_REVISION",
    "TatrOptions",
    "clear_model_cache",
    "find_tables",
]
