"""Type stubs for :mod:`pdfspine.geometry` (PyMuPDF-compatible value types)."""

from typing import Iterator, Sequence, Union

EPSILON: float
FZ_MIN_INF_RECT: int
FZ_MAX_INF_RECT: int

class Point:
    x: float
    y: float
    def __init__(self, *args: float | Sequence[float]) -> None: ...
    def __iter__(self) -> Iterator[float]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __add__(self, p: float | Point | Sequence[float]) -> Point: ...
    def __sub__(self, p: float | Point | Sequence[float]) -> Point: ...
    def __mul__(self, m: float | Point | Matrix | Sequence[float]) -> Point | float: ...
    def __truediv__(self, m: float | Matrix | Sequence[float]) -> Point: ...
    def __abs__(self) -> float: ...
    def __neg__(self) -> Point: ...
    def norm(self) -> float: ...
    def distance_to(self, *args: object) -> float: ...
    def transform(self, m: Matrix | Sequence[float]) -> Point: ...
    @property
    def unit(self) -> Point: ...
    @property
    def abs_unit(self) -> Point: ...

class Rect:
    x0: float
    y0: float
    x1: float
    y1: float
    def __init__(self, *args: float | Point | Sequence[float]) -> None: ...
    def __iter__(self) -> Iterator[float]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    def __abs__(self) -> float: ...
    def norm(self) -> float: ...
    def get_area(self, unit: str = ...) -> float: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def is_infinite(self) -> bool: ...
    @property
    def top_left(self) -> Point: ...
    @property
    def tl(self) -> Point: ...
    @property
    def bottom_right(self) -> Point: ...
    @property
    def br(self) -> Point: ...
    @property
    def top_right(self) -> Point: ...
    @property
    def tr(self) -> Point: ...
    @property
    def bottom_left(self) -> Point: ...
    @property
    def bl(self) -> Point: ...
    @property
    def quad(self) -> Quad: ...
    def round(self) -> IRect: ...
    @property
    def irect(self) -> IRect: ...
    def normalize(self) -> Rect: ...
    def include_point(self, p: Point | Sequence[float]) -> Rect: ...
    def include_rect(self, r: Rect | IRect | Sequence[float]) -> Rect: ...
    def intersect(self, r: Rect | IRect | Sequence[float]) -> Rect: ...
    def transform(self, m: Matrix | Sequence[float]) -> Rect: ...
    def morph(self, p: Point | Sequence[float], m: Matrix | Sequence[float]) -> Quad: ...
    def torect(self, r: Rect | IRect | Sequence[float]) -> Matrix: ...
    def contains(self, x: object) -> bool: ...
    def __contains__(self, x: object) -> bool: ...
    def intersects(self, x: Rect | IRect | Sequence[float]) -> bool: ...
    def __or__(self, x: Point | Rect | IRect | Sequence[float]) -> Rect: ...
    def __and__(self, x: Rect | IRect | Sequence[float]) -> Rect: ...
    def __add__(self, p: float | Rect | IRect | Sequence[float]) -> Rect: ...
    def __sub__(self, p: float | Rect | IRect | Sequence[float]) -> Rect: ...
    def __mul__(self, m: float | Matrix | Sequence[float]) -> Rect: ...
    def __truediv__(self, m: float | Matrix | Sequence[float]) -> Rect: ...

class IRect:
    x0: int
    y0: int
    x1: int
    y1: int
    def __init__(self, *args: int | Point | Sequence[float]) -> None: ...
    def __iter__(self) -> Iterator[int]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    def get_area(self, unit: str = ...) -> float: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def is_infinite(self) -> bool: ...
    @property
    def top_left(self) -> Point: ...
    @property
    def tl(self) -> Point: ...
    @property
    def bottom_right(self) -> Point: ...
    @property
    def br(self) -> Point: ...
    @property
    def top_right(self) -> Point: ...
    @property
    def tr(self) -> Point: ...
    @property
    def bottom_left(self) -> Point: ...
    @property
    def bl(self) -> Point: ...
    @property
    def quad(self) -> Quad: ...
    @property
    def rect(self) -> Rect: ...
    @property
    def irect(self) -> IRect: ...
    def round(self) -> IRect: ...
    def normalize(self) -> IRect: ...
    def include_point(self, p: Point | Sequence[float]) -> IRect: ...
    def include_rect(self, r: Rect | IRect | Sequence[float]) -> IRect: ...
    def intersect(self, r: Rect | IRect | Sequence[float]) -> IRect: ...
    def transform(self, m: Matrix | Sequence[float]) -> IRect: ...
    def morph(self, p: Point | Sequence[float], m: Matrix | Sequence[float]) -> Quad: ...
    def torect(self, r: Rect | IRect | Sequence[float]) -> Matrix: ...
    def contains(self, x: object) -> bool: ...
    def __contains__(self, x: object) -> bool: ...
    def intersects(self, x: Rect | IRect | Sequence[float]) -> bool: ...
    def __or__(self, x: Point | Rect | IRect | Sequence[float]) -> IRect: ...
    def __and__(self, x: Rect | IRect | Sequence[float]) -> IRect: ...
    def __add__(self, p: float | Rect | IRect | Sequence[float]) -> IRect: ...
    def __sub__(self, p: float | Rect | IRect | Sequence[float]) -> IRect: ...
    def __mul__(self, m: float | Matrix | Sequence[float]) -> IRect: ...
    def __truediv__(self, m: float | Matrix | Sequence[float]) -> IRect: ...

class Matrix:
    a: float
    b: float
    c: float
    d: float
    e: float
    f: float
    def __init__(self, *args: float | Matrix | Sequence[float]) -> None: ...
    def __iter__(self) -> Iterator[float]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __mul__(self, m: float | Matrix | Sequence[float]) -> Matrix: ...
    def __truediv__(self, m: float | Matrix | Sequence[float]) -> Matrix: ...
    def __add__(self, m: float | Matrix | Sequence[float]) -> Matrix: ...
    def __sub__(self, m: float | Matrix | Sequence[float]) -> Matrix: ...
    def __neg__(self) -> Matrix: ...
    def __abs__(self) -> float: ...
    def norm(self) -> float: ...
    def __invert__(self) -> Matrix: ...
    def __inv__(self) -> Matrix: ...
    def concat(self, one: Matrix | Sequence[float], two: Matrix | Sequence[float]) -> Matrix: ...
    def invert(self, src: Matrix | Sequence[float] | None = ...) -> int: ...
    def prerotate(self, theta: float) -> Matrix: ...
    def prescale(self, sx: float, sy: float) -> Matrix: ...
    def preshear(self, h: float, v: float) -> Matrix: ...
    def pretranslate(self, tx: float, ty: float) -> Matrix: ...
    @property
    def is_rectilinear(self) -> bool: ...

class IdentityMatrix(Matrix):
    def __init__(self) -> None: ...
    def __hash__(self) -> int: ...
    def __setattr__(self, name: str, value: float) -> None: ...

class Quad:
    ul: Point
    ur: Point
    ll: Point
    lr: Point
    def __init__(self, *args: Point | Quad | Sequence[Point | Sequence[float]]) -> None: ...
    def __iter__(self) -> Iterator[Point]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> Point: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    @property
    def rect(self) -> Rect: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    def __abs__(self) -> float: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def is_infinite(self) -> bool: ...
    @property
    def is_convex(self) -> bool: ...
    @property
    def is_rectangular(self) -> bool: ...
    def transform(self, m: Matrix | Sequence[float]) -> Quad: ...
    def __mul__(self, m: Matrix | Sequence[float]) -> Quad: ...
    def morph(self, p: Point | Sequence[float], m: Matrix | Sequence[float]) -> Quad: ...

Identity: IdentityMatrix

def EMPTY_RECT() -> Rect: ...
def EMPTY_IRECT() -> IRect: ...
def EMPTY_QUAD() -> Quad: ...
def INFINITE_RECT() -> Rect: ...
def INFINITE_IRECT() -> IRect: ...
def INFINITE_QUAD() -> Quad: ...
def paper_sizes() -> dict[str, tuple[int, int]]: ...
def paper_size(s: str) -> tuple[int, int]: ...
def paper_rect(s: str) -> Rect: ...

point_like = Union[Point, Sequence[float]]
rect_like = Union[Rect, IRect, Sequence[float]]
matrix_like = Union[Matrix, Sequence[float]]
quad_like = Union[Quad, Rect, IRect, Sequence]
