"""Type stubs for :mod:`pdfspine.helpers`."""

from typing import Any

from .geometry import Matrix, Quad

Base14_fontdict: dict[str, str]

def planish_line(p1: Any, p2: Any) -> Matrix: ...
def recover_bbox_quad(line_dir: Any, span: dict[str, Any], bbox: Any) -> Quad: ...
def recover_quad(line_dir: Any, span: dict[str, Any]) -> Quad: ...
def recover_char_quad(line_dir: Any, span: dict[str, Any], char: Any) -> Quad: ...
def recover_line_quad(
    line: dict[str, Any], spans: list[dict[str, Any]] | None = ...
) -> Quad: ...
def recover_span_quad(
    line_dir: Any, span: dict[str, Any], chars: list[dict[str, Any]] | None = ...
) -> Quad: ...
def glyph_name_to_unicode(name: str) -> int: ...
def unicode_to_glyph_name(ch: int) -> str: ...
def sRGB_to_rgb(srgb: int) -> tuple[int, int, int]: ...
def sRGB_to_pdf(srgb: int) -> tuple[float, float, float]: ...
def get_pdf_now() -> str: ...
def get_pdf_str(s: str) -> str: ...
def get_text_length(
    text: str, fontname: str = ..., fontsize: float = ..., encoding: int = ...
) -> float: ...
def image_profile(stream: Any, keep_image: int = ...) -> dict[str, Any] | None: ...
def ConversionHeader(output: str = ..., filename: str = ...) -> str: ...
def ConversionTrailer(output: str) -> str: ...
def set_messages(
    *,
    text: str | None = ...,
    fd: int | None = ...,
    stream: Any = ...,
    path: str | None = ...,
    path_append: str | None = ...,
    pylogging: Any = ...,
    pylogging_logger: Any = ...,
    pylogging_level: Any = ...,
    pylogging_name: Any = ...,
) -> None: ...
def message(text: str = ...) -> None: ...
def set_log(
    *,
    text: str | None = ...,
    fd: int | None = ...,
    stream: Any = ...,
    path: str | None = ...,
    path_append: str | None = ...,
    pylogging: Any = ...,
    pylogging_logger: Any = ...,
    pylogging_level: Any = ...,
    pylogging_name: Any = ...,
) -> None: ...
def log(text: str = ..., caller: int = ...) -> None: ...
