//! M2d html/xhtml/xml golden tests (pdfspine-defined valid serializations;
//! Tier-B per PRD §6.1 — our own human-validated goldens, not PyMuPDF bytes).
//! The expected strings below were generated by the serializers and reviewed by
//! a human for well-formedness + correct escaping/structure. Catalog IDs:
//! `HTML-*`, `XHTML-*`, `XML-*`.

use pdf_core::geom::{Point, Rect};
use pdf_text::model::WritingDir;
use pdf_text::serialize::{defaults, to_html, to_xhtml, to_xml};
use pdf_text::{textpage_from_glyphs, PositionedGlyph};
use smol_str::SmolStr;

fn letter() -> Rect {
    Rect::new(0.0, 0.0, 612.0, 792.0)
}

fn glyph(c: &str, ox: f64, oy: f64, size: f64, w: f64, font: &str, color: u32) -> PositionedGlyph {
    PositionedGlyph {
        unicode: SmolStr::new(c),
        code: c.chars().next().map_or(0, |ch| ch as u32),
        origin: Point::new(ox, oy),
        bbox: Rect::new(ox, oy - 0.2 * size, ox + w, oy + 0.7 * size),
        font_name: SmolStr::new(font),
        size,
        color,
        render_mode: 0,
        writing_dir: WritingDir::Horizontal,
        ascender: 0.7,
        descender: -0.2,
    }
}

/// Two lines in one block: bold "Hi", then red "x<y" (exercises escaping).
fn golden_tp() -> pdf_text::TextPage {
    let mut gs = Vec::new();
    let mut x = 100.0;
    for c in "Hi".chars() {
        gs.push(glyph(
            &c.to_string(),
            x,
            700.0,
            12.0,
            7.0,
            "Helvetica-Bold",
            0,
        ));
        x += 7.0;
    }
    x = 100.0;
    for c in "x<y".chars() {
        gs.push(glyph(
            &c.to_string(),
            x,
            688.0,
            12.0,
            7.0,
            "Helvetica",
            0xFF_0000,
        ));
        x += 7.0;
    }
    textpage_from_glyphs(&gs, &[], letter(), 0)
}

const HTML_GOLDEN: &str = "<div id=\"page0\" style=\"width:612pt;height:792pt\">\n\
<p style=\"top:83.6pt;left:100pt;line-height:12pt\"><span style=\"font-family:Helvetica-Bold;font-size:12pt;color:#000000;font-weight:bold\">Hi</span></p>\n\
<p style=\"top:95.6pt;left:100pt;line-height:12pt\"><span style=\"font-family:Helvetica;font-size:12pt;color:#ff0000\">x&lt;y</span></p>\n\
</div>\n";

const XHTML_GOLDEN: &str = "<div id=\"page0\">\n\
<p><span style=\"font-family:Helvetica-Bold;font-size:12pt;color:#000000;font-weight:bold\">Hi</span></p>\n\
<p><span style=\"font-family:Helvetica;font-size:12pt;color:#ff0000\">x&lt;y</span></p>\n\
</div>\n";

const XML_GOLDEN: &str = concat!(
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n",
    "<page id=\"page0\" width=\"612\" height=\"792\">\n",
    "<block bbox=\"100 83.6 121 106.4\" justify=\"unknown\">\n",
    "<line bbox=\"100 83.6 114 94.4\" wmode=\"0\" dir=\"1 0\" flags=\"0\" text=\"Hi\">\n",
    "<font name=\"Helvetica-Bold\" size=\"12\">\n",
    "<char quad=\"100 83.6 107 83.6 100 94.4 107 94.4\" x=\"100\" y=\"92\" bidi=\"0\" color=\"#000000\" alpha=\"#ff\" flags=\"16\" c=\"H\"/>\n",
    "<char quad=\"107 83.6 114 83.6 107 94.4 114 94.4\" x=\"107\" y=\"92\" bidi=\"0\" color=\"#000000\" alpha=\"#ff\" flags=\"16\" c=\"i\"/>\n",
    "</font>\n",
    "</line>\n",
    "<line bbox=\"100 95.6 121 106.4\" wmode=\"0\" dir=\"1 0\" flags=\"0\" text=\"x&lt;y\">\n",
    "<font name=\"Helvetica\" size=\"12\">\n",
    "<char quad=\"100 95.6 107 95.6 100 106.4 107 106.4\" x=\"100\" y=\"104\" bidi=\"0\" color=\"#ff0000\" alpha=\"#ff\" flags=\"0\" c=\"x\"/>\n",
    "<char quad=\"107 95.6 114 95.6 107 106.4 114 106.4\" x=\"107\" y=\"104\" bidi=\"0\" color=\"#ff0000\" alpha=\"#ff\" flags=\"0\" c=\"&lt;\"/>\n",
    "<char quad=\"114 95.6 121 95.6 114 106.4 121 106.4\" x=\"114\" y=\"104\" bidi=\"0\" color=\"#ff0000\" alpha=\"#ff\" flags=\"0\" c=\"y\"/>\n",
    "</font>\n",
    "</line>\n",
    "</block>\n",
    "</page>\n",
);

#[test]
fn html_001_positioned_golden() {
    let tp = golden_tp();
    assert_eq!(to_html(&tp, defaults::HTML), HTML_GOLDEN);
}

#[test]
fn xhtml_001_semantic_golden() {
    let tp = golden_tp();
    assert_eq!(to_xhtml(&tp, defaults::XHTML), XHTML_GOLDEN);
}

#[test]
fn xml_001_charlevel_golden() {
    let tp = golden_tp();
    assert_eq!(to_xml(&tp, defaults::XML), XML_GOLDEN);
}

#[test]
fn xml_002_escapes_special_chars() {
    // A char data with `<`, `>`, `&`, quotes in the char itself and the font
    // name; assert they appear escaped, never raw, in the char-data attribute.
    let tp = golden_tp();
    let xml = to_xml(&tp, defaults::XML);
    assert!(xml.contains("c=\"&lt;\""));
    // No raw `<` inside an attribute value (only as element-tag openers).
    for line in xml.lines() {
        if let Some(idx) = line.find("c=\"") {
            let rest = &line[idx + 3..];
            let val = &rest[..rest.find('"').unwrap()];
            assert!(!val.contains('<'), "raw < in attr value: {line}");
            assert!(
                !val.contains('&')
                    || val.contains("&amp;")
                    || val.starts_with("&lt;")
                    || val.starts_with("&gt;")
                    || val.starts_with("&quot;")
                    || val.starts_with("&apos;")
            );
        }
    }
}
