"""Type stubs for the native ``oxide_pdf._core`` extension module (PyO3).

These describe the raw Rust-backed surface. Most user code uses the
:mod:`oxide_pdf.document` wrappers instead; the ``Pixmap`` and ``DisplayList``
classes below are, however, re-exported unwrapped as the public types.
"""

from typing import Any, Iterator, Sequence, final

__version__: str
__all__ = [
    "__version__",
    "version",
    "identity_matrix",
    "open",
    "open_bytes",
    "Document",
    "Page",
    "TextPage",
    "Annot",
    "Widget",
    "Shape",
    "Pixmap",
    "DisplayList",
    "TableFinder",
    "Table",
    "PdfError",
    "PdfSyntaxError",
    "PdfPasswordError",
    "PdfUnsupportedError",
    "PdfDecodeError",
    "PdfLimitError",
    "PdfRedactionError",
]

def version() -> str: ...
def identity_matrix() -> tuple[float, float, float, float, float, float]: ...
def open(path: str) -> Document: ...
def open_bytes(data: bytes) -> Document: ...

# --- exception hierarchy (PRD §9.3) ---
class PdfError(Exception): ...
class PdfSyntaxError(PdfError): ...
class PdfPasswordError(PdfError): ...
class PdfUnsupportedError(PdfError): ...
class PdfDecodeError(PdfError): ...
class PdfLimitError(PdfError): ...
class PdfRedactionError(PdfError): ...

_Color = tuple[float, float, float]
_Tuple4 = tuple[float, float, float, float]

@final
class Annot:
    @property
    def rect(self) -> _Tuple4: ...
    @property
    def type_string(self) -> str: ...
    @property
    def xref(self) -> int: ...
    @property
    def opacity(self) -> float: ...
    @property
    def flags(self) -> int: ...
    @property
    def border_width(self) -> float: ...
    @property
    def has_appearance(self) -> bool: ...
    def info(self) -> dict[str, str]: ...
    def colors(self) -> dict[str, _Color | None]: ...
    def vertices(self) -> list[tuple[float, float]]: ...
    def set_rect(self, rect: _Tuple4) -> None: ...
    def set_colors(self, stroke: _Color | None = ..., fill: _Color | None = ...) -> None: ...
    def set_opacity(self, opacity: float) -> None: ...
    def set_border(self, width: float = ...) -> None: ...
    def set_flags(self, flags: int) -> None: ...
    def set_info(
        self, content: str | None = ..., title: str | None = ..., name: str | None = ...
    ) -> None: ...
    def update(self) -> None: ...

@final
class Widget:
    @property
    def rect(self) -> _Tuple4: ...
    @property
    def xref(self) -> int: ...
    @property
    def field_type(self) -> int: ...
    @property
    def field_type_string(self) -> str: ...
    @property
    def field_name(self) -> str | None: ...
    @property
    def field_label(self) -> str | None: ...
    @property
    def field_value(self) -> Any: ...
    @property
    def field_flags(self) -> int: ...
    @property
    def choice_values(self) -> list[str]: ...
    @property
    def button_states(self) -> list[str]: ...
    def set_field_value(self, value: Any) -> None: ...
    def update(self, value: Any = ...) -> None: ...

@final
class Shape:
    def draw_line(self, p1: tuple[float, float], p2: tuple[float, float]) -> None: ...
    def draw_rect(self, rect: _Tuple4) -> None: ...
    def draw_circle(self, center: tuple[float, float], radius: float) -> None: ...
    def draw_oval(self, rect: _Tuple4) -> None: ...
    def draw_bezier(
        self,
        p1: tuple[float, float],
        p2: tuple[float, float],
        p3: tuple[float, float],
        p4: tuple[float, float],
    ) -> None: ...
    def draw_polyline(self, points: Sequence[tuple[float, float]]) -> None: ...
    def draw_curve(self, points: Sequence[tuple[float, float]]) -> None: ...
    def finish(
        self,
        color: _Color | None = ...,
        fill: _Color | None = ...,
        width: float = ...,
        dashes: Any = ...,
        even_odd: bool = ...,
        close_path: bool = ...,
    ) -> None: ...
    def commit(self, overlay: bool = ...) -> None: ...

@final
class TextPage:
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    def extractText(self) -> str: ...
    def extractWORDS(self) -> list[tuple[Any, ...]]: ...
    def extractBLOCKS(self) -> list[tuple[Any, ...]]: ...
    def extractDICT(self) -> dict[str, Any]: ...
    def extractRAWDICT(self) -> dict[str, Any]: ...
    def extractJSON(self) -> str: ...

@final
class Table:
    @property
    def bbox(self) -> _Tuple4: ...
    @property
    def row_count(self) -> int: ...
    @property
    def col_count(self) -> int: ...
    @property
    def header(self) -> list[Any]: ...
    @property
    def rows(self) -> list[float]: ...
    @property
    def cols(self) -> list[float]: ...
    @property
    def cells(self) -> list[list[_Tuple4 | None]]: ...
    @property
    def spans(self) -> list[tuple[int, int, int, int, _Tuple4]]: ...
    def extract(self) -> list[list[Any]]: ...
    def to_markdown(self) -> str: ...
    def to_html(self) -> str: ...

@final
class TableFinder:
    @property
    def tables(self) -> list[Table]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int, /) -> Table: ...

@final
class Page:
    @property
    def number(self) -> int: ...
    @property
    def is_image_only(self) -> bool: ...
    @property
    def first_annot(self) -> Annot | None: ...
    @property
    def first_widget(self) -> Widget | None: ...
    def rect(self) -> _Tuple4: ...
    def bound(self) -> _Tuple4: ...
    def mediabox(self) -> _Tuple4: ...
    def cropbox(self) -> _Tuple4: ...
    def rotation(self) -> int: ...
    def get_textpage(self, flags: int | None = ..., clip: _Tuple4 | None = ...) -> TextPage: ...
    def get_textpage_ocr(
        self,
        flags: int = ...,
        language: str = ...,
        dpi: int = ...,
        full: bool = ...,
        tessdata: str | None = ...,
    ) -> TextPage: ...
    def get_text(
        self,
        option: str = ...,
        *,
        clip: _Tuple4 | None = ...,
        flags: int | None = ...,
        textpage: TextPage | None = ...,
        sort: bool = ...,
    ) -> Any: ...
    def search_for(
        self,
        needle: str,
        *,
        hit_max: int = ...,
        quads: bool = ...,
        clip: _Tuple4 | None = ...,
        flags: int | None = ...,
        textpage: TextPage | None = ...,
    ) -> list[tuple[float, ...]]: ...
    def get_fonts(self, full: bool = ...) -> list[tuple[Any, ...]]: ...
    def get_images(self, full: bool = ...) -> list[tuple[Any, ...]]: ...
    def get_pixmap(
        self,
        *,
        matrix: tuple[float, float, float, float, float, float] | None = ...,
        dpi: int | None = ...,
        colorspace: Any = ...,
        alpha: bool = ...,
        clip: _Tuple4 | None = ...,
    ) -> Pixmap: ...
    def get_displaylist(self) -> DisplayList: ...
    def find_tables(
        self,
        *,
        strategy: str = ...,
        line_max_thickness: float = ...,
        snap_tolerance: float = ...,
        min_line_length: float = ...,
    ) -> TableFinder: ...
    def get_svg_image(
        self, *, matrix: tuple[float, float, float, float, float, float] | None = ...
    ) -> str: ...
    def get_links(self) -> list[dict[str, Any]]: ...
    def insert_link(self, link: dict[str, Any]) -> None: ...
    def delete_link(self, xref: int) -> None: ...
    def get_label(self) -> str: ...
    def set_rotation(self, rotation: int) -> None: ...
    def insert_text(
        self,
        point: tuple[float, float],
        text: str,
        *,
        fontname: str = ...,
        fontsize: float = ...,
        color: _Color | None = ...,
        fontfile: str | None = ...,
    ) -> int: ...
    def insert_textbox(
        self,
        rect: _Tuple4,
        text: str,
        *,
        fontname: str = ...,
        fontsize: float = ...,
        color: _Color | None = ...,
        align: int = ...,
        fontfile: str | None = ...,
    ) -> float: ...
    def insert_image(
        self,
        rect: _Tuple4,
        *,
        stream: bytes,
        width: int | None = ...,
        height: int | None = ...,
    ) -> None: ...
    def draw_line(
        self,
        p1: tuple[float, float],
        p2: tuple[float, float],
        *,
        color: _Color | None = ...,
        width: float = ...,
    ) -> None: ...
    def draw_rect(
        self,
        rect: _Tuple4,
        *,
        color: _Color | None = ...,
        fill: _Color | None = ...,
        width: float = ...,
    ) -> None: ...
    def draw_circle(
        self,
        center: tuple[float, float],
        radius: float,
        *,
        color: _Color | None = ...,
        fill: _Color | None = ...,
        width: float = ...,
    ) -> None: ...
    def draw_oval(
        self,
        rect: _Tuple4,
        *,
        color: _Color | None = ...,
        fill: _Color | None = ...,
        width: float = ...,
    ) -> None: ...
    def draw_bezier(
        self,
        p1: tuple[float, float],
        p2: tuple[float, float],
        p3: tuple[float, float],
        p4: tuple[float, float],
        *,
        color: _Color | None = ...,
        width: float = ...,
    ) -> None: ...
    def draw_polyline(
        self,
        points: Sequence[tuple[float, float]],
        *,
        color: _Color | None = ...,
        width: float = ...,
    ) -> None: ...
    def new_shape(self) -> Shape: ...
    def add_text_annot(
        self, point: tuple[float, float], text: str, *, icon: str = ...
    ) -> Annot: ...
    def add_freetext_annot(
        self,
        rect: _Tuple4,
        text: str,
        *,
        fontsize: float = ...,
        text_color: _Color | None = ...,
        fill_color: _Color | None = ...,
        align: int = ...,
    ) -> Annot: ...
    def add_highlight_annot(self, quads: Sequence[tuple[float, ...]]) -> Annot: ...
    def add_underline_annot(self, quads: Sequence[tuple[float, ...]]) -> Annot: ...
    def add_strikeout_annot(self, quads: Sequence[tuple[float, ...]]) -> Annot: ...
    def add_squiggly_annot(self, quads: Sequence[tuple[float, ...]]) -> Annot: ...
    def add_rect_annot(
        self, rect: _Tuple4, *, color: _Color | None = ..., fill: _Color | None = ...
    ) -> Annot: ...
    def add_circle_annot(
        self, rect: _Tuple4, *, color: _Color | None = ..., fill: _Color | None = ...
    ) -> Annot: ...
    def add_line_annot(
        self,
        p1: tuple[float, float],
        p2: tuple[float, float],
        *,
        color: _Color | None = ...,
    ) -> Annot: ...
    def add_polygon_annot(
        self,
        points: Sequence[tuple[float, float]],
        *,
        color: _Color | None = ...,
        fill: _Color | None = ...,
    ) -> Annot: ...
    def add_polyline_annot(
        self, points: Sequence[tuple[float, float]], *, color: _Color | None = ...
    ) -> Annot: ...
    def add_ink_annot(
        self,
        strokes: Sequence[Sequence[tuple[float, float]]],
        *,
        color: _Color | None = ...,
    ) -> Annot: ...
    def add_stamp_annot(self, rect: _Tuple4, *, stamp: str = ...) -> Annot: ...
    def add_file_annot(
        self, point: tuple[float, float], bytes: bytes, filename: str
    ) -> Annot: ...
    def add_redact_annot(
        self, rect: _Tuple4, *, fill: _Color | None = ..., text: str | None = ...
    ) -> Annot: ...
    def annots(self) -> Iterator[Annot]: ...
    def annot_xrefs(self) -> list[int]: ...
    def annot_names(self) -> list[str]: ...
    def delete_annot(self, xref: int) -> None: ...
    def apply_redactions(self, *args: Any, **kwargs: Any) -> int: ...
    def get_drawings(self) -> list[dict[str, Any]]: ...
    def get_cdrawings(self) -> list[dict[str, Any]]: ...
    def widgets(self) -> list[Widget]: ...

@final
class Document:
    @property
    def page_count(self) -> int: ...
    @property
    def is_pdf(self) -> bool: ...
    @property
    def is_repaired(self) -> bool: ...
    @property
    def is_encrypted(self) -> bool: ...
    @property
    def needs_pass(self) -> bool: ...
    @property
    def permissions(self) -> int: ...
    @property
    def is_form_pdf(self) -> bool: ...
    def load_page(self, index: int) -> Page: ...
    def __getitem__(self, index: int, /) -> Page: ...
    def authenticate(self, password: str | bytes) -> bool: ...
    def get_page_text(
        self, pno: int, option: str = ..., *, flags: int | None = ..., sort: bool = ...
    ) -> Any: ...
    def metadata(self) -> dict[str, str]: ...
    def xref_length(self) -> int: ...
    def xref_object(self, num: int) -> str: ...
    def xref_get_key(self, num: int, key: str) -> Any: ...
    def xref_is_stream(self, num: int) -> bool: ...
    def xref_stream(self, num: int) -> bytes: ...
    def extract_image(self, xref: int) -> dict[str, Any]: ...
    def save(
        self,
        path: str,
        *,
        garbage: int = ...,
        deflate: bool = ...,
        incremental: bool = ...,
        encryption: int | None = ...,
        owner_pw: str | None = ...,
        user_pw: str | None = ...,
        permissions: int = ...,
    ) -> None: ...
    def saveIncr(self, path: str) -> None: ...
    def tobytes(
        self,
        *,
        garbage: int = ...,
        deflate: bool = ...,
        incremental: bool = ...,
        encryption: int | None = ...,
        owner_pw: str | None = ...,
        user_pw: str | None = ...,
        permissions: int = ...,
    ) -> bytes: ...
    def pdfocr_tobytes(
        self,
        *,
        compress: bool = ...,
        language: str = ...,
        tessdata: str | None = ...,
        dpi: int = ...,
    ) -> bytes: ...
    def pdfocr_save(
        self,
        filename: str,
        *,
        compress: bool = ...,
        language: str = ...,
        tessdata: str | None = ...,
        dpi: int = ...,
    ) -> None: ...
    def set_metadata(self, meta: dict[str, str]) -> None: ...
    def setMetadata(self, meta: dict[str, str]) -> None: ...
    def get_xml_metadata(self) -> str: ...
    def set_xml_metadata(self, xml: str) -> None: ...
    def get_toc(self, simple: bool = ...) -> list[list[Any]]: ...
    def getToC(self, simple: bool = ...) -> list[list[Any]]: ...
    def set_toc(self, toc: list[list[Any]]) -> None: ...
    def setToC(self, toc: list[list[Any]]) -> None: ...
    def insert_pdf(
        self,
        src: Document,
        from_page: int | None = ...,
        to_page: int | None = ...,
        start_at: int | None = ...,
    ) -> None: ...
    def insertPDF(
        self,
        src: Document,
        from_page: int | None = ...,
        to_page: int | None = ...,
        start_at: int | None = ...,
    ) -> None: ...
    def new_page(self, pno: int = ..., width: float = ..., height: float = ...) -> Page: ...
    def newPage(self, pno: int = ..., width: float = ..., height: float = ...) -> Page: ...
    def delete_page(self, pno: int) -> None: ...
    def select(self, pages: list[int]) -> None: ...
    def get_page_label(self, pno: int) -> str: ...
    def form_field_names(self) -> list[str]: ...
    def form_fill(self, name: str, value: Any) -> None: ...
    def form_flatten(self) -> None: ...
    def embfile_add(
        self,
        name: str,
        data: bytes,
        *,
        filename: str | None = ...,
        ufilename: str | None = ...,
        desc: str | None = ...,
    ) -> None: ...
    def embfile_get(self, name: str) -> bytes: ...
    def embfile_del(self, name: str) -> None: ...
    def embfile_names(self) -> list[str]: ...
    def embfile_count(self) -> int: ...
    def embfile_info(self, name: str) -> dict[str, Any]: ...
    def scrub(
        self,
        *,
        metadata: bool = ...,
        javascript: bool = ...,
        attached_files: bool = ...,
        remove_links: bool = ...,
        xml_metadata: bool = ...,
    ) -> None: ...
    def bake(self, *, annots: bool = ..., widgets: bool = ...) -> None: ...
    def get_ocgs(self) -> dict[int, dict[str, Any]]: ...
    def layer_ui_configs(self) -> list[dict[str, Any]]: ...
    def ocg_state(self, xref: int) -> bool: ...
    def add_ocg(
        self, name: str, *, config: str | None = ..., on: bool = ..., intent: str = ...
    ) -> int: ...
    def set_layer(self, *, on: list[int] = ..., off: list[int] = ...) -> None: ...
    def set_oc(self, xref: int, ocg: int) -> None: ...

@final
class Pixmap:
    def __new__(
        cls,
        colorspace: int | str,
        irect: tuple[int, int, int, int] | Sequence[int],
        alpha: bool = ...,
    ) -> Pixmap: ...
    @property
    def width(self) -> int: ...
    @property
    def w(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def h(self) -> int: ...
    @property
    def n(self) -> int: ...
    @property
    def alpha(self) -> bool: ...
    @property
    def stride(self) -> int: ...
    @property
    def irect(self) -> tuple[int, int, int, int]: ...
    @property
    def colorspace(self) -> str: ...
    @property
    def samples(self) -> bytes: ...
    @property
    def size(self) -> int: ...
    @property
    def samples_mv(self) -> memoryview: ...
    def pixel(self, x: int, y: int) -> tuple[int, ...]: ...
    def set_pixel(self, x: int, y: int, value: Sequence[int]) -> None: ...
    def set_alpha(self, value: int) -> None: ...
    def clear_with(self, value: int = ...) -> None: ...
    def invert_irect(self, irect: tuple[int, int, int, int] | None = ...) -> None: ...
    def tobytes(self, output: str = ...) -> bytes: ...
    def save(self, filename: str, output: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    # The native ``bf_getbuffer`` slot (PRD §9.4 zero-copy buffer protocol) is
    # implemented in Rust, so ``memoryview(pix)`` / ``numpy.frombuffer(pix)``
    # work. Declared here for PEP 688 buffer awareness; it has no Python-level
    # callable at runtime (stubtest reports this single known, intentional miss).
    def __buffer__(self, flags: int, /) -> memoryview: ...

@final
class DisplayList:
    @property
    def rect(self) -> _Tuple4: ...
    def __len__(self) -> int: ...
    def get_pixmap(
        self,
        *,
        matrix: tuple[float, float, float, float, float, float] | None = ...,
        dpi: float | None = ...,
        colorspace: Any = ...,
        alpha: bool = ...,
        clip: _Tuple4 | None = ...,
    ) -> Pixmap: ...
