"""Type stubs for the native ``oxide_pdf._core`` extension module (PyO3).

These describe the raw Rust-backed surface. Most user code uses the
:mod:`oxide_pdf.document` wrappers instead; the ``Pixmap`` and ``DisplayList``
classes below are, however, re-exported unwrapped as the public types.
"""

from typing import Any, Iterator, Sequence, final

__version__: str
__all__ = [
    "__version__",
    "version",
    "identity_matrix",
    "open",
    "open_bytes",
    "Document",
    "Page",
    "TextPage",
    "Annot",
    "Widget",
    "Shape",
    "Pixmap",
    "DisplayList",
    "TableFinder",
    "Table",
    "Font",
    "Base14_fontnames",
    "PdfError",
    "PdfSyntaxError",
    "PdfPasswordError",
    "PdfUnsupportedError",
    "PdfDecodeError",
    "PdfLimitError",
    "PdfRedactionError",
]

def version() -> str: ...
def identity_matrix() -> tuple[float, float, float, float, float, float]: ...
def open(path: str) -> Document: ...
def open_bytes(data: bytes) -> Document: ...

# --- exception hierarchy (PRD §9.3) ---
class PdfError(Exception): ...
class PdfSyntaxError(PdfError): ...
class PdfPasswordError(PdfError): ...
class PdfUnsupportedError(PdfError): ...
class PdfDecodeError(PdfError): ...
class PdfLimitError(PdfError): ...
class PdfRedactionError(PdfError): ...

_Color = tuple[float, float, float]
_Tuple4 = tuple[float, float, float, float]

@final
class Annot:
    @property
    def rect(self) -> _Tuple4: ...
    @property
    def type_string(self) -> str: ...
    @property
    def xref(self) -> int: ...
    @property
    def opacity(self) -> float: ...
    @property
    def flags(self) -> int: ...
    @property
    def border_width(self) -> float: ...
    @property
    def has_appearance(self) -> bool: ...
    def info(self) -> dict[str, str]: ...
    def colors(self) -> dict[str, _Color | None]: ...
    def vertices(self) -> list[tuple[float, float]]: ...
    def set_rect(self, rect: _Tuple4) -> None: ...
    def set_colors(self, stroke: _Color | None = ..., fill: _Color | None = ...) -> None: ...
    def set_opacity(self, opacity: float) -> None: ...
    def set_border(self, width: float = ...) -> None: ...
    def set_flags(self, flags: int) -> None: ...
    def set_info(
        self, content: str | None = ..., title: str | None = ..., name: str | None = ...
    ) -> None: ...
    def update(self) -> None: ...
    @property
    def blendmode(self) -> str | None: ...
    @property
    def is_open(self) -> bool: ...
    def line_ends(self) -> tuple[int, int]: ...
    def set_line_ends(self, start: int, end: int) -> None: ...
    def set_blendmode(self, mode: str) -> None: ...
    def set_name(self, name: str) -> None: ...
    def set_open(self, open: bool) -> None: ...
    def border_tuple(self) -> tuple[float, str, list[float]]: ...
    def set_rotation(self, rotate: int = ...) -> None: ...
    def rect_delta(self) -> tuple[float, float, float, float] | None: ...
    @property
    def has_popup(self) -> bool: ...
    @property
    def popup_xref(self) -> int: ...
    @property
    def popup_rect(self) -> _Tuple4 | None: ...
    def set_popup(self, rect: _Tuple4) -> None: ...
    def apn_bbox(self) -> _Tuple4 | None: ...
    def apn_matrix(self) -> tuple[float, float, float, float, float, float]: ...
    def set_apn_bbox(self, rect: _Tuple4) -> None: ...
    def set_apn_matrix(
        self, m: tuple[float, float, float, float, float, float]
    ) -> None: ...
    @property
    def language(self) -> str: ...
    def set_language(self, language: str) -> None: ...
    @property
    def irt_xref(self) -> int: ...
    def set_irt_xref(self, xref: int) -> None: ...
    def delete_responses(self) -> None: ...
    def clean_contents(self, sanitize: int = ...) -> None: ...
    def get_file(self) -> bytes: ...
    def file_info(self) -> dict[str, Any]: ...
    def update_file(
        self,
        buffer_: bytes | None = ...,
        filename: str | None = ...,
        ufilename: str | None = ...,
        desc: str | None = ...,
    ) -> None: ...

@final
class Widget:
    @property
    def rect(self) -> _Tuple4: ...
    @property
    def xref(self) -> int: ...
    @property
    def field_type(self) -> int: ...
    @property
    def field_type_string(self) -> str: ...
    @property
    def field_name(self) -> str | None: ...
    @property
    def field_label(self) -> str | None: ...
    @property
    def field_value(self) -> Any: ...
    @property
    def field_flags(self) -> int: ...
    @property
    def choice_values(self) -> list[str]: ...
    @property
    def button_states(self) -> list[str]: ...
    @property
    def border_color(self) -> list[float] | None: ...
    @property
    def fill_color(self) -> list[float] | None: ...
    @property
    def border_style(self) -> str: ...
    @property
    def border_width(self) -> float: ...
    @property
    def border_dashes(self) -> list[int] | None: ...
    @property
    def text_color(self) -> list[float]: ...
    @property
    def text_font(self) -> str: ...
    @property
    def text_fontsize(self) -> float: ...
    @property
    def text_maxlen(self) -> int: ...
    @property
    def text_format(self) -> int: ...
    @property
    def button_caption(self) -> str | None: ...
    @property
    def field_display(self) -> int: ...
    @property
    def is_signed(self) -> bool | None: ...
    @property
    def rb_parent(self) -> int | None: ...
    def on_state(self) -> str | None: ...
    def reset(self) -> None: ...
    def set_field_value(self, value: Any) -> None: ...
    def update(self, value: Any = ...) -> None: ...

@final
class Shape:
    def draw_line(self, p1: tuple[float, float], p2: tuple[float, float]) -> None: ...
    def draw_rect(self, rect: _Tuple4) -> None: ...
    def draw_circle(self, center: tuple[float, float], radius: float) -> None: ...
    def draw_oval(self, rect: _Tuple4) -> None: ...
    def draw_bezier(
        self,
        p1: tuple[float, float],
        p2: tuple[float, float],
        p3: tuple[float, float],
        p4: tuple[float, float],
    ) -> None: ...
    def draw_polyline(self, points: Sequence[tuple[float, float]]) -> None: ...
    def draw_curve(self, points: Sequence[tuple[float, float]]) -> None: ...
    def draw_close(self) -> None: ...
    def finish(
        self,
        color: _Color | None = ...,
        fill: _Color | None = ...,
        width: float = ...,
        dashes: Any = ...,
        even_odd: bool = ...,
        close_path: bool = ...,
    ) -> None: ...
    def commit(self, overlay: bool = ...) -> None: ...

@final
class TextPage:
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    def extractText(self) -> str: ...
    def extractWORDS(self) -> list[tuple[Any, ...]]: ...
    def extractBLOCKS(self) -> list[tuple[Any, ...]]: ...
    def extractDICT(self) -> dict[str, Any]: ...
    def extractRAWDICT(self) -> dict[str, Any]: ...
    def extractJSON(self) -> str: ...
    def extractRAWJSON(self) -> str: ...
    def extractHTML(self) -> str: ...
    def extractXHTML(self) -> str: ...
    def extractXML(self) -> str: ...
    def extractTextbox(self, rect: tuple[float, float, float, float]) -> str: ...
    def extractSelection(
        self, a: tuple[float, float], b: tuple[float, float]
    ) -> str: ...
    def search(
        self, needle: str, quads: bool = ...
    ) -> list[tuple[float, ...]]: ...
    def extractIMGINFO(self) -> list[dict[str, Any]]: ...
    def poolsize(self) -> int: ...

@final
class Outline:
    @property
    def title(self) -> str: ...
    @property
    def page(self) -> int: ...
    @property
    def uri(self) -> str | None: ...
    @property
    def is_external(self) -> bool: ...
    @property
    def is_open(self) -> bool: ...
    @property
    def next(self) -> Outline | None: ...
    @property
    def down(self) -> Outline | None: ...

@final
class Link:
    @property
    def rect(self) -> _Tuple4: ...
    @property
    def kind(self) -> int: ...
    @property
    def uri(self) -> str: ...
    @property
    def page(self) -> int: ...
    @property
    def dest(self) -> str: ...
    @property
    def is_external(self) -> bool: ...
    @property
    def border(self) -> tuple[float, float, float]: ...
    @property
    def color(self) -> tuple[float, float, float] | None: ...
    @property
    def flags(self) -> int: ...
    @property
    def xref(self) -> int: ...
    @property
    def next(self) -> Link | None: ...

@final
class Table:
    @property
    def bbox(self) -> _Tuple4: ...
    @property
    def row_count(self) -> int: ...
    @property
    def col_count(self) -> int: ...
    @property
    def header(self) -> list[Any]: ...
    @property
    def rows(self) -> list[float]: ...
    @property
    def cols(self) -> list[float]: ...
    @property
    def cells(self) -> list[list[_Tuple4 | None]]: ...
    @property
    def spans(self) -> list[tuple[int, int, int, int, _Tuple4]]: ...
    def extract(self) -> list[list[Any]]: ...
    def to_markdown(self) -> str: ...
    def to_html(self) -> str: ...

@final
class TableFinder:
    @property
    def tables(self) -> list[Table]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int, /) -> Table: ...

Base14_fontnames: tuple[str, ...]

@final
class Font:
    def __init__(
        self,
        fontname: str | None = ...,
        fontfile: str | None = ...,
        fontbuffer: bytes | None = ...,
        *args: Any,
        **kwargs: Any,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def ascender(self) -> float: ...
    @property
    def descender(self) -> float: ...
    @property
    def bbox(self) -> _Tuple4: ...
    @property
    def glyph_count(self) -> int: ...
    @property
    def flags(self) -> dict[str, int]: ...
    @property
    def is_bold(self) -> int: ...
    @property
    def is_italic(self) -> int: ...
    @property
    def is_serif(self) -> int: ...
    @property
    def is_monospaced(self) -> int: ...
    @property
    def is_writable(self) -> bool: ...
    @property
    def buffer(self) -> bytes: ...
    def glyph_advance(self, chr: int, *args: Any, **kwargs: Any) -> float: ...
    def has_glyph(self, chr: int, *args: Any, **kwargs: Any) -> int: ...
    def text_length(self, text: str, fontsize: float = ..., *args: Any, **kwargs: Any) -> float: ...
    def char_lengths(
        self, text: str, fontsize: float = ..., *args: Any, **kwargs: Any
    ) -> list[float]: ...
    def glyph_name_to_unicode(self, name: str) -> int: ...
    def unicode_to_glyph_name(self, ch: int) -> str: ...
    def valid_codepoints(self, *args: Any, **kwargs: Any) -> list[int]: ...
    def glyph_bbox(self, chr: int, *args: Any, **kwargs: Any) -> _Tuple4: ...
    def __repr__(self) -> str: ...

@final
class Page:
    @property
    def number(self) -> int: ...
    @property
    def is_image_only(self) -> bool: ...
    @property
    def first_annot(self) -> Annot | None: ...
    @property
    def first_widget(self) -> Widget | None: ...
    @property
    def first_link(self) -> Link | None: ...
    def link_objects(self) -> list[Link]: ...
    def rect(self) -> _Tuple4: ...
    def bound(self) -> _Tuple4: ...
    def mediabox(self) -> _Tuple4: ...
    def cropbox(self) -> _Tuple4: ...
    def rotation(self) -> int: ...
    def artbox(self) -> _Tuple4: ...
    def bleedbox(self) -> _Tuple4: ...
    def trimbox(self) -> _Tuple4: ...
    def transformation_matrix(self) -> tuple[float, float, float, float, float, float]: ...
    def rotation_matrix(self) -> tuple[float, float, float, float, float, float]: ...
    def derotation_matrix(self) -> tuple[float, float, float, float, float, float]: ...
    @property
    def xref(self) -> int: ...
    def get_textpage(self, flags: int | None = ..., clip: _Tuple4 | None = ...) -> TextPage: ...
    def get_textpage_ocr(
        self,
        flags: int = ...,
        language: str = ...,
        dpi: int = ...,
        full: bool = ...,
        tessdata: str | None = ...,
    ) -> TextPage: ...
    def get_text(
        self,
        option: str = ...,
        *,
        clip: _Tuple4 | None = ...,
        flags: int | None = ...,
        textpage: TextPage | None = ...,
        sort: bool = ...,
    ) -> Any: ...
    def search_for(
        self,
        needle: str,
        *,
        hit_max: int = ...,
        quads: bool = ...,
        clip: _Tuple4 | None = ...,
        flags: int | None = ...,
        textpage: TextPage | None = ...,
    ) -> list[tuple[float, ...]]: ...
    def get_fonts(self, full: bool = ...) -> list[tuple[Any, ...]]: ...
    def get_images(self, full: bool = ...) -> list[tuple[Any, ...]]: ...
    def get_pixmap(
        self,
        *,
        matrix: tuple[float, float, float, float, float, float] | None = ...,
        dpi: int | None = ...,
        colorspace: Any = ...,
        alpha: bool = ...,
        clip: _Tuple4 | None = ...,
    ) -> Pixmap: ...
    def get_displaylist(self) -> DisplayList: ...
    def find_tables(
        self,
        *,
        strategy: str = ...,
        line_max_thickness: float = ...,
        snap_tolerance: float = ...,
        min_line_length: float = ...,
    ) -> TableFinder: ...
    def get_svg_image(
        self, *, matrix: tuple[float, float, float, float, float, float] | None = ...
    ) -> str: ...
    def get_links(self) -> list[dict[str, Any]]: ...
    def insert_link(self, link: dict[str, Any]) -> None: ...
    def delete_link(self, xref: int) -> None: ...
    def get_label(self) -> str: ...
    def set_rotation(self, rotation: int) -> None: ...
    def set_mediabox(self, rect: _Tuple4) -> None: ...
    def set_cropbox(self, rect: _Tuple4) -> None: ...
    def set_artbox(self, rect: _Tuple4) -> None: ...
    def set_bleedbox(self, rect: _Tuple4) -> None: ...
    def set_trimbox(self, rect: _Tuple4) -> None: ...
    def insert_text(
        self,
        point: tuple[float, float],
        text: str,
        *,
        fontname: str = ...,
        fontsize: float = ...,
        color: _Color | None = ...,
        fontfile: str | None = ...,
    ) -> int: ...
    def insert_textbox(
        self,
        rect: _Tuple4,
        text: str,
        *,
        fontname: str = ...,
        fontsize: float = ...,
        color: _Color | None = ...,
        align: int = ...,
        fontfile: str | None = ...,
    ) -> float: ...
    def insert_image(
        self,
        rect: _Tuple4,
        *,
        stream: bytes,
        width: int | None = ...,
        height: int | None = ...,
    ) -> None: ...
    def draw_line(
        self,
        p1: tuple[float, float],
        p2: tuple[float, float],
        *,
        color: _Color | None = ...,
        width: float = ...,
    ) -> None: ...
    def draw_rect(
        self,
        rect: _Tuple4,
        *,
        color: _Color | None = ...,
        fill: _Color | None = ...,
        width: float = ...,
    ) -> None: ...
    def draw_circle(
        self,
        center: tuple[float, float],
        radius: float,
        *,
        color: _Color | None = ...,
        fill: _Color | None = ...,
        width: float = ...,
    ) -> None: ...
    def draw_oval(
        self,
        rect: _Tuple4,
        *,
        color: _Color | None = ...,
        fill: _Color | None = ...,
        width: float = ...,
    ) -> None: ...
    def draw_bezier(
        self,
        p1: tuple[float, float],
        p2: tuple[float, float],
        p3: tuple[float, float],
        p4: tuple[float, float],
        *,
        color: _Color | None = ...,
        width: float = ...,
    ) -> None: ...
    def draw_polyline(
        self,
        points: Sequence[tuple[float, float]],
        *,
        color: _Color | None = ...,
        width: float = ...,
    ) -> None: ...
    def new_shape(self) -> Shape: ...
    def add_text_annot(
        self, point: tuple[float, float], text: str, *, icon: str = ...
    ) -> Annot: ...
    def add_freetext_annot(
        self,
        rect: _Tuple4,
        text: str,
        *,
        fontsize: float = ...,
        text_color: _Color | None = ...,
        fill_color: _Color | None = ...,
        align: int = ...,
    ) -> Annot: ...
    def add_highlight_annot(self, quads: Sequence[tuple[float, ...]]) -> Annot: ...
    def add_underline_annot(self, quads: Sequence[tuple[float, ...]]) -> Annot: ...
    def add_strikeout_annot(self, quads: Sequence[tuple[float, ...]]) -> Annot: ...
    def add_squiggly_annot(self, quads: Sequence[tuple[float, ...]]) -> Annot: ...
    def add_rect_annot(
        self, rect: _Tuple4, *, color: _Color | None = ..., fill: _Color | None = ...
    ) -> Annot: ...
    def add_circle_annot(
        self, rect: _Tuple4, *, color: _Color | None = ..., fill: _Color | None = ...
    ) -> Annot: ...
    def add_line_annot(
        self,
        p1: tuple[float, float],
        p2: tuple[float, float],
        *,
        color: _Color | None = ...,
    ) -> Annot: ...
    def add_polygon_annot(
        self,
        points: Sequence[tuple[float, float]],
        *,
        color: _Color | None = ...,
        fill: _Color | None = ...,
    ) -> Annot: ...
    def add_polyline_annot(
        self, points: Sequence[tuple[float, float]], *, color: _Color | None = ...
    ) -> Annot: ...
    def add_ink_annot(
        self,
        strokes: Sequence[Sequence[tuple[float, float]]],
        *,
        color: _Color | None = ...,
    ) -> Annot: ...
    def add_stamp_annot(self, rect: _Tuple4, *, stamp: str = ...) -> Annot: ...
    def add_file_annot(
        self,
        point: tuple[float, float],
        bytes: bytes,
        filename: str,
        desc: str | None = ...,
    ) -> Annot: ...
    def add_redact_annot(
        self, rect: _Tuple4, *, fill: _Color | None = ..., text: str | None = ...
    ) -> Annot: ...
    def annots(self) -> Iterator[Annot]: ...
    def annot_xrefs(self) -> list[int]: ...
    def annot_names(self) -> list[str]: ...
    def delete_annot(self, xref: int) -> None: ...
    def apply_redactions(self, *args: Any, **kwargs: Any) -> int: ...
    def get_drawings(self) -> list[dict[str, Any]]: ...
    def get_cdrawings(self) -> list[dict[str, Any]]: ...
    def widgets(self) -> list[Widget]: ...

@final
class Document:
    @property
    def page_count(self) -> int: ...
    @property
    def is_pdf(self) -> bool: ...
    @property
    def is_repaired(self) -> bool: ...
    @property
    def is_encrypted(self) -> bool: ...
    @property
    def needs_pass(self) -> bool: ...
    @property
    def permissions(self) -> int: ...
    @property
    def is_form_pdf(self) -> bool: ...
    def load_page(self, index: int) -> Page: ...
    def __getitem__(self, index: int, /) -> Page: ...
    def authenticate(self, password: str | bytes) -> bool: ...
    def get_page_text(
        self, pno: int, option: str = ..., *, flags: int | None = ..., sort: bool = ...
    ) -> Any: ...
    def metadata(self) -> dict[str, str]: ...
    def xref_length(self) -> int: ...
    def xref_object(self, num: int) -> str: ...
    def xref_get_key(self, num: int, key: str) -> Any: ...
    def xref_is_stream(self, num: int) -> bool: ...
    def xref_stream(self, num: int) -> bytes: ...
    def xref_stream_raw(self, num: int) -> bytes: ...
    def is_stream(self, num: int) -> bool: ...
    def xref_get_keys(self, num: int) -> list[str]: ...
    def xref_is_xobject(self, num: int) -> bool: ...
    def pdf_catalog(self) -> int: ...
    def pdf_trailer(self, compressed: bool = ..., ascii: bool = ...) -> str: ...
    def get_new_xref(self) -> int: ...
    def update_object(self, xref: int, text: str, page: Any = ...) -> None: ...
    def update_stream(
        self, xref: int, stream: Any, new: bool = ..., compress: bool = ...
    ) -> None: ...
    def resolve_names(self) -> dict[str, dict[str, Any]]: ...
    def page_annot_xrefs(self, pno: int) -> list[tuple[int, str, str]]: ...
    def pagelayout(self) -> str: ...
    def set_pagelayout(self, layout: str) -> None: ...
    def pagemode(self) -> str: ...
    def set_pagemode(self, mode: str) -> None: ...
    def language(self) -> str | None: ...
    def set_language(self, lang: str) -> None: ...
    def markinfo(self) -> tuple[bool, bool, bool] | None: ...
    def set_markinfo(
        self, marked: bool, user_properties: bool, suspects: bool
    ) -> None: ...
    def xref_xml_metadata(self) -> int: ...
    def is_dirty(self) -> bool: ...
    def is_fast_webaccess(self) -> bool: ...
    def can_save_incrementally(self) -> bool: ...
    def has_acroform(self) -> bool: ...
    def need_appearances(self) -> bool: ...
    def set_need_appearances(self, value: bool) -> None: ...
    def get_sigflags(self) -> int: ...
    def extract_image(self, xref: int) -> dict[str, Any]: ...
    def save(
        self,
        path: str,
        *,
        garbage: int = ...,
        deflate: bool = ...,
        incremental: bool = ...,
        encryption: int | None = ...,
        owner_pw: str | None = ...,
        user_pw: str | None = ...,
        permissions: int = ...,
    ) -> None: ...
    def saveIncr(self, path: str) -> None: ...
    def tobytes(
        self,
        *,
        garbage: int = ...,
        deflate: bool = ...,
        incremental: bool = ...,
        encryption: int | None = ...,
        owner_pw: str | None = ...,
        user_pw: str | None = ...,
        permissions: int = ...,
    ) -> bytes: ...
    def pdfocr_tobytes(
        self,
        *,
        compress: bool = ...,
        language: str = ...,
        tessdata: str | None = ...,
        dpi: int = ...,
    ) -> bytes: ...
    def pdfocr_save(
        self,
        filename: str,
        *,
        compress: bool = ...,
        language: str = ...,
        tessdata: str | None = ...,
        dpi: int = ...,
    ) -> None: ...
    def set_metadata(self, meta: dict[str, str]) -> None: ...
    def setMetadata(self, meta: dict[str, str]) -> None: ...
    def get_xml_metadata(self) -> str: ...
    def set_xml_metadata(self, xml: str) -> None: ...
    def get_toc(self, simple: bool = ...) -> list[list[Any]]: ...
    def getToC(self, simple: bool = ...) -> list[list[Any]]: ...
    @property
    def outline(self) -> Outline | None: ...
    def set_toc(self, toc: list[list[Any]]) -> None: ...
    def setToC(self, toc: list[list[Any]]) -> None: ...
    def insert_pdf(
        self,
        src: Document,
        from_page: int | None = ...,
        to_page: int | None = ...,
        start_at: int | None = ...,
    ) -> None: ...
    def insertPDF(
        self,
        src: Document,
        from_page: int | None = ...,
        to_page: int | None = ...,
        start_at: int | None = ...,
    ) -> None: ...
    def new_page(self, pno: int = ..., width: float = ..., height: float = ...) -> Page: ...
    def newPage(self, pno: int = ..., width: float = ..., height: float = ...) -> Page: ...
    def delete_page(self, pno: int) -> None: ...
    def select(self, pages: list[int]) -> None: ...
    def copy_page(self, from_: int, to: int) -> None: ...
    def move_page(self, from_: int, to: int) -> None: ...
    def get_page_label(self, pno: int) -> str: ...
    def get_page_labels(self) -> list[tuple[int, str, str, int]]: ...
    def form_field_names(self) -> list[str]: ...
    def form_fill(self, name: str, value: Any) -> None: ...
    def form_flatten(self) -> None: ...
    def embfile_add(
        self,
        name: str,
        data: bytes,
        *,
        filename: str | None = ...,
        ufilename: str | None = ...,
        desc: str | None = ...,
    ) -> None: ...
    def embfile_get(self, name: str) -> bytes: ...
    def embfile_del(self, name: str) -> None: ...
    def embfile_names(self) -> list[str]: ...
    def embfile_count(self) -> int: ...
    def embfile_info(self, name: str) -> dict[str, Any]: ...
    def scrub(
        self,
        *,
        metadata: bool = ...,
        javascript: bool = ...,
        attached_files: bool = ...,
        remove_links: bool = ...,
        xml_metadata: bool = ...,
    ) -> None: ...
    def bake(self, *, annots: bool = ..., widgets: bool = ...) -> None: ...
    def get_ocgs(self) -> dict[int, dict[str, Any]]: ...
    def layer_ui_configs(self) -> list[dict[str, Any]]: ...
    def ocg_state(self, xref: int) -> bool: ...
    def add_ocg(
        self, name: str, *, config: str | None = ..., on: bool = ..., intent: str = ...
    ) -> int: ...
    def set_layer(self, *, on: list[int] = ..., off: list[int] = ...) -> None: ...
    def set_oc(self, xref: int, ocg: int) -> None: ...

@final
class Pixmap:
    def __new__(
        cls,
        colorspace: int | str,
        irect: tuple[int, int, int, int] | Sequence[int],
        alpha: bool = ...,
    ) -> Pixmap: ...
    @property
    def width(self) -> int: ...
    @property
    def w(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def h(self) -> int: ...
    @property
    def n(self) -> int: ...
    @property
    def alpha(self) -> bool: ...
    @property
    def stride(self) -> int: ...
    @property
    def irect(self) -> tuple[int, int, int, int]: ...
    @property
    def colorspace(self) -> str: ...
    @property
    def samples(self) -> bytes: ...
    @property
    def size(self) -> int: ...
    @property
    def samples_mv(self) -> memoryview: ...
    def pixel(self, x: int, y: int) -> tuple[int, ...]: ...
    def set_pixel(self, x: int, y: int, value: Sequence[int]) -> None: ...
    def set_alpha(self, value: int) -> None: ...
    def clear_with(self, value: int = ...) -> None: ...
    def invert_irect(self, irect: tuple[int, int, int, int] | None = ...) -> None: ...
    def copy(self) -> Pixmap: ...
    def set_rect(
        self, irect: tuple[int, int, int, int], color: Sequence[int]
    ) -> bool: ...
    def shrink(self, factor: int) -> None: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    def set_origin(self, x: int, y: int) -> None: ...
    @property
    def xres(self) -> int: ...
    @property
    def yres(self) -> int: ...
    def set_dpi(self, xres: int, yres: int) -> None: ...
    def tint_with(self, black: int = ..., white: int = ...) -> None: ...
    def gamma_with(self, gamma: float) -> None: ...
    def color_count(self) -> int: ...
    def color_topusage(self) -> tuple[float, bytes]: ...
    @property
    def is_monochrome(self) -> bool: ...
    @property
    def is_unicolor(self) -> bool: ...
    def digest(self) -> bytes: ...
    def tobytes(self, output: str = ...) -> bytes: ...
    def pil_tobytes(self, format: str = ..., **kwargs: Any) -> bytes: ...
    def pil_save(self, filename: str, format: str | None = ..., **kwargs: Any) -> None: ...
    def save(self, filename: str, output: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    # The native ``bf_getbuffer`` slot (PRD §9.4 zero-copy buffer protocol) is
    # implemented in Rust, so ``memoryview(pix)`` / ``numpy.frombuffer(pix)``
    # work. Declared here for PEP 688 buffer awareness; it has no Python-level
    # callable at runtime (stubtest reports this single known, intentional miss).
    def __buffer__(self, flags: int, /) -> memoryview: ...

@final
class DisplayList:
    @property
    def rect(self) -> _Tuple4: ...
    def __len__(self) -> int: ...
    def get_pixmap(
        self,
        *,
        matrix: tuple[float, float, float, float, float, float] | None = ...,
        dpi: float | None = ...,
        colorspace: Any = ...,
        alpha: bool = ...,
        clip: _Tuple4 | None = ...,
    ) -> Pixmap: ...
