"""Type stubs for :mod:`oxide_pdf.cli`."""

import argparse
from typing import Sequence

class CLIError(Exception): ...

def parse_page_range(spec: str | None, page_count: int) -> list[int]: ...
def build_parser() -> argparse.ArgumentParser: ...
def main(argv: Sequence[str] | None = ...) -> int: ...
