"""Type stubs for :mod:`oxide_pdf.document` (PyMuPDF-compatible wrappers)."""

import os
from typing import Any, Iterator, Sequence

from . import _core
from .geometry import IRect, Matrix, Point, Quad, Rect

# Re-exported native types (used unwrapped).
Pixmap = _core.Pixmap
DisplayList = _core.DisplayList

PDF_ENCRYPT_NONE: int
PDF_ENCRYPT_RC4_128: int
PDF_ENCRYPT_AES_128: int
PDF_ENCRYPT_AES_256: int
PDF_PERM_ACCESSIBILITY: int

_Point = Point | Sequence[float]
_Rect = Rect | IRect | Sequence[float]
_Matrix = Matrix | Sequence[float]
_Quad = Quad | Rect | Sequence[float]
_Color = float | Sequence[float] | None

class Annot:
    def __init__(self, core_annot: _core.Annot) -> None: ...
    @property
    def rect(self) -> Rect: ...
    @property
    def type(self) -> tuple[int, str]: ...
    @property
    def xref(self) -> int: ...
    @property
    def info(self) -> dict[str, str]: ...
    @property
    def colors(self) -> dict[str, tuple[float, float, float] | None]: ...
    @property
    def opacity(self) -> float: ...
    @property
    def flags(self) -> int: ...
    @property
    def border(self) -> dict[str, Any]: ...
    @property
    def line_ends(self) -> tuple[int, int]: ...
    @property
    def blendmode(self) -> str | None: ...
    @property
    def is_open(self) -> bool: ...
    @property
    def vertices(self) -> list[Point]: ...
    @property
    def has_appearance(self) -> bool: ...
    def has_ap(self) -> bool: ...
    def set_rect(self, rect: _Rect) -> None: ...
    def set_colors(
        self,
        colors: dict[str, Any] | None = ...,
        *,
        stroke: _Color = ...,
        fill: _Color = ...,
        **_ignored: Any,
    ) -> None: ...
    def set_opacity(self, opacity: float) -> None: ...
    def set_border(
        self, border: dict[str, Any] | None = ..., *, width: float | None = ..., **_ignored: Any
    ) -> None: ...
    def set_line_ends(self, start: int, end: int) -> None: ...
    def set_blendmode(self, blend_mode: str) -> None: ...
    def set_name(self, name: str) -> None: ...
    def set_open(self, is_open: bool) -> None: ...
    def set_flags(self, flags: int) -> None: ...
    def set_info(
        self,
        info: dict[str, Any] | None = ...,
        *,
        content: str | None = ...,
        title: str | None = ...,
        name: str | None = ...,
    ) -> None: ...
    def update(self, **_ignored: Any) -> bool: ...
    def setColors(self, *args: Any, **kw: Any) -> None: ...
    def setRect(self, rect: _Rect) -> None: ...
    def setOpacity(self, opacity: float) -> None: ...
    def setBorder(self, *args: Any, **kw: Any) -> None: ...
    def setInfo(self, *args: Any, **kw: Any) -> None: ...
    def setFlags(self, flags: int) -> None: ...

class Widget:
    def __init__(self, core_widget: _core.Widget) -> None: ...
    @property
    def rect(self) -> Rect: ...
    @property
    def xref(self) -> int: ...
    @property
    def field_type(self) -> int: ...
    @property
    def field_type_string(self) -> str: ...
    @property
    def field_name(self) -> str | None: ...
    @property
    def field_label(self) -> str | None: ...
    field_value: Any
    @property
    def field_flags(self) -> int: ...
    @property
    def choice_values(self) -> list[str]: ...
    @property
    def button_states(self) -> list[str]: ...
    def update(self, value: Any = ...) -> None: ...

class Shape:
    def __init__(self, core_shape: _core.Shape) -> None: ...
    def draw_line(self, p1: _Point, p2: _Point) -> Point: ...
    def draw_rect(self, rect: _Rect) -> Rect: ...
    def draw_circle(self, center: _Point, radius: float) -> Point: ...
    def draw_oval(self, rect: _Rect) -> Rect: ...
    def draw_bezier(self, p1: _Point, p2: _Point, p3: _Point, p4: _Point) -> Point: ...
    def draw_polyline(self, points: Sequence[_Point]) -> Point: ...
    def draw_curve(self, points: Sequence[_Point]) -> Point: ...
    def finish(
        self,
        color: _Color = ...,
        fill: _Color = ...,
        width: float = ...,
        dashes: Any = ...,
        even_odd: bool = ...,
        closePath: bool = ...,
        **_ignored: Any,
    ) -> None: ...
    def commit(self, overlay: bool = ...) -> None: ...

class TextPage:
    def __init__(self, core_tp: _core.TextPage) -> None: ...
    def extractText(self) -> str: ...
    def extractWORDS(self) -> list[tuple[Any, ...]]: ...
    def extractBLOCKS(self) -> list[tuple[Any, ...]]: ...
    def extractDICT(self) -> dict[str, Any]: ...
    def extractRAWDICT(self) -> dict[str, Any]: ...
    def extractJSON(self) -> str: ...
    @property
    def rect(self) -> Rect: ...

class Table:
    def __init__(self, core_table: _core.Table) -> None: ...
    @property
    def bbox(self) -> Rect: ...
    @property
    def row_count(self) -> int: ...
    @property
    def col_count(self) -> int: ...
    @property
    def header(self) -> list[Any]: ...
    @property
    def rows(self) -> list[float]: ...
    @property
    def cols(self) -> list[float]: ...
    @property
    def cells(self) -> list[list[Rect | None]]: ...
    @property
    def spans(self) -> list[tuple[int, int, int, int, Rect]]: ...
    def extract(self) -> list[list[Any]]: ...
    def to_markdown(self) -> str: ...
    def to_html(self) -> str: ...
    def toMarkdown(self) -> str: ...

class TableFinder:
    def __init__(self, core_finder: _core.TableFinder) -> None: ...
    @property
    def tables(self) -> list[Table]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Table: ...
    def __iter__(self) -> Iterator[Table]: ...

class Page:
    def __init__(self, core_page: _core.Page) -> None: ...
    @property
    def number(self) -> int: ...
    @property
    def rect(self) -> Rect: ...
    def bound(self) -> Rect: ...
    @property
    def mediabox(self) -> Rect: ...
    @property
    def cropbox(self) -> Rect: ...
    @property
    def rotation(self) -> int: ...
    @property
    def is_image_only(self) -> bool: ...
    @property
    def first_annot(self) -> Annot | None: ...
    @property
    def first_widget(self) -> Widget | None: ...
    @property
    def firstAnnot(self) -> Annot | None: ...
    @property
    def firstWidget(self) -> Widget | None: ...
    def get_textpage(self, flags: int | None = ..., clip: _Rect | None = ...) -> TextPage: ...
    def get_textpage_ocr(
        self,
        flags: int = ...,
        language: str = ...,
        dpi: int = ...,
        full: bool = ...,
        tessdata: str | None = ...,
    ) -> TextPage: ...
    def get_text(
        self,
        option: str = ...,
        *,
        clip: _Rect | None = ...,
        flags: int | None = ...,
        textpage: TextPage | None = ...,
        sort: bool = ...,
    ) -> str | list[Any] | dict[str, Any]: ...
    def search_for(
        self,
        needle: str,
        *,
        hit_max: int = ...,
        quads: bool = ...,
        clip: _Rect | None = ...,
        flags: int | None = ...,
        textpage: TextPage | None = ...,
    ) -> list[Quad] | list[Rect]: ...
    def get_fonts(self, full: bool = ...) -> list[tuple[Any, ...]]: ...
    def get_images(self, full: bool = ...) -> list[tuple[Any, ...]]: ...
    def get_xobjects(self) -> list[tuple[Any, ...]]: ...
    def get_image_rects(self, *args: Any, **kwargs: Any) -> list[Rect]: ...
    def get_image_info(self, *args: Any, **kwargs: Any) -> list[dict[str, Any]]: ...
    def get_image_bbox(self, name_or_xref: Any, *args: Any, **kwargs: Any) -> Rect: ...
    def get_contents(self) -> list[int]: ...
    def read_contents(self) -> bytes: ...
    def show_pdf_page(
        self, rect: _Rect, src: Document, pno: int = ..., *args: Any, **kwargs: Any
    ) -> str: ...
    def get_pixmap(
        self,
        *,
        matrix: _Matrix | None = ...,
        dpi: int | None = ...,
        colorspace: Any = ...,
        alpha: bool = ...,
        clip: _Rect | None = ...,
    ) -> Pixmap: ...
    def get_displaylist(self) -> DisplayList: ...
    def find_tables(
        self,
        *,
        strategy: str = ...,
        line_max_thickness: float = ...,
        snap_tolerance: float = ...,
        min_line_length: float = ...,
        clip: _Rect | None = ...,
        **_ignored: Any,
    ) -> TableFinder: ...
    def get_svg_image(
        self, matrix: _Matrix | None = ..., *, text_as_path: bool = ..., **_ignored: Any
    ) -> str: ...
    def get_links(self) -> list[dict[str, Any]]: ...
    def insert_link(self, link: dict[str, Any]) -> None: ...
    def delete_link(self, link: dict[str, Any]) -> None: ...
    def get_label(self) -> str: ...
    def set_rotation(self, rotation: int) -> None: ...
    def insert_text(
        self,
        point: _Point,
        text: str,
        *,
        fontname: str = ...,
        fontsize: float = ...,
        color: _Color = ...,
        fontfile: str | None = ...,
        **_ignored: Any,
    ) -> int: ...
    def insert_textbox(
        self,
        rect: _Rect,
        text: str,
        *,
        fontname: str = ...,
        fontsize: float = ...,
        color: _Color = ...,
        align: int = ...,
        fontfile: str | None = ...,
        **_ignored: Any,
    ) -> float: ...
    def insert_image(
        self,
        rect: _Rect,
        *,
        stream: bytes | None = ...,
        filename: str | os.PathLike[str] | None = ...,
        pixmap: Pixmap | None = ...,
        width: int = ...,
        height: int = ...,
        **_ignored: Any,
    ) -> None: ...
    def draw_line(
        self, p1: _Point, p2: _Point, *, color: _Color = ..., width: float = ..., **_ignored: Any
    ) -> None: ...
    def draw_rect(
        self,
        rect: _Rect,
        *,
        color: _Color = ...,
        fill: _Color = ...,
        width: float = ...,
        **_ignored: Any,
    ) -> None: ...
    def draw_circle(
        self,
        center: _Point,
        radius: float,
        *,
        color: _Color = ...,
        fill: _Color = ...,
        width: float = ...,
        **_ignored: Any,
    ) -> None: ...
    def draw_oval(
        self,
        rect: _Rect,
        *,
        color: _Color = ...,
        fill: _Color = ...,
        width: float = ...,
        **_ignored: Any,
    ) -> None: ...
    def draw_bezier(
        self,
        p1: _Point,
        p2: _Point,
        p3: _Point,
        p4: _Point,
        *,
        color: _Color = ...,
        width: float = ...,
        **_ignored: Any,
    ) -> None: ...
    def draw_polyline(
        self, points: Sequence[_Point], *, color: _Color = ..., width: float = ..., **_ignored: Any
    ) -> None: ...
    def new_shape(self) -> Shape: ...
    def add_text_annot(
        self, point: _Point, text: str, *, icon: str = ..., **_ignored: Any
    ) -> Annot: ...
    def add_freetext_annot(
        self,
        rect: _Rect,
        text: str,
        *,
        fontsize: float = ...,
        text_color: _Color = ...,
        fill_color: _Color = ...,
        align: int = ...,
        **_ignored: Any,
    ) -> Annot: ...
    def add_highlight_annot(
        self,
        quads: _Quad | Sequence[_Quad] | None = ...,
        *,
        start: _Point | None = ...,
        stop: _Point | None = ...,
        clip: _Rect | None = ...,
        **_ignored: Any,
    ) -> Annot: ...
    def add_underline_annot(
        self,
        quads: _Quad | Sequence[_Quad] | None = ...,
        *,
        start: _Point | None = ...,
        stop: _Point | None = ...,
        clip: _Rect | None = ...,
        **_ignored: Any,
    ) -> Annot: ...
    def add_strikeout_annot(
        self,
        quads: _Quad | Sequence[_Quad] | None = ...,
        *,
        start: _Point | None = ...,
        stop: _Point | None = ...,
        clip: _Rect | None = ...,
        **_ignored: Any,
    ) -> Annot: ...
    def add_squiggly_annot(
        self,
        quads: _Quad | Sequence[_Quad] | None = ...,
        *,
        start: _Point | None = ...,
        stop: _Point | None = ...,
        clip: _Rect | None = ...,
        **_ignored: Any,
    ) -> Annot: ...
    def add_rect_annot(
        self, rect: _Rect, *, color: _Color = ..., fill: _Color = ..., **_ignored: Any
    ) -> Annot: ...
    def add_circle_annot(
        self, rect: _Rect, *, color: _Color = ..., fill: _Color = ..., **_ignored: Any
    ) -> Annot: ...
    def add_line_annot(
        self, p1: _Point, p2: _Point, *, color: _Color = ..., **_ignored: Any
    ) -> Annot: ...
    def add_polygon_annot(
        self, points: Sequence[_Point], *, color: _Color = ..., fill: _Color = ..., **_ignored: Any
    ) -> Annot: ...
    def add_polyline_annot(
        self, points: Sequence[_Point], *, color: _Color = ..., **_ignored: Any
    ) -> Annot: ...
    def add_ink_annot(
        self, handwriting: Sequence[Sequence[_Point]], *, color: _Color = ..., **_ignored: Any
    ) -> Annot: ...
    def add_stamp_annot(self, rect: _Rect, *, stamp: str = ..., **_ignored: Any) -> Annot: ...
    def add_file_annot(
        self,
        point: _Point,
        buffer: bytes,
        filename: str,
        *,
        ufilename: str | None = ...,
        desc: str | None = ...,
        icon: str | None = ...,
        **_ignored: Any,
    ) -> Annot: ...
    def add_redact_annot(
        self, quad: _Quad, *, text: str | None = ..., fill: _Color = ..., **_ignored: Any
    ) -> Annot: ...
    def annots(self, types: Sequence[int] | None = ...) -> Iterator[Annot]: ...
    def annot_xrefs(self) -> list[int]: ...
    def annot_names(self) -> list[str]: ...
    def delete_annot(self, annot: Annot | int) -> None: ...
    def apply_redactions(self, *args: Any, **kwargs: Any) -> int: ...
    def get_drawings(self, **_ignored: Any) -> list[dict[str, Any]]: ...
    def get_cdrawings(self, **_ignored: Any) -> list[dict[str, Any]]: ...
    def widgets(self) -> list[Widget]: ...
    # PyMuPDF deprecated camelCase aliases.
    def getPixmap(self, *args: Any, **kw: Any) -> Pixmap: ...
    def getTextPageOCR(self, *args: Any, **kw: Any) -> TextPage: ...
    def getDisplayList(self) -> DisplayList: ...
    def findTables(self, **kw: Any) -> TableFinder: ...
    def getSVGimage(self, *args: Any, **kw: Any) -> str: ...
    def getImages(self, full: bool = ...) -> list[tuple[Any, ...]]: ...
    def getLinks(self) -> list[dict[str, Any]]: ...
    def setRotation(self, rotation: int) -> None: ...
    def insertText(self, *args: Any, **kw: Any) -> int: ...
    def insertTextbox(self, *args: Any, **kw: Any) -> float: ...
    def insertImage(self, *args: Any, **kw: Any) -> None: ...
    def drawLine(self, *args: Any, **kw: Any) -> None: ...
    def drawRect(self, *args: Any, **kw: Any) -> None: ...
    def drawCircle(self, *args: Any, **kw: Any) -> None: ...
    def drawOval(self, *args: Any, **kw: Any) -> None: ...
    def drawBezier(self, *args: Any, **kw: Any) -> None: ...
    def drawPolyline(self, *args: Any, **kw: Any) -> None: ...
    def newShape(self) -> Shape: ...
    def addTextAnnot(self, *args: Any, **kw: Any) -> Annot: ...
    def addFreetextAnnot(self, *args: Any, **kw: Any) -> Annot: ...
    def addHighlightAnnot(self, *args: Any, **kw: Any) -> Annot: ...
    def addUnderlineAnnot(self, *args: Any, **kw: Any) -> Annot: ...
    def addStrikeoutAnnot(self, *args: Any, **kw: Any) -> Annot: ...
    def addSquigglyAnnot(self, *args: Any, **kw: Any) -> Annot: ...
    def addRectAnnot(self, *args: Any, **kw: Any) -> Annot: ...
    def addCircleAnnot(self, *args: Any, **kw: Any) -> Annot: ...
    def addLineAnnot(self, *args: Any, **kw: Any) -> Annot: ...
    def addPolygonAnnot(self, *args: Any, **kw: Any) -> Annot: ...
    def addPolylineAnnot(self, *args: Any, **kw: Any) -> Annot: ...
    def addInkAnnot(self, *args: Any, **kw: Any) -> Annot: ...
    def addStampAnnot(self, *args: Any, **kw: Any) -> Annot: ...
    def addFileAnnot(self, *args: Any, **kw: Any) -> Annot: ...
    def addRedactAnnot(self, *args: Any, **kw: Any) -> Annot: ...
    def applyRedactions(self, *args: Any, **kw: Any) -> int: ...
    def getDrawings(self, **kw: Any) -> list[dict[str, Any]]: ...
    def getCdrawings(self, **kw: Any) -> list[dict[str, Any]]: ...
    def deleteAnnot(self, annot: Annot | int) -> None: ...

class Document:
    def __init__(self, core_doc: _core.Document) -> None: ...
    @property
    def page_count(self) -> int: ...
    def __len__(self) -> int: ...
    def load_page(self, index: int = ...) -> Page: ...
    def __getitem__(self, index: int) -> Page: ...
    def __iter__(self) -> Iterator[Page]: ...
    def pages(self, *args: Any, **kwargs: Any) -> Iterator[Page]: ...
    def reload_page(self, page: Page | int) -> Page: ...
    def page_xref(self, pno: int) -> int: ...
    def get_page_xobjects(self, pno: int) -> list[tuple[Any, ...]]: ...
    def resolve_link(self, uri: str = ..., *, chapters: int = ...) -> int | None: ...
    def fullcopy_page(self, pno: int, to: int = ...) -> None: ...
    @property
    def chapter_count(self) -> int: ...
    def chapter_page_count(self, chapter: int) -> int: ...
    @property
    def last_location(self) -> tuple[int, int]: ...
    @property
    def is_pdf(self) -> bool: ...
    @property
    def is_repaired(self) -> bool: ...
    @property
    def is_encrypted(self) -> bool: ...
    @property
    def needs_pass(self) -> bool: ...
    @property
    def permissions(self) -> int: ...
    def authenticate(self, password: str | bytes) -> bool: ...
    def get_page_text(
        self, pno: int, option: str = ..., *, flags: int | None = ..., sort: bool = ...
    ) -> str | list[Any] | dict[str, Any]: ...
    @property
    def metadata(self) -> dict[str, str]: ...
    def xref_length(self) -> int: ...
    def xref_object(self, xref: int) -> str: ...
    def xref_get_key(self, xref: int, key: str) -> Any: ...
    def xref_is_stream(self, xref: int) -> bool: ...
    def xref_stream(self, xref: int) -> bytes: ...
    def extract_image(self, xref: int) -> dict[str, Any]: ...
    def extractImage(self, xref: int) -> dict[str, Any]: ...
    def get_page_pixmap(self, pno: int, **kw: Any) -> Pixmap: ...
    def save(
        self,
        filename: str | os.PathLike[str],
        *,
        garbage: int = ...,
        deflate: bool = ...,
        incremental: bool = ...,
        encryption: int | None = ...,
        owner_pw: str | None = ...,
        user_pw: str | None = ...,
        permissions: int = ...,
        **_ignored: Any,
    ) -> None: ...
    def tobytes(
        self,
        *,
        garbage: int = ...,
        deflate: bool = ...,
        incremental: bool = ...,
        encryption: int | None = ...,
        owner_pw: str | None = ...,
        user_pw: str | None = ...,
        permissions: int = ...,
        **_ignored: Any,
    ) -> bytes: ...
    def write(
        self,
        *,
        garbage: int = ...,
        deflate: bool = ...,
        incremental: bool = ...,
        encryption: int | None = ...,
        owner_pw: str | None = ...,
        user_pw: str | None = ...,
        permissions: int = ...,
        **_ignored: Any,
    ) -> bytes: ...
    def pdfocr_tobytes(
        self,
        *,
        compress: bool = ...,
        language: str = ...,
        tessdata: str | None = ...,
        dpi: int = ...,
    ) -> bytes: ...
    def pdfocr_save(
        self,
        filename: str | os.PathLike[str],
        *,
        compress: bool = ...,
        language: str = ...,
        tessdata: str | None = ...,
        dpi: int = ...,
    ) -> None: ...
    def ez_save(self, filename: str | os.PathLike[str], **kwargs: Any) -> None: ...
    def saveIncr(self, filename: str | os.PathLike[str] | None = ...) -> None: ...
    def set_metadata(self, metadata: dict[str, Any]) -> None: ...
    def setMetadata(self, metadata: dict[str, Any]) -> None: ...
    def get_xml_metadata(self) -> str: ...
    def set_xml_metadata(self, xml: str) -> None: ...
    def get_toc(self, simple: bool = ...) -> list[list[Any]]: ...
    def getToC(self, simple: bool = ...) -> list[list[Any]]: ...
    def set_toc(self, toc: list[Any]) -> None: ...
    def setToC(self, toc: list[Any]) -> None: ...
    def insert_pdf(
        self,
        docsrc: Document,
        from_page: int | None = ...,
        to_page: int | None = ...,
        start_at: int | None = ...,
        **_ignored: Any,
    ) -> None: ...
    def insertPDF(self, docsrc: Document, **kwargs: Any) -> None: ...
    def new_page(self, pno: int = ..., width: float = ..., height: float = ...) -> Page: ...
    def newPage(self, pno: int = ..., width: float = ..., height: float = ...) -> Page: ...
    def delete_page(self, pno: int = ...) -> None: ...
    def select(self, pages: Sequence[int]) -> None: ...
    def get_page_label(self, pno: int) -> str: ...
    def set_page_labels(self, labels: Sequence[dict[str, Any]]) -> None: ...
    def get_char_widths(self, xref: int, *args: Any, **kwargs: Any) -> list[tuple[int, float]]: ...
    def page_cropbox(self, pno: int) -> Rect: ...
    def page_mediabox(self, pno: int) -> Rect: ...
    def journal_enable(self) -> None: ...
    def journal_is_enabled(self) -> bool: ...
    def journal_save_state(self) -> None: ...
    def journal_can_undo(self) -> bool: ...
    def journal_can_redo(self) -> bool: ...
    def journal_can_do(self) -> dict[str, bool]: ...
    def journal_undo(self) -> bool: ...
    def journal_redo(self) -> bool: ...
    @property
    def is_form_pdf(self) -> bool: ...
    @property
    def isFormPDF(self) -> bool: ...
    def form_field_names(self) -> list[str]: ...
    def form_fill(self, name: str, value: Any) -> None: ...
    def form_flatten(self) -> None: ...
    def embfile_add(
        self,
        name: str,
        buffer: bytes,
        filename: str | None = ...,
        ufilename: str | None = ...,
        desc: str | None = ...,
        **_ignored: Any,
    ) -> None: ...
    def embfile_get(self, name: str) -> bytes: ...
    def embfile_del(self, name: str) -> None: ...
    def embfile_names(self) -> list[str]: ...
    def embfile_count(self) -> int: ...
    def embfile_info(self, name: str) -> dict[str, Any]: ...
    def embfileAdd(self, *args: Any, **kw: Any) -> None: ...
    def embfileGet(self, name: str) -> bytes: ...
    def embfileDel(self, name: str) -> None: ...
    def embfileNames(self) -> list[str]: ...
    def embfileCount(self) -> int: ...
    def embfileInfo(self, name: str) -> dict[str, Any]: ...
    def scrub(
        self,
        *,
        attached_files: bool = ...,
        clean_pages: bool = ...,
        embedded_files: bool = ...,
        hidden_text: bool = ...,
        javascript: bool = ...,
        metadata: bool = ...,
        redactions: bool = ...,
        redact_images: int = ...,
        remove_links: bool = ...,
        reset_fields: bool = ...,
        reset_responses: bool = ...,
        thumbnails: bool = ...,
        xml_metadata: bool = ...,
        **_ignored: Any,
    ) -> None: ...
    def bake(self, *, annots: bool = ..., widgets: bool = ..., **_ignored: Any) -> None: ...
    def get_ocgs(self) -> dict[int, dict[str, Any]]: ...
    def layer_ui_configs(self) -> list[dict[str, Any]]: ...
    def ocg_state(self, xref: int) -> bool: ...
    def get_layer(self, config: int = ...) -> dict[str, list[int]]: ...
    def set_layer(
        self,
        config: int = ...,
        *,
        on: list[int] | None = ...,
        off: list[int] | None = ...,
        locked: list[int] | None = ...,
        **_ignored: Any,
    ) -> None: ...
    def add_ocg(
        self,
        name: str,
        config: int | str | None = ...,
        *,
        on: bool = ...,
        intent: str = ...,
        usage: str | None = ...,
        **_ignored: Any,
    ) -> int: ...
    def set_oc(self, xref: int, ocg: int) -> None: ...
    def getOCGs(self) -> dict[int, dict[str, Any]]: ...
    def layerUIConfigs(self) -> list[dict[str, Any]]: ...
    def getLayer(self, config: int = ...) -> dict[str, list[int]]: ...
    def setLayer(self, *args: Any, **kw: Any) -> None: ...
    def addOCG(self, *args: Any, **kw: Any) -> int: ...
    def setOC(self, xref: int, ocg: int) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Document: ...
    def __exit__(self, *exc: Any) -> None: ...

def open(
    filename: str | os.PathLike[str] | None = ...,
    *,
    stream: bytes | None = ...,
    filetype: str | None = ...,
) -> Document: ...
