#!/usr/bin/env python3
"""LOCAL-ONLY LibreOffice oracle for the typeset fixtures (PRD §10 TS-7).

pdf-typeset lays out docx/pptx-shaped content directly; LibreOffice is the
independent reference implementation of that layout. This script authors the
same content twice — a minimal ``sample.docx`` / ``sample.pptx`` (hand-built
OOXML, no dependencies) converted to PDF by ``soffice --headless``, and the
committed engine fixtures ``fixtures/typeset/typeset-lo-doc.pdf`` /
``typeset-lo-slide.pdf`` (generated by
``cargo run -p pdf-typeset --example make_typeset_fixtures``) — rasterizes
BOTH sides with pdfspine's own ``get_pixmap`` and scores perceptual agreement
with ``render_diff.py``'s pure-Python SSIM.

Agreement is **advisory**: line breaking, leading and justification legitimately
differ between engines, so the expected score sits in the 0.80–0.90 band
(above = better than expected, below = investigate a layout regression). The
script therefore never turns a comparison into a failure exit — it emits a
report and exits 0. Only an environment problem (no soffice, conversion
failure) exits non-zero.

**LibreOffice must never become a CI dependency** (PRD §10 TS-7): this script
is run by hand, locally, and the committed report is a snapshot.

Usage (from the repo root, in the project venv)::

    python conformance/gt/typeset_lo_oracle.py \
        --report conformance/gt/TYPESET-LO-REPORT.md

The sample .docx/.pptx text/geometry constants below MUST stay in sync with
``crates/pdf-typeset/examples/make_typeset_fixtures.rs`` (`lo_doc_fixture` /
`lo_slide_fixture`) — the two sides are the same document by construction.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import time
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))

import render_diff  # noqa: E402  (shared gray-raster + SSIM helpers)

# Advisory agreement band (PRD §10 TS-7).
BAND_LO = 0.80
BAND_HI = 0.90
# More detail than the committed-reference buffers (192): this is a local
# perceptual comparison, not a git-committed artifact.
GRAY_MAX_DIM = 256

# ---------------------------------------------------------------------------
# Shared content — keep in sync with make_typeset_fixtures.rs (lo_* fixtures).
# ---------------------------------------------------------------------------
DOC_TITLE = "Typeset LibreOffice Oracle Sample"
DOC_PARAS = [
    "This document is authored twice: once as a minimal docx converted to PDF "
    "by LibreOffice, and once through the pdf typeset engine with the bundled "
    "Liberation Serif face. The two renderings are rasterized by the same in "
    "repo renderer and compared with SSIM.",
    "Agreement is advisory rather than exact because line breaking, leading "
    "and justification differ slightly between engines. The expected band for "
    "this pair is between zero point eight zero and zero point nine zero "
    "structural similarity.",
    "A large regression such as missing text, wrong font size, broken "
    "wrapping or displaced margins drops the score far below the band and is "
    "investigated locally before any release.",
]
SLIDE_TITLE = "Typeset LibreOffice Oracle Slide"
SLIDE_LINES = [
    "First body line rendered at eighteen points",
    "Second body line for the advisory comparison",
    "Third body line keeps the layout deliberately plain",
    "Fourth body line closes the sample slide",
]

# ---------------------------------------------------------------------------
# Minimal OOXML authoring (deterministic, dependency-free)
# ---------------------------------------------------------------------------
XML_DECL = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
NS_CT = "http://schemas.openxmlformats.org/package/2006/content-types"
NS_REL = "http://schemas.openxmlformats.org/package/2006/relationships"
NS_ODOC = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
NS_W = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
NS_A = "http://schemas.openxmlformats.org/drawingml/2006/main"
NS_P = "http://schemas.openxmlformats.org/presentationml/2006/main"


def _zip_write(path: Path, members: list[tuple[str, str]]) -> None:
    """Write an OOXML package with fixed timestamps (deterministic bytes)."""
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, text in members:
            info = zipfile.ZipInfo(name, date_time=(2020, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            zf.writestr(info, text.encode("utf-8"))


def _rels(pairs: list[tuple[str, str, str]]) -> str:
    rows = "".join(
        f'<Relationship Id="{rid}" Type="{typ}" Target="{tgt}"/>'
        for rid, typ, tgt in pairs
    )
    return f'{XML_DECL}<Relationships xmlns="{NS_REL}">{rows}</Relationships>'


def build_docx(path: Path) -> None:
    """One Letter page, 1-in margins, Liberation Serif — mirrors typeset-lo-doc."""

    def para(text: str, *, size_half_pt: int, bold: bool, after_20th: int) -> str:
        b = "<w:b/>" if bold else ""
        rpr = (
            f'<w:rPr><w:rFonts w:ascii="Liberation Serif" w:hAnsi="Liberation Serif"/>'
            f'{b}<w:sz w:val="{size_half_pt}"/></w:rPr>'
        )
        return (
            f'<w:p><w:pPr><w:spacing w:before="0" w:after="{after_20th}" '
            f'w:line="240" w:lineRule="auto"/></w:pPr>'
            f"<w:r>{rpr}<w:t xml:space=\"preserve\">{text}</w:t></w:r></w:p>"
        )

    body = para(DOC_TITLE, size_half_pt=48, bold=True, after_20th=240)
    for p in DOC_PARAS:
        body += para(p, size_half_pt=24, bold=False, after_20th=200)
    document = (
        f'{XML_DECL}<w:document xmlns:w="{NS_W}"><w:body>{body}'
        f'<w:sectPr><w:pgSz w:w="12240" w:h="15840"/>'
        f'<w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" '
        f'w:header="720" w:footer="720" w:gutter="0"/></w:sectPr>'
        f"</w:body></w:document>"
    )
    content_types = (
        f'{XML_DECL}<Types xmlns="{NS_CT}">'
        f'<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        f'<Default Extension="xml" ContentType="application/xml"/>'
        f'<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
        f"</Types>"
    )
    _zip_write(path, [
        ("[Content_Types].xml", content_types),
        ("_rels/.rels", _rels([("rId1", f"{NS_ODOC}/officeDocument", "word/document.xml")])),
        ("word/document.xml", document),
    ])


def build_pptx(path: Path) -> None:
    """One 10x7.5-in slide, two zero-inset boxes — mirrors typeset-lo-slide."""
    emu = lambda pt: str(round(pt * 12700))  # noqa: E731 — 1 pt = 12700 EMU

    def textbox(shape_id: int, name: str, x: float, y: float, w: float, h: float,
                paras: str) -> str:
        return (
            f'<p:sp><p:nvSpPr><p:cNvPr id="{shape_id}" name="{name}"/>'
            f'<p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr>'
            f'<p:spPr><a:xfrm><a:off x="{emu(x)}" y="{emu(y)}"/>'
            f'<a:ext cx="{emu(w)}" cy="{emu(h)}"/></a:xfrm>'
            f'<a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/></p:spPr>'
            f'<p:txBody><a:bodyPr wrap="square" lIns="0" tIns="0" rIns="0" bIns="0" '
            f'anchor="t"/><a:lstStyle/>{paras}</p:txBody></p:sp>'
        )

    def para(text: str, *, size_100th_pt: int, bold: bool, after_100th_pt: int) -> str:
        b = ' b="1"' if bold else ""
        ppr = (
            f'<a:pPr><a:spcAft><a:spcPts val="{after_100th_pt}"/></a:spcAft></a:pPr>'
            if after_100th_pt
            else ""
        )
        return (
            f"<a:p>{ppr}<a:r>"
            f'<a:rPr lang="en-US" sz="{size_100th_pt}"{b} dirty="0">'
            f'<a:latin typeface="Liberation Sans"/></a:rPr>'
            f"<a:t>{text}</a:t></a:r></a:p>"
        )

    # Geometry mirrors lo_slide_fixture: title (72,60)-(648,140), body
    # (72,180)-(648,460) on a 720x540 pt slide.
    title = textbox(2, "Title", 72, 60, 576, 80,
                    para(SLIDE_TITLE, size_100th_pt=2800, bold=True, after_100th_pt=0))
    body_paras = "".join(
        para(t, size_100th_pt=1800, bold=False, after_100th_pt=800) for t in SLIDE_LINES
    )
    body = textbox(3, "Body", 72, 180, 576, 280, body_paras)

    sp_tree_head = (
        '<p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>'
        "<p:grpSpPr/>"
    )
    slide = (
        f'{XML_DECL}<p:sld xmlns:a="{NS_A}" xmlns:r="{NS_ODOC}" xmlns:p="{NS_P}">'
        f"<p:cSld><p:spTree>{sp_tree_head}{title}{body}</p:spTree></p:cSld>"
        f"<p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>"
    )
    presentation = (
        f'{XML_DECL}<p:presentation xmlns:a="{NS_A}" xmlns:r="{NS_ODOC}" xmlns:p="{NS_P}">'
        f'<p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst>'
        f'<p:sldIdLst><p:sldId id="256" r:id="rId2"/></p:sldIdLst>'
        f'<p:sldSz cx="9144000" cy="6858000"/><p:notesSz cx="6858000" cy="9144000"/>'
        f"</p:presentation>"
    )
    master = (
        f'{XML_DECL}<p:sldMaster xmlns:a="{NS_A}" xmlns:r="{NS_ODOC}" xmlns:p="{NS_P}">'
        f"<p:cSld><p:spTree>{sp_tree_head}</p:spTree></p:cSld>"
        f'<p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1" '
        f'accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" '
        f'accent6="accent6" hlink="hlink" folHlink="folHlink"/>'
        f'<p:sldLayoutIdLst><p:sldLayoutId id="2147483649" r:id="rId1"/></p:sldLayoutIdLst>'
        f"</p:sldMaster>"
    )
    layout = (
        f'{XML_DECL}<p:sldLayout xmlns:a="{NS_A}" xmlns:r="{NS_ODOC}" xmlns:p="{NS_P}">'
        f"<p:cSld><p:spTree>{sp_tree_head}</p:spTree></p:cSld>"
        f"<p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>"
    )

    accents = "".join(
        f"<a:{tag}><a:srgbClr val=\"{val}\"/></a:{tag}>"
        for tag, val in [
            ("dk1", "000000"), ("lt1", "FFFFFF"), ("dk2", "1F1F1F"), ("lt2", "F0F0F0"),
            ("accent1", "4472C4"), ("accent2", "ED7D31"), ("accent3", "A5A5A5"),
            ("accent4", "FFC000"), ("accent5", "5B9BD5"), ("accent6", "70AD47"),
            ("hlink", "0563C1"), ("folHlink", "954F72"),
        ]
    )
    solid = '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>'
    line = f'<a:ln w="6350">{solid}</a:ln>'
    effect = "<a:effectStyle><a:effectLst/></a:effectStyle>"
    font = (
        '<a:latin typeface="Liberation Sans"/><a:ea typeface=""/><a:cs typeface=""/>'
    )
    theme = (
        f'{XML_DECL}<a:theme xmlns:a="{NS_A}" name="Minimal"><a:themeElements>'
        f'<a:clrScheme name="Minimal">{accents}</a:clrScheme>'
        f'<a:fontScheme name="Minimal"><a:majorFont>{font}</a:majorFont>'
        f"<a:minorFont>{font}</a:minorFont></a:fontScheme>"
        f'<a:fmtScheme name="Minimal"><a:fillStyleLst>{solid * 3}</a:fillStyleLst>'
        f"<a:lnStyleLst>{line * 3}</a:lnStyleLst>"
        f"<a:effectStyleLst>{effect * 3}</a:effectStyleLst>"
        f"<a:bgFillStyleLst>{solid * 3}</a:bgFillStyleLst></a:fmtScheme>"
        f"</a:themeElements></a:theme>"
    )

    ct = "application/vnd.openxmlformats-officedocument.presentationml"
    content_types = (
        f'{XML_DECL}<Types xmlns="{NS_CT}">'
        f'<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        f'<Default Extension="xml" ContentType="application/xml"/>'
        f'<Override PartName="/ppt/presentation.xml" ContentType="{ct}.presentation.main+xml"/>'
        f'<Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="{ct}.slideMaster+xml"/>'
        f'<Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="{ct}.slideLayout+xml"/>'
        f'<Override PartName="/ppt/slides/slide1.xml" ContentType="{ct}.slide+xml"/>'
        f'<Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>'
        f"</Types>"
    )
    _zip_write(path, [
        ("[Content_Types].xml", content_types),
        ("_rels/.rels", _rels([("rId1", f"{NS_ODOC}/officeDocument", "ppt/presentation.xml")])),
        ("ppt/presentation.xml", presentation),
        ("ppt/_rels/presentation.xml.rels", _rels([
            ("rId1", f"{NS_ODOC}/slideMaster", "slideMasters/slideMaster1.xml"),
            ("rId2", f"{NS_ODOC}/slide", "slides/slide1.xml"),
        ])),
        ("ppt/slideMasters/slideMaster1.xml", master),
        ("ppt/slideMasters/_rels/slideMaster1.xml.rels", _rels([
            ("rId1", f"{NS_ODOC}/slideLayout", "../slideLayouts/slideLayout1.xml"),
            ("rId2", f"{NS_ODOC}/theme", "../theme/theme1.xml"),
        ])),
        ("ppt/slideLayouts/slideLayout1.xml", layout),
        ("ppt/slideLayouts/_rels/slideLayout1.xml.rels", _rels([
            ("rId1", f"{NS_ODOC}/slideMaster", "../slideMasters/slideMaster1.xml"),
        ])),
        ("ppt/theme/theme1.xml", theme),
        ("ppt/slides/slide1.xml", slide),
        ("ppt/slides/_rels/slide1.xml.rels", _rels([
            ("rId1", f"{NS_ODOC}/slideLayout", "../slideLayouts/slideLayout1.xml"),
        ])),
    ])


# ---------------------------------------------------------------------------
# LibreOffice conversion
# ---------------------------------------------------------------------------
SOFFICE_CANDIDATES = [
    "/Applications/LibreOffice.app/Contents/MacOS/soffice",  # macOS
    "/usr/bin/soffice",  # Linux
    "/usr/local/bin/soffice",
    r"C:\Program Files\LibreOffice\program\soffice.exe",  # Windows
]


def find_soffice(explicit: str | None) -> str | None:
    if explicit:
        return explicit if Path(explicit).exists() else None
    found = shutil.which("soffice")
    if found:
        return found
    for cand in SOFFICE_CANDIDATES:
        if Path(cand).exists():
            return cand
    return None


def convert_to_pdf(soffice: str, src: Path, out_dir: Path, timeout: float) -> Path:
    """``soffice --headless --convert-to pdf`` with an isolated user profile
    (a running desktop LibreOffice instance must not swallow the request)."""
    profile = out_dir / "lo-profile"
    profile.mkdir(parents=True, exist_ok=True)
    cmd = [
        soffice, "--headless", "--norestore",
        f"-env:UserInstallation={profile.resolve().as_uri()}",
        "--convert-to", "pdf", "--outdir", str(out_dir), str(src),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    out_pdf = out_dir / (src.stem + ".pdf")
    if proc.returncode != 0 or not out_pdf.exists():
        msg = (proc.stderr or proc.stdout or "").strip().replace("\n", " ")
        raise RuntimeError(f"soffice conversion failed for {src.name}: "
                           f"exit {proc.returncode}: {msg[:300]}")
    return out_pdf


# ---------------------------------------------------------------------------
# Comparison + report
# ---------------------------------------------------------------------------
def compare_pair(fixture_pdf: Path, oracle_pdf: Path, dpi: float) -> dict:
    """SSIM(fixture raster, LO raster) on page 0, both via pdfspine get_pixmap."""
    fgw, fgh, fpx = render_diff._pdfspine_gray(str(fixture_pdf), 0, dpi, GRAY_MAX_DIM)
    ogw, ogh, opx = render_diff._pdfspine_gray(str(oracle_pdf), 0, dpi, GRAY_MAX_DIM)
    tw, th = min(fgw, ogw), min(fgh, ogh)
    ffit = render_diff._resize_gray(fgw, fgh, fpx, tw, th)
    ofit = render_diff._resize_gray(ogw, ogh, opx, tw, th)
    s = render_diff.ssim(ffit, ofit, tw, th)
    if s >= BAND_HI:
        status = "above-band"
    elif s >= BAND_LO:
        status = "in-band"
    else:
        status = "below-band"
    return {
        "fixture": str(fixture_pdf.relative_to(ROOT)),
        "oracle": oracle_pdf.name,
        "ssim": round(s, 4),
        "status": status,
        "fixture_near_blank": render_diff._near_blank(fpx),
        "oracle_near_blank": render_diff._near_blank(opx),
    }


def render_report(payload: dict) -> str:
    lines = [
        "# Typeset ↔ LibreOffice advisory report (TS-7)",
        "",
        f"*Generated {payload['generated']} · soffice: `{payload['soffice']}` · "
        f"dpi {payload['dpi']} · advisory band **{BAND_LO:.2f}–{BAND_HI:.2f}** "
        f"(local-only — LibreOffice is NOT a CI dependency).*",
        "",
        "The same content is authored as minimal OOXML (converted by LibreOffice)",
        "and as a pdf-typeset fixture; both PDFs are rasterized by pdfspine's own",
        "renderer and compared with pure-Python SSIM. Scores inside or above the",
        "band are expected; `below-band` means a layout regression to investigate.",
        "",
        "| pair | fixture | LO oracle | SSIM | status |",
        "|------|---------|-----------|------|--------|",
    ]
    for p in payload["pairs"]:
        lines.append(
            f"| {p['pair']} | `{p['fixture']}` | `{p['oracle']}` "
            f"| {p['ssim']:.4f} | {p['status']} |"
        )
    lines += [
        "",
        "Regenerate: `python conformance/gt/typeset_lo_oracle.py "
        "--report conformance/gt/TYPESET-LO-REPORT.md`",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--soffice", help="path to the soffice binary (default: autodetect)")
    ap.add_argument("--dpi", type=float, default=100.0)
    ap.add_argument("--timeout", type=float, default=120.0,
                    help="per-conversion wall-clock timeout (s)")
    ap.add_argument("--cache", default=str(HERE / "cache" / "lo-oracle"),
                    help="working dir for samples + converted PDFs (gitignored)")
    ap.add_argument("--report", type=Path, help="markdown report output path")
    ap.add_argument("--json", dest="json_out", type=Path, help="JSON output path")
    args = ap.parse_args(argv)

    soffice = find_soffice(args.soffice)
    if not soffice:
        print("ERROR: no soffice binary found (install LibreOffice or pass "
              "--soffice); this oracle is local-only by design.", file=sys.stderr)
        return 2

    cache = Path(args.cache)
    cache.mkdir(parents=True, exist_ok=True)

    # Distinct stems: soffice names its output <stem>.pdf, so identical stems
    # would collide in the shared --outdir.
    docx = cache / "sample-doc.docx"
    pptx = cache / "sample-slide.pptx"
    build_docx(docx)
    build_pptx(pptx)
    print(f"authored {docx} + {pptx}")

    pairs = []
    try:
        for pair, sample, fixture in [
            ("docx", docx, ROOT / "fixtures" / "typeset" / "typeset-lo-doc.pdf"),
            ("pptx", pptx, ROOT / "fixtures" / "typeset" / "typeset-lo-slide.pdf"),
        ]:
            if not fixture.exists():
                print(f"ERROR: missing committed fixture {fixture} — run "
                      "`cargo run -p pdf-typeset --example make_typeset_fixtures`",
                      file=sys.stderr)
                return 2
            oracle_pdf = convert_to_pdf(soffice, sample, cache, args.timeout)
            print(f"converted {sample.name} -> {oracle_pdf.name}")
            rec = {"pair": pair, **compare_pair(fixture, oracle_pdf, args.dpi)}
            pairs.append(rec)
            print(f"  {pair}: ssim={rec['ssim']} -> {rec['status']}")
    except (RuntimeError, subprocess.TimeoutExpired) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    payload = {
        "generated": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "mode": "lo-oracle-advisory",
        "soffice": soffice,
        "dpi": args.dpi,
        "band": [BAND_LO, BAND_HI],
        "pairs": pairs,
    }
    if args.json_out:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(json.dumps(payload, indent=2), encoding="utf-8")
        print(f"Wrote {args.json_out}")
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(render_report(payload), encoding="utf-8")
        print(f"Wrote {args.report}")

    n_below = sum(1 for p in pairs if p["status"] == "below-band")
    if n_below:
        print(f"ADVISORY: {n_below} pair(s) below the {BAND_LO:.2f} band — "
              "investigate before release (not a gate failure).")
    else:
        print("LO oracle advisory comparison complete — all pairs in/above band.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
