"""Generate ``docs/reference/constants.md`` from ``pdfspine.constants``.

The module-level constants (``fitz.*`` compatibility values) are too numerous
(~250) to hand-maintain, and a per-symbol mkdocstrings directive each would be
noise. Instead this script introspects the *installed* ``pdfspine`` and emits
one grouped table per family, so every name in ``pdfspine.constants.__all__``
plus the re-exported colorspace instances is documented from the source of
truth. Re-run after changing the constants:

    .venv/bin/python scripts/gen_docs_constants.py
"""

from __future__ import annotations

import os
from collections import defaultdict
from pathlib import Path

import pdfspine

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "reference" / "constants.md"

# Ordered (label, predicate) families. First match wins, so order matters.
FAMILIES: list[tuple[str, object]] = [
    ("Colorspace (`CS_*`)", lambda n: n.startswith("CS_")),
    ("Annotation types (`PDF_ANNOT_*`)",
     lambda n: n.startswith("PDF_ANNOT_")
     and not n.startswith(("PDF_ANNOT_IT", "PDF_ANNOT_LE",
                           "PDF_ANNOT_IS", "PDF_ANNOT_Q"))),
    ("Annotation flags (`PDF_ANNOT_IS_*` / `PDF_ANNOT_Q_*`)",
     lambda n: n.startswith(("PDF_ANNOT_IS", "PDF_ANNOT_Q"))),
    ("Annotation intents (`PDF_ANNOT_IT_*`)",
     lambda n: n.startswith("PDF_ANNOT_IT")),
    ("Line endings (`PDF_ANNOT_LE_*`)",
     lambda n: n.startswith("PDF_ANNOT_LE")),
    ("Blend modes (`PDF_BM_*`)", lambda n: n.startswith("PDF_BM")),
    ("Border styles (`PDF_BORDER_STYLE_*`)",
     lambda n: n.startswith("PDF_BORDER")),
    ("Encryption (`PDF_ENCRYPT_*`)", lambda n: n.startswith("PDF_ENCRYPT")),
    ("Form-field flags (`PDF_FIELD_*`)", lambda n: n.startswith("PDF_FIELD")),
    ("Page labels (`PDF_PAGE_LABEL_*`)",
     lambda n: n.startswith("PDF_PAGE_LABEL")),
    ("Permissions (`PDF_PERM_*`)", lambda n: n.startswith("PDF_PERM")),
    ("Redaction (`PDF_REDACT_*`)", lambda n: n.startswith("PDF_REDACT")),
    ("Signatures (`PDF_SIGNATURE_*`)",
     lambda n: n.startswith("PDF_SIGNATURE")),
    ("Tokenizer (`PDF_TOK_*`)", lambda n: n.startswith("PDF_TOK")),
    ("Widget text formats (`PDF_WIDGET_TX_FORMAT_*`)",
     lambda n: n.startswith("PDF_WIDGET_TX")),
    ("Widget types (`PDF_WIDGET_TYPE_*`)",
     lambda n: n.startswith("PDF_WIDGET")),
    ("Stamps (`STAMP_*`)", lambda n: n.startswith("STAMP")),
    ("Signature flags (`SigFlag_*`)", lambda n: n.startswith("SigFlag")),
    ("Text extraction presets (`TEXTFLAGS_*`)",
     lambda n: n.startswith("TEXTFLAGS")),
    ("Text alignment (`TEXT_ALIGN_*`)", lambda n: n.startswith("TEXT_ALIGN")),
    ("Text encodings (`TEXT_ENCODING_*`)",
     lambda n: n.startswith("TEXT_ENCODING")),
    ("Font flags (`TEXT_FONT_*`)", lambda n: n.startswith("TEXT_FONT")),
    ("Text output formats (`TEXT_OUTPUT_*`)",
     lambda n: n.startswith("TEXT_OUTPUT")),
    ("Text extraction flags (`TEXT_*`)", lambda n: n.startswith("TEXT_")),
    ("Version", lambda n: n.startswith("Version") or n in ("version",
                                                            "version_info")),
]


def _family(name: str) -> str:
    for label, pred in FAMILIES:
        if pred(name):  # type: ignore[operator]
            return label
    return "Other"


def _fmt(value: object) -> str:
    text = repr(value)
    if len(text) > 60:
        text = text[:57] + "…"
    return f"`{text}`"


def main() -> None:
    groups: dict[str, list[str]] = defaultdict(list)
    for name in pdfspine.constants.__all__:
        groups[_family(name)].append(name)

    total = sum(len(v) for v in groups.values())

    lines: list[str] = [
        "<!-- AUTO-GENERATED by docs/_scripts/gen_constants.py — do not edit by hand. -->",
        "",
        "# Constants",
        "",
        "::: pdfspine.constants",
        "    options:",
        "      members: false",
        "      show_source: false",
        "",
        f"The {total} PyMuPDF-compatible module-level constants below are "
        "re-exported at the top level of `pdfspine` (e.g. `pdfspine.PDF_ENCRYPT_AES_256`) "
        "and match PyMuPDF 1.27 exactly. They are also reachable via the "
        "`pdfspine.constants` submodule.",
        "",
    ]

    # Stable order following the FAMILIES declaration, then "Other".
    order = [label for label, _ in FAMILIES] + ["Other"]
    for label in order:
        names = groups.get(label)
        if not names:
            continue
        lines.append(f"## {label}")
        lines.append("")
        lines.append("| Name | Value |")
        lines.append("|---|---|")
        for name in sorted(names):
            lines.append(f"| `{name}` | {_fmt(getattr(pdfspine, name))} |")
        lines.append("")

    # Re-exported value instances / collections (not in constants.__all__,
    # but part of the top-level public surface and best documented here).
    lines.append("## Colorspace singletons & font tables")
    lines.append("")
    lines.append(
        "These pre-built objects are re-exported at the top level for "
        "PyMuPDF compatibility:")
    lines.append("")
    lines.append("| Name | Type | Description |")
    lines.append("|---|---|---|")
    lines.append("| `csGRAY` | `Colorspace` | The DeviceGray colorspace singleton. |")
    lines.append("| `csRGB` | `Colorspace` | The DeviceRGB colorspace singleton. |")
    lines.append("| `csCMYK` | `Colorspace` | The DeviceCMYK colorspace singleton. |")
    lines.append("| `TOOLS` | `Tools` | The shared `Tools` helper instance (PyMuPDF `fitz.TOOLS`). |")
    lines.append("| `Base14_fontnames` | `tuple[str, ...]` | Names of the 14 standard PDF fonts. |")
    lines.append("| `Base14_fontdict` | `dict[str, str]` | Alias → canonical Base-14 font name. |")
    lines.append("| `__version__` | `str` | The installed `pdfspine` version string. |")
    lines.append("")

    OUT.write_text(os.linesep.join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({total} constants + 7 instances)")


if __name__ == "__main__":
    main()
