"""Named font registration and actual text insertion (prepared outside the tree)."""

import base64

import pdfspine
import pytest


def test_core14_registration_reuses_xref_without_writing_contents():
    doc = pdfspine.open()
    page = doc.new_page()
    before = page.get_contents()
    xref = page.insert_font(fontname="helv")
    assert isinstance(xref, int) and xref > 0
    assert page.get_contents() == before
    assert page.insert_font(fontname="/helv", fontbuffer=b"invalid") == xref
    page.insert_text((40, 70), "Registered text", fontname="helv")
    reopened = pdfspine.open(stream=doc.tobytes(), filetype="pdf")
    assert "Registered text" in reopened[0].get_text()


@pytest.mark.parametrize("name", ["bad name", "bad/name"])
def test_invalid_font_name_is_atomic(name):
    doc = pdfspine.open()
    page = doc.new_page()
    before = doc.xref_length()
    with pytest.raises(ValueError):
        page.insert_font(fontname=name)
    assert doc.xref_length() == before


def test_unknown_font_without_source_fails_before_mutation():
    doc = pdfspine.open()
    page = doc.new_page()
    before = doc.xref_length()
    with pytest.raises(pdfspine.PdfUnsupportedError):
        page.insert_font(fontname="MissingFont")
    assert doc.xref_length() == before


# Generated by crates/pdf-edit/tests/common/testfont.rs::build_test_ttf
# for space, A, B, Ω, Ж, é at 700-unit advance; no third-party font.
SYNTHETIC_TTF = base64.b64decode(
    "AAEAAAAKAIAAAwAgT1MvMlihXtUAAACsAAAAYGNtYXAGmANHAAABDAAAAFRnbHlmAAAAAAAAAWAAAAAAaGVhZGHQ"
    "Qz0AAAFgAAAANmhoZWEF3gH8AAABmAAAACRobXR4EyQAAAAAAbwAAAAcbG9jYQAAAAAAAAHYAAAAEG1heHAACAAB"
    "AAAB6AAAACBuYW1lAkAGBAAAAggAAAAmcG9zdP87ADIAAAIwAAAAIAAEArwBkAAFAAAB9AH0AAAAZAH0AfQAAAGQ"
    "ADIA+gAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAABPWElQAEAAIAQWAyD/OAAAAyAAyAAAAAEAAAAAAfQCvAAA"
    "ACAAAAAAAAEAAwABAAAADAAEAEgAAAAOAAgAAgAGACAAQQBCAOkDqQQW//8AAAAgAEEAQgDpA6kEFv///+H/wf/B"
    "/x38W/vvAAEAAAAAAAAAAAAAAAAAAAABAAAAAQAA7ntAr18PPPUAAAPoAAAAAAAAAAAAAAAAAAAAAAAA/zgCvAMg"
    "AAAACAACAAAAAAAAAAEAAAMg/zgAAAK8AAAAAAK8AAEAAAAAAAAAAAAAAAAAAAAHArwAAAK8AAACvAAAArwAAAK8"
    "AAACvAAAArwAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAcAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAEgAD"
    "AAEECQAGABQAAABPAHgAaQBwAGQAZgBUAGUAcwB0AAAAAwAAAAAAAP84ADIAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
)


@pytest.mark.parametrize("source", ["buffer", "file"])
def test_registered_truetype_reused_by_text_and_survives_reopen(tmp_path, source):
    doc = pdfspine.open()
    page = doc.new_page()
    kwargs = {"fontbuffer": SYNTHETIC_TTF}
    if source == "file":
        path = tmp_path / "generated.ttf"
        path.write_bytes(SYNTHETIC_TTF)
        kwargs = {"fontfile": path}
    before_contents = page.get_contents()
    xref = page.insert_font(fontname="Custom", **kwargs)
    assert page.get_contents() == before_contents
    page.insert_text((40, 70), "AB ΩЖé", fontname="Custom", fontsize=20)
    assert page.insert_font(fontname="Custom", fontbuffer=b"bad") == xref
    reopened = pdfspine.open(stream=doc.tobytes(), filetype="pdf")
    assert "AB ΩЖé" in reopened[0].get_text()
    assert len(reopened[0].get_fonts()) == 1
    assert reopened[0].get_fonts()[0][0] == xref


@pytest.mark.parametrize(
    "options",
    [{"set_simple": True}, {"wmode": 1}, {"encoding": 1}, {"fontbuffer": b"bad"}],
)
def test_new_unsupported_registration_is_atomic(options):
    doc = pdfspine.open()
    page = doc.new_page()
    before = doc.xref_length()
    with pytest.raises(pdfspine.PdfUnsupportedError):
        page.insert_font(fontname="Custom", **options)
    assert doc.xref_length() == before


def test_shared_glyph_unicode_aliases_survive_reopen_and_append():
    from pathlib import Path

    font = (
        Path(__file__).resolve().parents[2]
        / "crates/pdf-fonts/fonts/liberation/LiberationSans-Regular.ttf"
    )
    doc = pdfspine.open()
    page = doc.new_page()
    xref = page.insert_font(fontname="Registered", fontfile=font)
    page.insert_text((40, 70), "A B\u00a0A", fontname="Registered")
    reopened = pdfspine.open(stream=doc.tobytes(), filetype="pdf")
    reopened[0].insert_text((40, 100), "B\u00a0A B", fontname="Registered")
    final = pdfspine.open(stream=reopened.tobytes(), filetype="pdf")
    assert "A B\u00a0A" in final[0].get_text()
    assert "B\u00a0A B" in final[0].get_text()
    assert final[0].get_fonts()[0][0] == xref


def test_registered_textbox_uses_composite_widths_and_encoding():
    doc = pdfspine.open()
    page = doc.new_page()
    page.insert_font(fontname="Custom", fontbuffer=SYNTHETIC_TTF)
    # Two 700-unit glyphs at 20pt occupy 28pt; a space and a second word
    # require 70pt. This width therefore places the words on separate lines.
    page.insert_textbox(
        pdfspine.Rect(40, 40, 80, 120), "AB ΩЖ", fontname="Custom", fontsize=20
    )
    assert page.get_text().splitlines() == ["AB", "ΩЖ"]


def test_core14_aliases_share_an_equal_existing_font():
    doc = pdfspine.open()
    page = doc.new_page()
    xref = page.insert_font(fontname="helv")
    assert page.insert_font(fontname="Helvetica") == xref


def test_inherited_fonts_preserved_without_mutating_shared_parent():
    doc = pdfspine.open()
    page = doc.new_page()
    doc.new_page()
    page = doc[0]
    font = doc.get_new_xref()
    doc.update_object(
        font,
        "<< /Type /Font /Subtype /Type1 /BaseFont /Courier /Encoding /WinAnsiEncoding >>",
    )
    parent = int(doc.xref_get_key(page.xref, "Parent").split()[0])
    doc.xref_set_key(parent, "Resources", f"<< /Font << /Existing {font} 0 R >> >>")
    doc.xref_set_key(page.xref, "Resources", "null")
    before_parent = doc.xref_object(parent)
    assert page.insert_font(fontname="Existing", fontbuffer=b"bad") == font
    page.insert_font(fontname="helv")
    assert doc.xref_object(parent) == before_parent
    assert {entry[4] for entry in page.get_fonts()} == {"Existing", "helv"}
    page.insert_text((40, 70), "AB", fontname="Existing", fontsize=20)
    assert page.get_text().strip() == "AB"


def test_missing_glyph_fails_without_appending_contents():
    doc = pdfspine.open()
    page = doc.new_page()
    page.insert_font(fontname="Custom", fontbuffer=SYNTHETIC_TTF)
    before = page.get_contents()
    with pytest.raises(pdfspine.PdfUnsupportedError):
        page.insert_text((40, 70), "Missing", fontname="Custom")
    assert page.get_contents() == before


def aliased_synthetic_font():
    """Give A/B one glyph and space/NBSP another in the generated format-4 cmap."""
    import struct

    data = bytearray(SYNTHETIC_TTF)
    tables = struct.unpack_from(">H", data, 4)[0]
    cmap = next(
        struct.unpack_from(">I", data, 12 + 16 * i + 8)[0]
        for i in range(tables)
        if data[12 + 16 * i : 16 + 16 * i] == b"cmap"
    )
    sub = cmap + struct.unpack_from(">I", data, cmap + 8)[0]
    segments = struct.unpack_from(">H", data, sub + 6)[0] // 2
    delta = sub + 16 + 4 * segments
    struct.pack_into(">H", data, delta + 2 * 2, (2 - ord("B")) & 0xFFFF)
    # The fourth sorted segment was é: replace it with NBSP, mapping to space GID 1.
    struct.pack_into(">H", data, sub + 14 + 3 * 2, 0xA0)
    struct.pack_into(">H", data, sub + 16 + 2 * segments + 3 * 2, 0xA0)
    struct.pack_into(">H", data, delta + 3 * 2, (1 - 0xA0) & 0xFFFF)
    return bytes(data)


def test_two_unicode_pairs_sharing_gids_keep_distinct_cids_after_reopen():
    doc = pdfspine.open()
    page = doc.new_page()
    page.insert_font(fontname="Aliases", fontbuffer=aliased_synthetic_font())
    page.insert_text((40, 70), "A B\u00a0A", fontname="Aliases")
    reopened = pdfspine.open(stream=doc.tobytes(), filetype="pdf")
    reopened[0].insert_text((40, 100), "BA\u00a0B A", fontname="Aliases")
    assert "A B\u00a0A" in reopened[0].get_text()
    assert "BA\u00a0B A" in reopened[0].get_text()


def synthetic_with_cmap_groups(format_number, groups):
    """Replace the generated cmap with a bounded format-12/13 test program."""
    import struct

    data = bytearray(SYNTHETIC_TTF)
    tables = struct.unpack_from(">H", data, 4)[0]
    record = next(
        12 + 16 * i for i in range(tables) if data[12 + 16 * i : 16 + 16 * i] == b"cmap"
    )
    offset, capacity = struct.unpack_from(">II", data, record + 8)
    sub = struct.pack(">HHIII", format_number, 0, 16 + len(groups) * 12, 0, len(groups))
    sub += b"".join(struct.pack(">III", *group) for group in groups)
    cmap = struct.pack(">HHHHI", 0, 1, 3, 10, 12) + sub
    assert len(cmap) <= capacity
    data[offset : offset + len(cmap)] = cmap
    struct.pack_into(">I", data, record + 12, len(cmap))
    return bytes(data)


def test_astral_cmap_character_survives_registered_reopen():
    program = synthetic_with_cmap_groups(12, [(0x41, 0x41, 2), (0x1F600, 0x1F600, 3)])
    doc = pdfspine.open()
    page = doc.new_page()
    page.insert_font(fontname="Astral", fontbuffer=program)
    page.insert_text((40, 70), "A😀", fontname="Astral")
    reopened = pdfspine.open(stream=doc.tobytes(), filetype="pdf")
    reopened[0].insert_text((40, 100), "😀A", fontname="Astral")
    assert reopened[0].get_text().splitlines() == ["A😀", "😀A"]


def test_cid_capacity_overflow_rejected_before_new_xrefs():
    program = synthetic_with_cmap_groups(13, [(0, 65535, 1)])
    doc = pdfspine.open()
    page = doc.new_page()
    before = doc.xref_length()
    with pytest.raises(pdfspine.PdfUnsupportedError, match="capacity"):
        page.insert_font(fontname="TooMany", fontbuffer=program)
    assert doc.xref_length() == before


@pytest.mark.parametrize("text", ["A😀", "A😀\n😀A"])
def test_textbox_font_without_space_can_write_words_and_explicit_lines(text):
    program = synthetic_with_cmap_groups(12, [(0x41, 0x41, 2), (0x1F600, 0x1F600, 3)])
    doc = pdfspine.open()
    page = doc.new_page()
    page.insert_font(fontname="NoSpace", fontbuffer=program)
    page.insert_textbox(pdfspine.Rect(40, 40, 200, 150), text, fontname="NoSpace")
    assert page.get_text().splitlines() == text.splitlines()


def test_registered_simple_font_uses_explicit_pdf_widths_in_textbox():
    doc = pdfspine.open()
    page = doc.new_page()
    font = doc.get_new_xref()
    widths = " ".join(["900"] * 35)  # character codes 32 through 66.
    doc.update_object(
        font,
        f"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding /FirstChar 32 /LastChar 66 /Widths [{widths}] >>",
    )
    doc.xref_set_key(page.xref, "Resources", f"<< /Font << /Wide {font} 0 R >> >>")
    assert page.insert_font(fontname="Wide") == font
    # Actual width is 90pt for AB-space-AB; Helvetica AFM would fit in 70pt.
    page.insert_textbox(
        pdfspine.Rect(40, 40, 110, 150), "AB AB", fontname="Wide", fontsize=20
    )
    assert page.get_text().splitlines() == ["AB", "AB"]
