//! Simple-font base encodings: code (0–255) → glyph name (PRD §8.5).
//!
//! These are the ISO 32000-1 **Annex D** tables — public-domain facts
//! (Standard, WinAnsi, MacRoman, PDFDoc) plus the Symbol and ZapfDingbats
//! built-in encodings. We store each as a sparse `(code, name)` list and build
//! the dense `[Option<&str>; 256]` lookup once, lazily.
//!
//! The values are glyph *names*; conversion to Unicode is the job of
//! [`crate::glyphlist`]. `/Differences` overrides land in [`crate::mapper`].

use std::sync::OnceLock;

/// A base encoding selectable by `/Encoding` name or `/BaseEncoding`.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum BaseEncoding {
    /// Adobe StandardEncoding (Annex D.1).
    Standard,
    /// WinAnsiEncoding (Annex D.2) — CP1252-ish.
    WinAnsi,
    /// MacRomanEncoding (Annex D.3).
    MacRoman,
    /// PDFDocEncoding (Annex D.3) — used for text strings / built-in default.
    PdfDoc,
    /// The Symbol font built-in encoding (Annex D.5).
    Symbol,
    /// The ZapfDingbats font built-in encoding (Annex D.6).
    ZapfDingbats,
}

impl BaseEncoding {
    /// Resolves a `/Encoding` (or `/BaseEncoding`) name to a base encoding.
    #[must_use]
    pub fn from_name(name: &[u8]) -> Option<BaseEncoding> {
        match name {
            b"StandardEncoding" => Some(BaseEncoding::Standard),
            b"WinAnsiEncoding" => Some(BaseEncoding::WinAnsi),
            b"MacRomanEncoding" => Some(BaseEncoding::MacRoman),
            b"PDFDocEncoding" => Some(BaseEncoding::PdfDoc),
            // `MacExpertEncoding` is an expert set we do not table; callers fall
            // back to Standard. Symbol/ZapfDingbats are selected by base-font.
            _ => None,
        }
    }

    /// The dense code → glyph-name table for this encoding.
    #[must_use]
    pub fn table(self) -> &'static [Option<&'static str>; 256] {
        match self {
            BaseEncoding::Standard => standard(),
            BaseEncoding::WinAnsi => winansi(),
            BaseEncoding::MacRoman => macroman(),
            BaseEncoding::PdfDoc => pdfdoc(),
            BaseEncoding::Symbol => symbol(),
            BaseEncoding::ZapfDingbats => zapf(),
        }
    }

    /// The glyph name for `code` in this encoding, if any.
    #[must_use]
    pub fn glyph_name(self, code: u8) -> Option<&'static str> {
        self.table()[code as usize]
    }
}

/// Builds a dense table from a sparse `(code, name)` slice.
fn dense(pairs: &[(u8, &'static str)]) -> [Option<&'static str>; 256] {
    let mut t: [Option<&'static str>; 256] = [None; 256];
    for &(code, name) in pairs {
        t[code as usize] = Some(name);
    }
    t
}

macro_rules! lazy_table {
    ($fn_name:ident, $pairs:expr) => {
        fn $fn_name() -> &'static [Option<&'static str>; 256] {
            static T: OnceLock<[Option<&'static str>; 256]> = OnceLock::new();
            T.get_or_init(|| dense($pairs))
        }
    };
}

// ASCII 0x20..0x7E is (nearly) shared by Standard/WinAnsi/MacRoman/PDFDoc; the
// few divergences (Standard quotes, etc.) are encoded per table.
const ASCII_COMMON: &[(u8, &str)] = &[
    (0x20, "space"),
    (0x21, "exclam"),
    (0x22, "quotedbl"),
    (0x23, "numbersign"),
    (0x24, "dollar"),
    (0x25, "percent"),
    (0x26, "ampersand"),
    (0x28, "parenleft"),
    (0x29, "parenright"),
    (0x2A, "asterisk"),
    (0x2B, "plus"),
    (0x2C, "comma"),
    (0x2D, "hyphen"),
    (0x2E, "period"),
    (0x2F, "slash"),
    (0x30, "zero"),
    (0x31, "one"),
    (0x32, "two"),
    (0x33, "three"),
    (0x34, "four"),
    (0x35, "five"),
    (0x36, "six"),
    (0x37, "seven"),
    (0x38, "eight"),
    (0x39, "nine"),
    (0x3A, "colon"),
    (0x3B, "semicolon"),
    (0x3C, "less"),
    (0x3D, "equal"),
    (0x3E, "greater"),
    (0x3F, "question"),
    (0x40, "at"),
    (0x41, "A"),
    (0x42, "B"),
    (0x43, "C"),
    (0x44, "D"),
    (0x45, "E"),
    (0x46, "F"),
    (0x47, "G"),
    (0x48, "H"),
    (0x49, "I"),
    (0x4A, "J"),
    (0x4B, "K"),
    (0x4C, "L"),
    (0x4D, "M"),
    (0x4E, "N"),
    (0x4F, "O"),
    (0x50, "P"),
    (0x51, "Q"),
    (0x52, "R"),
    (0x53, "S"),
    (0x54, "T"),
    (0x55, "U"),
    (0x56, "V"),
    (0x57, "W"),
    (0x58, "X"),
    (0x59, "Y"),
    (0x5A, "Z"),
    (0x5B, "bracketleft"),
    (0x5C, "backslash"),
    (0x5D, "bracketright"),
    (0x5E, "asciicircum"),
    (0x5F, "underscore"),
    (0x61, "a"),
    (0x62, "b"),
    (0x63, "c"),
    (0x64, "d"),
    (0x65, "e"),
    (0x66, "f"),
    (0x67, "g"),
    (0x68, "h"),
    (0x69, "i"),
    (0x6A, "j"),
    (0x6B, "k"),
    (0x6C, "l"),
    (0x6D, "m"),
    (0x6E, "n"),
    (0x6F, "o"),
    (0x70, "p"),
    (0x71, "q"),
    (0x72, "r"),
    (0x73, "s"),
    (0x74, "t"),
    (0x75, "u"),
    (0x76, "v"),
    (0x77, "w"),
    (0x78, "x"),
    (0x79, "y"),
    (0x7A, "z"),
    (0x7B, "braceleft"),
    (0x7C, "bar"),
    (0x7D, "braceright"),
    (0x7E, "asciitilde"),
];

fn with_common(extra: &[(u8, &'static str)]) -> Vec<(u8, &'static str)> {
    let mut v: Vec<(u8, &'static str)> = ASCII_COMMON.to_vec();
    v.extend_from_slice(extra);
    v
}

// --- StandardEncoding (Annex D.1) ----------------------------------------

fn standard() -> &'static [Option<&'static str>; 256] {
    static T: OnceLock<[Option<&'static str>; 256]> = OnceLock::new();
    T.get_or_init(|| {
        let pairs = with_common(&[
            (0x27, "quoteright"),
            (0x60, "quoteleft"),
            (0xA1, "exclamdown"),
            (0xA2, "cent"),
            (0xA3, "sterling"),
            (0xA4, "fraction"),
            (0xA5, "yen"),
            (0xA6, "florin"),
            (0xA7, "section"),
            (0xA8, "currency"),
            (0xA9, "quotesingle"),
            (0xAA, "quotedblleft"),
            (0xAB, "guillemotleft"),
            (0xAC, "guilsinglleft"),
            (0xAD, "guilsinglright"),
            (0xAE, "fi"),
            (0xAF, "fl"),
            (0xB1, "endash"),
            (0xB2, "dagger"),
            (0xB3, "daggerdbl"),
            (0xB4, "periodcentered"),
            (0xB6, "paragraph"),
            (0xB7, "bullet"),
            (0xB8, "quotesinglbase"),
            (0xB9, "quotedblbase"),
            (0xBA, "quotedblright"),
            (0xBB, "guillemotright"),
            (0xBC, "ellipsis"),
            (0xBD, "perthousand"),
            (0xBF, "questiondown"),
            (0xC1, "grave"),
            (0xC2, "acute"),
            (0xC3, "circumflex"),
            (0xC4, "tilde"),
            (0xC5, "macron"),
            (0xC6, "breve"),
            (0xC7, "dotaccent"),
            (0xC8, "dieresis"),
            (0xCA, "ring"),
            (0xCB, "cedilla"),
            (0xCD, "hungarumlaut"),
            (0xCE, "ogonek"),
            (0xCF, "caron"),
            (0xD0, "emdash"),
            (0xE1, "AE"),
            (0xE3, "ordfeminine"),
            (0xE8, "Lslash"),
            (0xE9, "Oslash"),
            (0xEA, "OE"),
            (0xEB, "ordmasculine"),
            (0xF1, "ae"),
            (0xF5, "dotlessi"),
            (0xF8, "lslash"),
            (0xF9, "oslash"),
            (0xFA, "oe"),
            (0xFB, "germandbls"),
        ]);
        dense(&pairs)
    })
}

// --- WinAnsiEncoding (Annex D.2) -----------------------------------------

fn winansi() -> &'static [Option<&'static str>; 256] {
    static T: OnceLock<[Option<&'static str>; 256]> = OnceLock::new();
    T.get_or_init(|| {
        let pairs = with_common(&[
            (0x27, "quotesingle"),
            (0x60, "grave"),
            (0x80, "Euro"),
            (0x82, "quotesinglbase"),
            (0x83, "florin"),
            (0x84, "quotedblbase"),
            (0x85, "ellipsis"),
            (0x86, "dagger"),
            (0x87, "daggerdbl"),
            (0x88, "circumflex"),
            (0x89, "perthousand"),
            (0x8A, "Scaron"),
            (0x8B, "guilsinglleft"),
            (0x8C, "OE"),
            (0x8E, "Zcaron"),
            (0x91, "quoteleft"),
            (0x92, "quoteright"),
            (0x93, "quotedblleft"),
            (0x94, "quotedblright"),
            (0x95, "bullet"),
            (0x96, "endash"),
            (0x97, "emdash"),
            (0x98, "tilde"),
            (0x99, "trademark"),
            (0x9A, "scaron"),
            (0x9B, "guilsinglright"),
            (0x9C, "oe"),
            (0x9E, "zcaron"),
            (0x9F, "Ydieresis"),
            (0xA0, "space"),
            (0xA1, "exclamdown"),
            (0xA2, "cent"),
            (0xA3, "sterling"),
            (0xA4, "currency"),
            (0xA5, "yen"),
            (0xA6, "brokenbar"),
            (0xA7, "section"),
            (0xA8, "dieresis"),
            (0xA9, "copyright"),
            (0xAA, "ordfeminine"),
            (0xAB, "guillemotleft"),
            (0xAC, "logicalnot"),
            (0xAD, "hyphen"),
            (0xAE, "registered"),
            (0xAF, "macron"),
            (0xB0, "degree"),
            (0xB1, "plusminus"),
            (0xB2, "twosuperior"),
            (0xB3, "threesuperior"),
            (0xB4, "acute"),
            (0xB5, "mu"),
            (0xB6, "paragraph"),
            (0xB7, "periodcentered"),
            (0xB8, "cedilla"),
            (0xB9, "onesuperior"),
            (0xBA, "ordmasculine"),
            (0xBB, "guillemotright"),
            (0xBC, "onequarter"),
            (0xBD, "onehalf"),
            (0xBE, "threequarters"),
            (0xBF, "questiondown"),
            (0xC0, "Agrave"),
            (0xC1, "Aacute"),
            (0xC2, "Acircumflex"),
            (0xC3, "Atilde"),
            (0xC4, "Adieresis"),
            (0xC5, "Aring"),
            (0xC6, "AE"),
            (0xC7, "Ccedilla"),
            (0xC8, "Egrave"),
            (0xC9, "Eacute"),
            (0xCA, "Ecircumflex"),
            (0xCB, "Edieresis"),
            (0xCC, "Igrave"),
            (0xCD, "Iacute"),
            (0xCE, "Icircumflex"),
            (0xCF, "Idieresis"),
            (0xD0, "Eth"),
            (0xD1, "Ntilde"),
            (0xD2, "Ograve"),
            (0xD3, "Oacute"),
            (0xD4, "Ocircumflex"),
            (0xD5, "Otilde"),
            (0xD6, "Odieresis"),
            (0xD7, "multiply"),
            (0xD8, "Oslash"),
            (0xD9, "Ugrave"),
            (0xDA, "Uacute"),
            (0xDB, "Ucircumflex"),
            (0xDC, "Udieresis"),
            (0xDD, "Yacute"),
            (0xDE, "Thorn"),
            (0xDF, "germandbls"),
            (0xE0, "agrave"),
            (0xE1, "aacute"),
            (0xE2, "acircumflex"),
            (0xE3, "atilde"),
            (0xE4, "adieresis"),
            (0xE5, "aring"),
            (0xE6, "ae"),
            (0xE7, "ccedilla"),
            (0xE8, "egrave"),
            (0xE9, "eacute"),
            (0xEA, "ecircumflex"),
            (0xEB, "edieresis"),
            (0xEC, "igrave"),
            (0xED, "iacute"),
            (0xEE, "icircumflex"),
            (0xEF, "idieresis"),
            (0xF0, "eth"),
            (0xF1, "ntilde"),
            (0xF2, "ograve"),
            (0xF3, "oacute"),
            (0xF4, "ocircumflex"),
            (0xF5, "otilde"),
            (0xF6, "odieresis"),
            (0xF7, "divide"),
            (0xF8, "oslash"),
            (0xF9, "ugrave"),
            (0xFA, "uacute"),
            (0xFB, "ucircumflex"),
            (0xFC, "udieresis"),
            (0xFD, "yacute"),
            (0xFE, "thorn"),
            (0xFF, "ydieresis"),
        ]);
        dense(&pairs)
    })
}

// --- MacRomanEncoding (Annex D.3) ----------------------------------------

fn macroman() -> &'static [Option<&'static str>; 256] {
    static T: OnceLock<[Option<&'static str>; 256]> = OnceLock::new();
    T.get_or_init(|| {
        let pairs = with_common(&[
            (0x27, "quotesingle"),
            (0x60, "grave"),
            (0x80, "Adieresis"),
            (0x81, "Aring"),
            (0x82, "Ccedilla"),
            (0x83, "Eacute"),
            (0x84, "Ntilde"),
            (0x85, "Odieresis"),
            (0x86, "Udieresis"),
            (0x87, "aacute"),
            (0x88, "agrave"),
            (0x89, "acircumflex"),
            (0x8A, "adieresis"),
            (0x8B, "atilde"),
            (0x8C, "aring"),
            (0x8D, "ccedilla"),
            (0x8E, "eacute"),
            (0x8F, "egrave"),
            (0x90, "ecircumflex"),
            (0x91, "edieresis"),
            (0x92, "iacute"),
            (0x93, "igrave"),
            (0x94, "icircumflex"),
            (0x95, "idieresis"),
            (0x96, "ntilde"),
            (0x97, "oacute"),
            (0x98, "ograve"),
            (0x99, "ocircumflex"),
            (0x9A, "odieresis"),
            (0x9B, "otilde"),
            (0x9C, "uacute"),
            (0x9D, "ugrave"),
            (0x9E, "ucircumflex"),
            (0x9F, "udieresis"),
            (0xA0, "dagger"),
            (0xA1, "degree"),
            (0xA2, "cent"),
            (0xA3, "sterling"),
            (0xA4, "section"),
            (0xA5, "bullet"),
            (0xA6, "paragraph"),
            (0xA7, "germandbls"),
            (0xA8, "registered"),
            (0xA9, "copyright"),
            (0xAA, "trademark"),
            (0xAB, "acute"),
            (0xAC, "dieresis"),
            (0xAD, "notequal"),
            (0xAE, "AE"),
            (0xAF, "Oslash"),
            (0xB0, "infinity"),
            (0xB1, "plusminus"),
            (0xB2, "lessequal"),
            (0xB3, "greaterequal"),
            (0xB4, "yen"),
            (0xB5, "mu"),
            (0xB6, "partialdiff"),
            (0xB7, "summation"),
            (0xB8, "product"),
            (0xB9, "pi"),
            (0xBA, "integral"),
            (0xBB, "ordfeminine"),
            (0xBC, "ordmasculine"),
            (0xBD, "Omega"),
            (0xBE, "ae"),
            (0xBF, "oslash"),
            (0xC0, "questiondown"),
            (0xC1, "exclamdown"),
            (0xC2, "logicalnot"),
            (0xC3, "radical"),
            (0xC4, "florin"),
            (0xC5, "approxequal"),
            (0xC6, "Delta"),
            (0xC7, "guillemotleft"),
            (0xC8, "guillemotright"),
            (0xC9, "ellipsis"),
            (0xCA, "space"),
            (0xCB, "Agrave"),
            (0xCC, "Atilde"),
            (0xCD, "Otilde"),
            (0xCE, "OE"),
            (0xCF, "oe"),
            (0xD0, "endash"),
            (0xD1, "emdash"),
            (0xD2, "quotedblleft"),
            (0xD3, "quotedblright"),
            (0xD4, "quoteleft"),
            (0xD5, "quoteright"),
            (0xD6, "divide"),
            (0xD7, "lozenge"),
            (0xD8, "ydieresis"),
            (0xD9, "Ydieresis"),
            (0xDA, "fraction"),
            (0xDB, "currency"),
            (0xDC, "guilsinglleft"),
            (0xDD, "guilsinglright"),
            (0xDE, "fi"),
            (0xDF, "fl"),
            (0xE0, "daggerdbl"),
            (0xE1, "periodcentered"),
            (0xE2, "quotesinglbase"),
            (0xE3, "quotedblbase"),
            (0xE4, "perthousand"),
            (0xE5, "Acircumflex"),
            (0xE6, "Ecircumflex"),
            (0xE7, "Aacute"),
            (0xE8, "Edieresis"),
            (0xE9, "Egrave"),
            (0xEA, "Iacute"),
            (0xEB, "Icircumflex"),
            (0xEC, "Idieresis"),
            (0xED, "Igrave"),
            (0xEE, "Oacute"),
            (0xEF, "Ocircumflex"),
            (0xF0, "apple"),
            (0xF1, "Ograve"),
            (0xF2, "Uacute"),
            (0xF3, "Ucircumflex"),
            (0xF4, "Ugrave"),
            (0xF5, "dotlessi"),
            (0xF6, "circumflex"),
            (0xF7, "tilde"),
            (0xF8, "macron"),
            (0xF9, "breve"),
            (0xFA, "dotaccent"),
            (0xFB, "ring"),
            (0xFC, "cedilla"),
            (0xFD, "hungarumlaut"),
            (0xFE, "ogonek"),
            (0xFF, "caron"),
        ]);
        dense(&pairs)
    })
}

// --- PDFDocEncoding (Annex D.3) ------------------------------------------
//
// PDFDoc matches WinAnsi for most of the 0xA0..0xFF Latin-1 range, but the
// 0x18..0x1F C0-area and the 0x80..0xA0 block carry the dedicated PDFDoc
// glyphs (Euro at 0xA0, the bullet at 0x80, etc.). We layer the PDFDoc-specific
// codes over the WinAnsi Latin block.

fn pdfdoc() -> &'static [Option<&'static str>; 256] {
    static T: OnceLock<[Option<&'static str>; 256]> = OnceLock::new();
    T.get_or_init(|| {
        // Start from WinAnsi (shares the bulk of Latin-1) and override.
        let mut t = *winansi();
        let overrides: &[(u8, &str)] = &[
            (0x18, "breve"),
            (0x19, "caron"),
            (0x1A, "circumflex"),
            (0x1B, "dotaccent"),
            (0x1C, "hungarumlaut"),
            (0x1D, "ogonek"),
            (0x1E, "ring"),
            (0x1F, "tilde"),
            (0x80, "bullet"),
            (0x81, "dagger"),
            (0x82, "daggerdbl"),
            (0x83, "ellipsis"),
            (0x84, "emdash"),
            (0x85, "endash"),
            (0x86, "florin"),
            (0x87, "fraction"),
            (0x88, "guilsinglleft"),
            (0x89, "guilsinglright"),
            (0x8A, "minus"),
            (0x8B, "perthousand"),
            (0x8C, "quotedblbase"),
            (0x8D, "quotedblleft"),
            (0x8E, "quotedblright"),
            (0x8F, "quoteleft"),
            (0x90, "quoteright"),
            (0x91, "quotesinglbase"),
            (0x92, "trademark"),
            (0x93, "fi"),
            (0x94, "fl"),
            (0x95, "Lslash"),
            (0x96, "OE"),
            (0x97, "Scaron"),
            (0x98, "Ydieresis"),
            (0x99, "Zcaron"),
            (0x9A, "dotlessi"),
            (0x9B, "lslash"),
            (0x9C, "oe"),
            (0x9D, "scaron"),
            (0x9E, "zcaron"),
            (0xA0, "Euro"),
        ];
        for &(c, n) in overrides {
            t[c as usize] = Some(n);
        }
        t
    })
}

// --- Symbol built-in encoding (Annex D.5) --------------------------------
//
// The Symbol font has its own encoding (Greek letters, math). We table the
// commonly-encountered codes; absent codes fall through to None (then notdef).

lazy_table!(
    symbol,
    &[
        (0x20, "space"),
        (0x21, "exclam"),
        (0x22, "universal"),
        (0x23, "numbersign"),
        (0x24, "existential"),
        (0x25, "percent"),
        (0x26, "ampersand"),
        (0x27, "suchthat"),
        (0x28, "parenleft"),
        (0x29, "parenright"),
        (0x2A, "asteriskmath"),
        (0x2B, "plus"),
        (0x2C, "comma"),
        (0x2D, "minus"),
        (0x2E, "period"),
        (0x2F, "slash"),
        (0x30, "zero"),
        (0x31, "one"),
        (0x32, "two"),
        (0x33, "three"),
        (0x34, "four"),
        (0x35, "five"),
        (0x36, "six"),
        (0x37, "seven"),
        (0x38, "eight"),
        (0x39, "nine"),
        (0x3A, "colon"),
        (0x3B, "semicolon"),
        (0x3C, "less"),
        (0x3D, "equal"),
        (0x3E, "greater"),
        (0x3F, "question"),
        (0x40, "congruent"),
        (0x41, "Alpha"),
        (0x42, "Beta"),
        (0x43, "Chi"),
        (0x44, "Delta"),
        (0x45, "Epsilon"),
        (0x46, "Phi"),
        (0x47, "Gamma"),
        (0x48, "Eta"),
        (0x49, "Iota"),
        (0x4A, "theta1"),
        (0x4B, "Kappa"),
        (0x4C, "Lambda"),
        (0x4D, "Mu"),
        (0x4E, "Nu"),
        (0x4F, "Omicron"),
        (0x50, "Pi"),
        (0x51, "Theta"),
        (0x52, "Rho"),
        (0x53, "Sigma"),
        (0x54, "Tau"),
        (0x55, "Upsilon"),
        (0x56, "sigma1"),
        (0x57, "Omega"),
        (0x58, "Xi"),
        (0x59, "Psi"),
        (0x5A, "Zeta"),
        (0x5B, "bracketleft"),
        (0x5C, "therefore"),
        (0x5D, "bracketright"),
        (0x5E, "perpendicular"),
        (0x5F, "underscore"),
        (0x60, "radicalex"),
        (0x61, "alpha"),
        (0x62, "beta"),
        (0x63, "chi"),
        (0x64, "delta"),
        (0x65, "epsilon"),
        (0x66, "phi"),
        (0x67, "gamma"),
        (0x68, "eta"),
        (0x69, "iota"),
        (0x6A, "phi1"),
        (0x6B, "kappa"),
        (0x6C, "lambda"),
        (0x6D, "mu"),
        (0x6E, "nu"),
        (0x6F, "omicron"),
        (0x70, "pi"),
        (0x71, "theta"),
        (0x72, "rho"),
        (0x73, "sigma"),
        (0x74, "tau"),
        (0x75, "upsilon"),
        (0x76, "omega1"),
        (0x77, "omega"),
        (0x78, "xi"),
        (0x79, "psi"),
        (0x7A, "zeta"),
        (0x7B, "braceleft"),
        (0x7C, "bar"),
        (0x7D, "braceright"),
        (0x7E, "similar"),
        (0xA0, "Euro"),
        (0xB7, "bullet"),
        (0xD7, "product"),
    ]
);

// --- ZapfDingbats built-in encoding (Annex D.6) --------------------------
//
// ZapfDingbats codes 0x20..0xFE map to a* glyph names (a1..a202). We table the
// canonical run; the AGL resolves a* names to their Dingbat Unicode points.

lazy_table!(
    zapf,
    &[
        (0x20, "space"),
        (0x21, "a1"),
        (0x22, "a2"),
        (0x23, "a202"),
        (0x24, "a3"),
        (0x25, "a4"),
        (0x26, "a5"),
        (0x27, "a119"),
        (0x28, "a118"),
        (0x29, "a117"),
        (0x2A, "a11"),
        (0x2B, "a12"),
        (0x2C, "a13"),
        (0x2D, "a14"),
        (0x2E, "a15"),
        (0x2F, "a16"),
        (0x30, "a105"),
        (0x31, "a17"),
        (0x32, "a18"),
        (0x33, "a19"),
        (0x34, "a20"),
        (0x35, "a21"),
        (0x36, "a22"),
        (0x37, "a23"),
        (0x38, "a24"),
        (0x39, "a25"),
        (0x3A, "a26"),
        (0x3B, "a27"),
        (0x3C, "a28"),
        (0x3D, "a6"),
        (0x3E, "a7"),
        (0x3F, "a8"),
        (0x40, "a9"),
        (0x41, "a10"),
        (0x42, "a29"),
        (0x43, "a30"),
        (0x44, "a31"),
        (0x45, "a32"),
        (0x46, "a33"),
        (0x47, "a34"),
        (0x48, "a35"),
        (0x49, "a36"),
        (0x4A, "a37"),
        (0x4B, "a38"),
        (0x4C, "a39"),
        (0x4D, "a40"),
        (0x4E, "a41"),
        (0x4F, "a42"),
        (0x50, "a43"),
        (0x51, "a44"),
        (0x52, "a45"),
        (0x53, "a46"),
        (0x54, "a47"),
        (0x55, "a48"),
        (0x56, "a49"),
        (0x57, "a50"),
        (0x58, "a51"),
        (0x59, "a52"),
        (0x5A, "a53"),
        (0x5B, "a54"),
        (0x5C, "a55"),
        (0x5D, "a56"),
        (0x5E, "a57"),
        (0x5F, "a58"),
        (0x60, "a59"),
        (0x61, "a60"),
        (0x62, "a61"),
        (0x63, "a62"),
        (0x64, "a63"),
        (0x65, "a64"),
        (0x66, "a65"),
        (0x67, "a66"),
        (0x68, "a67"),
        (0x69, "a68"),
        (0x6A, "a69"),
        (0x6B, "a70"),
        (0x6C, "a71"),
        (0x6D, "a72"),
        (0x6E, "a73"),
        (0x6F, "a74"),
        (0x70, "a203"),
        (0x71, "a75"),
        (0x72, "a204"),
        (0x73, "a76"),
        (0x74, "a77"),
        (0x75, "a78"),
        (0x76, "a79"),
        (0x77, "a81"),
        (0x78, "a82"),
        (0x79, "a83"),
        (0x7A, "a84"),
        (0x7B, "a97"),
        (0x7C, "a98"),
        (0x7D, "a99"),
        (0x7E, "a100"),
    ]
);
